// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module calo_trigger_tower_stream_ref_produce_em_jet_cluster_stream_from_towers_Pipeline_VITIS_LOOP_486_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        tower_in_TVALID,
        local_ht,
        linebuf_6_address0,
        linebuf_6_ce0,
        linebuf_6_we0,
        linebuf_6_d0,
        linebuf_5_address0,
        linebuf_5_ce0,
        linebuf_5_we0,
        linebuf_5_d0,
        linebuf_4_address0,
        linebuf_4_ce0,
        linebuf_4_we0,
        linebuf_4_d0,
        linebuf_3_address0,
        linebuf_3_ce0,
        linebuf_3_we0,
        linebuf_3_d0,
        linebuf_2_address0,
        linebuf_2_ce0,
        linebuf_2_we0,
        linebuf_2_d0,
        linebuf_1_address0,
        linebuf_1_ce0,
        linebuf_1_we0,
        linebuf_1_d0,
        linebuf_address0,
        linebuf_ce0,
        linebuf_we0,
        linebuf_d0,
        tower_in_TDATA,
        tower_in_TREADY,
        empty_25,
        empty,
        local_ht_1_out,
        local_ht_1_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   tower_in_TVALID;
input  [23:0] local_ht;
output  [5:0] linebuf_6_address0;
output   linebuf_6_ce0;
output   linebuf_6_we0;
output  [11:0] linebuf_6_d0;
output  [5:0] linebuf_5_address0;
output   linebuf_5_ce0;
output   linebuf_5_we0;
output  [11:0] linebuf_5_d0;
output  [5:0] linebuf_4_address0;
output   linebuf_4_ce0;
output   linebuf_4_we0;
output  [11:0] linebuf_4_d0;
output  [5:0] linebuf_3_address0;
output   linebuf_3_ce0;
output   linebuf_3_we0;
output  [11:0] linebuf_3_d0;
output  [5:0] linebuf_2_address0;
output   linebuf_2_ce0;
output   linebuf_2_we0;
output  [11:0] linebuf_2_d0;
output  [5:0] linebuf_1_address0;
output   linebuf_1_ce0;
output   linebuf_1_we0;
output  [11:0] linebuf_1_d0;
output  [5:0] linebuf_address0;
output   linebuf_ce0;
output   linebuf_we0;
output  [11:0] linebuf_d0;
input  [15:0] tower_in_TDATA;
output   tower_in_TREADY;
input  [2:0] empty_25;
input  [0:0] empty;
output  [23:0] local_ht_1_out;
output   local_ht_1_out_ap_vld;

reg ap_idle;
reg tower_in_TREADY;
reg local_ht_1_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln486_fu_221_p2;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    tower_in_TDATA_blk_n;
wire   [63:0] zext_ln486_fu_236_p1;
reg   [23:0] local_ht_1_fu_78;
wire   [23:0] local_ht_2_fu_262_p2;
wire    ap_loop_init;
reg   [23:0] ap_sig_allocacmp_local_ht_1_load;
reg   [5:0] phi_fu_82;
wire   [5:0] add_ln486_fu_227_p2;
reg   [5:0] ap_sig_allocacmp_phi_1;
wire   [2:0] tmp_16_read_fu_92_p2;
reg    linebuf_5_we0_local;
wire   [11:0] incoming_fu_247_p1;
reg    linebuf_5_ce0_local;
reg    linebuf_4_we0_local;
reg    linebuf_4_ce0_local;
reg    linebuf_3_we0_local;
reg    linebuf_3_ce0_local;
reg    linebuf_2_we0_local;
reg    linebuf_2_ce0_local;
reg    linebuf_1_we0_local;
reg    linebuf_1_ce0_local;
reg    linebuf_we0_local;
reg    linebuf_ce0_local;
reg    linebuf_6_we0_local;
reg    linebuf_6_ce0_local;
wire   [23:0] zext_ln490_fu_258_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 local_ht_1_fu_78 = 24'd0;
#0 phi_fu_82 = 6'd0;
#0 ap_done_reg = 1'b0;
end

calo_trigger_tower_stream_ref_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln486_fu_221_p2 == 1'd0)) begin
            local_ht_1_fu_78 <= local_ht_2_fu_262_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            local_ht_1_fu_78 <= local_ht;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln486_fu_221_p2 == 1'd0)) begin
            phi_fu_82 <= add_ln486_fu_227_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            phi_fu_82 <= 6'd0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln486_fu_221_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_local_ht_1_load = local_ht;
    end else begin
        ap_sig_allocacmp_local_ht_1_load = local_ht_1_fu_78;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_phi_1 = 6'd0;
    end else begin
        ap_sig_allocacmp_phi_1 = phi_fu_82;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        linebuf_1_ce0_local = 1'b1;
    end else begin
        linebuf_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln486_fu_221_p2 == 1'd0) & (tmp_16_read_fu_92_p2 == 3'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        linebuf_1_we0_local = 1'b1;
    end else begin
        linebuf_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        linebuf_2_ce0_local = 1'b1;
    end else begin
        linebuf_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln486_fu_221_p2 == 1'd0) & (tmp_16_read_fu_92_p2 == 3'd2) & (1'b1 == ap_CS_fsm_state1))) begin
        linebuf_2_we0_local = 1'b1;
    end else begin
        linebuf_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        linebuf_3_ce0_local = 1'b1;
    end else begin
        linebuf_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln486_fu_221_p2 == 1'd0) & (tmp_16_read_fu_92_p2 == 3'd3) & (1'b1 == ap_CS_fsm_state1))) begin
        linebuf_3_we0_local = 1'b1;
    end else begin
        linebuf_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        linebuf_4_ce0_local = 1'b1;
    end else begin
        linebuf_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln486_fu_221_p2 == 1'd0) & (tmp_16_read_fu_92_p2 == 3'd4) & (1'b1 == ap_CS_fsm_state1))) begin
        linebuf_4_we0_local = 1'b1;
    end else begin
        linebuf_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        linebuf_5_ce0_local = 1'b1;
    end else begin
        linebuf_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln486_fu_221_p2 == 1'd0) & (tmp_16_read_fu_92_p2 == 3'd5) & (1'b1 == ap_CS_fsm_state1))) begin
        linebuf_5_we0_local = 1'b1;
    end else begin
        linebuf_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        linebuf_6_ce0_local = 1'b1;
    end else begin
        linebuf_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (((icmp_ln486_fu_221_p2 == 1'd0) & (tmp_16_read_fu_92_p2 == 3'd6)) | ((icmp_ln486_fu_221_p2 == 1'd0) & (tmp_16_read_fu_92_p2 == 3'd7))))) begin
        linebuf_6_we0_local = 1'b1;
    end else begin
        linebuf_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        linebuf_ce0_local = 1'b1;
    end else begin
        linebuf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln486_fu_221_p2 == 1'd0) & (tmp_16_read_fu_92_p2 == 3'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        linebuf_we0_local = 1'b1;
    end else begin
        linebuf_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln486_fu_221_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        local_ht_1_out_ap_vld = 1'b1;
    end else begin
        local_ht_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln486_fu_221_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        tower_in_TDATA_blk_n = tower_in_TVALID;
    end else begin
        tower_in_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln486_fu_221_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        tower_in_TREADY = 1'b1;
    end else begin
        tower_in_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln486_fu_227_p2 = (ap_sig_allocacmp_phi_1 + 6'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((icmp_ln486_fu_221_p2 == 1'd0) & (tower_in_TVALID == 1'b0)));
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln486_fu_221_p2 = ((ap_sig_allocacmp_phi_1 == 6'd60) ? 1'b1 : 1'b0);

assign incoming_fu_247_p1 = tower_in_TDATA[11:0];

assign linebuf_1_address0 = zext_ln486_fu_236_p1;

assign linebuf_1_ce0 = linebuf_1_ce0_local;

assign linebuf_1_d0 = incoming_fu_247_p1;

assign linebuf_1_we0 = linebuf_1_we0_local;

assign linebuf_2_address0 = zext_ln486_fu_236_p1;

assign linebuf_2_ce0 = linebuf_2_ce0_local;

assign linebuf_2_d0 = incoming_fu_247_p1;

assign linebuf_2_we0 = linebuf_2_we0_local;

assign linebuf_3_address0 = zext_ln486_fu_236_p1;

assign linebuf_3_ce0 = linebuf_3_ce0_local;

assign linebuf_3_d0 = incoming_fu_247_p1;

assign linebuf_3_we0 = linebuf_3_we0_local;

assign linebuf_4_address0 = zext_ln486_fu_236_p1;

assign linebuf_4_ce0 = linebuf_4_ce0_local;

assign linebuf_4_d0 = incoming_fu_247_p1;

assign linebuf_4_we0 = linebuf_4_we0_local;

assign linebuf_5_address0 = zext_ln486_fu_236_p1;

assign linebuf_5_ce0 = linebuf_5_ce0_local;

assign linebuf_5_d0 = incoming_fu_247_p1;

assign linebuf_5_we0 = linebuf_5_we0_local;

assign linebuf_6_address0 = zext_ln486_fu_236_p1;

assign linebuf_6_ce0 = linebuf_6_ce0_local;

assign linebuf_6_d0 = incoming_fu_247_p1;

assign linebuf_6_we0 = linebuf_6_we0_local;

assign linebuf_address0 = zext_ln486_fu_236_p1;

assign linebuf_ce0 = linebuf_ce0_local;

assign linebuf_d0 = incoming_fu_247_p1;

assign linebuf_we0 = linebuf_we0_local;

assign local_ht_1_out = local_ht_1_fu_78;

assign local_ht_2_fu_262_p2 = (zext_ln490_fu_258_p1 + ap_sig_allocacmp_local_ht_1_load);

assign tmp_16_read_fu_92_p2 = empty_25;

assign zext_ln486_fu_236_p1 = ap_sig_allocacmp_phi_1;

assign zext_ln490_fu_258_p1 = incoming_fu_247_p1;

endmodule //calo_trigger_tower_stream_ref_produce_em_jet_cluster_stream_from_towers_Pipeline_VITIS_LOOP_486_2
