-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity calo_trigger_tower_stream_ref is
generic (
    C_S_AXI_CTRL_ADDR_WIDTH : INTEGER := 7;
    C_S_AXI_CTRL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    tower_in_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    tower_in_TVALID : IN STD_LOGIC;
    tower_in_TREADY : OUT STD_LOGIC;
    em_objects_0 : OUT STD_LOGIC_VECTOR (88 downto 0);
    em_objects_0_ap_vld : OUT STD_LOGIC;
    em_objects_1 : OUT STD_LOGIC_VECTOR (88 downto 0);
    em_objects_1_ap_vld : OUT STD_LOGIC;
    em_objects_2 : OUT STD_LOGIC_VECTOR (88 downto 0);
    em_objects_2_ap_vld : OUT STD_LOGIC;
    em_objects_3 : OUT STD_LOGIC_VECTOR (88 downto 0);
    em_objects_3_ap_vld : OUT STD_LOGIC;
    em_objects_4 : OUT STD_LOGIC_VECTOR (88 downto 0);
    em_objects_4_ap_vld : OUT STD_LOGIC;
    em_objects_5 : OUT STD_LOGIC_VECTOR (88 downto 0);
    em_objects_5_ap_vld : OUT STD_LOGIC;
    em_objects_6 : OUT STD_LOGIC_VECTOR (88 downto 0);
    em_objects_6_ap_vld : OUT STD_LOGIC;
    em_objects_7 : OUT STD_LOGIC_VECTOR (88 downto 0);
    em_objects_7_ap_vld : OUT STD_LOGIC;
    jet_objects_0 : OUT STD_LOGIC_VECTOR (88 downto 0);
    jet_objects_0_ap_vld : OUT STD_LOGIC;
    jet_objects_1 : OUT STD_LOGIC_VECTOR (88 downto 0);
    jet_objects_1_ap_vld : OUT STD_LOGIC;
    jet_objects_2 : OUT STD_LOGIC_VECTOR (88 downto 0);
    jet_objects_2_ap_vld : OUT STD_LOGIC;
    jet_objects_3 : OUT STD_LOGIC_VECTOR (88 downto 0);
    jet_objects_3_ap_vld : OUT STD_LOGIC;
    jet_objects_4 : OUT STD_LOGIC_VECTOR (88 downto 0);
    jet_objects_4_ap_vld : OUT STD_LOGIC;
    jet_objects_5 : OUT STD_LOGIC_VECTOR (88 downto 0);
    jet_objects_5_ap_vld : OUT STD_LOGIC;
    jet_objects_6 : OUT STD_LOGIC_VECTOR (88 downto 0);
    jet_objects_6_ap_vld : OUT STD_LOGIC;
    jet_objects_7 : OUT STD_LOGIC_VECTOR (88 downto 0);
    jet_objects_7_ap_vld : OUT STD_LOGIC;
    s_axi_CTRL_AWVALID : IN STD_LOGIC;
    s_axi_CTRL_AWREADY : OUT STD_LOGIC;
    s_axi_CTRL_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_WVALID : IN STD_LOGIC;
    s_axi_CTRL_WREADY : OUT STD_LOGIC;
    s_axi_CTRL_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH/8-1 downto 0);
    s_axi_CTRL_ARVALID : IN STD_LOGIC;
    s_axi_CTRL_ARREADY : OUT STD_LOGIC;
    s_axi_CTRL_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_RVALID : OUT STD_LOGIC;
    s_axi_CTRL_RREADY : IN STD_LOGIC;
    s_axi_CTRL_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_CTRL_BVALID : OUT STD_LOGIC;
    s_axi_CTRL_BREADY : IN STD_LOGIC;
    s_axi_CTRL_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of calo_trigger_tower_stream_ref is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "calo_trigger_tower_stream_ref_calo_trigger_tower_stream_ref,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu13p-fsga2577-2-e,HLS_INPUT_CLOCK=25.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=12.510161,HLS_SYN_LAT=7217,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=7811,HLS_SYN_LUT=18708,HLS_VERSION=2024_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal em_seed_threshold : STD_LOGIC_VECTOR (11 downto 0);
    signal em_cluster_threshold : STD_LOGIC_VECTOR (19 downto 0);
    signal jet_seed_threshold : STD_LOGIC_VECTOR (11 downto 0);
    signal jet_cluster_threshold : STD_LOGIC_VECTOR (19 downto 0);
    signal jet_cluster_threshold_read_reg_170 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal jet_seed_threshold_read_reg_175 : STD_LOGIC_VECTOR (11 downto 0);
    signal em_cluster_threshold_read_reg_180 : STD_LOGIC_VECTOR (19 downto 0);
    signal em_seed_threshold_read_reg_185 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_cluster_sort_build_tower_stream_fu_118_em_objects_0 : STD_LOGIC_VECTOR (88 downto 0);
    signal grp_cluster_sort_build_tower_stream_fu_118_em_objects_1 : STD_LOGIC_VECTOR (88 downto 0);
    signal grp_cluster_sort_build_tower_stream_fu_118_em_objects_2 : STD_LOGIC_VECTOR (88 downto 0);
    signal grp_cluster_sort_build_tower_stream_fu_118_em_objects_3 : STD_LOGIC_VECTOR (88 downto 0);
    signal grp_cluster_sort_build_tower_stream_fu_118_em_objects_4 : STD_LOGIC_VECTOR (88 downto 0);
    signal grp_cluster_sort_build_tower_stream_fu_118_em_objects_5 : STD_LOGIC_VECTOR (88 downto 0);
    signal grp_cluster_sort_build_tower_stream_fu_118_em_objects_6 : STD_LOGIC_VECTOR (88 downto 0);
    signal grp_cluster_sort_build_tower_stream_fu_118_em_objects_7 : STD_LOGIC_VECTOR (88 downto 0);
    signal grp_cluster_sort_build_tower_stream_fu_118_jet_objects_0 : STD_LOGIC_VECTOR (88 downto 0);
    signal grp_cluster_sort_build_tower_stream_fu_118_jet_objects_1 : STD_LOGIC_VECTOR (88 downto 0);
    signal grp_cluster_sort_build_tower_stream_fu_118_jet_objects_2 : STD_LOGIC_VECTOR (88 downto 0);
    signal grp_cluster_sort_build_tower_stream_fu_118_jet_objects_3 : STD_LOGIC_VECTOR (88 downto 0);
    signal grp_cluster_sort_build_tower_stream_fu_118_jet_objects_4 : STD_LOGIC_VECTOR (88 downto 0);
    signal grp_cluster_sort_build_tower_stream_fu_118_jet_objects_5 : STD_LOGIC_VECTOR (88 downto 0);
    signal grp_cluster_sort_build_tower_stream_fu_118_jet_objects_6 : STD_LOGIC_VECTOR (88 downto 0);
    signal grp_cluster_sort_build_tower_stream_fu_118_jet_objects_7 : STD_LOGIC_VECTOR (88 downto 0);
    signal grp_cluster_sort_build_tower_stream_fu_118_ht : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_cluster_sort_build_tower_stream_fu_118_num_em_clusters : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_cluster_sort_build_tower_stream_fu_118_num_jet_clusters : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_cluster_sort_build_tower_stream_fu_118_tower_in_TREADY : STD_LOGIC;
    signal grp_cluster_sort_build_tower_stream_fu_118_ht_ap_vld : STD_LOGIC;
    signal grp_cluster_sort_build_tower_stream_fu_118_ap_start : STD_LOGIC;
    signal grp_cluster_sort_build_tower_stream_fu_118_ap_done : STD_LOGIC;
    signal grp_cluster_sort_build_tower_stream_fu_118_num_em_clusters_ap_vld : STD_LOGIC;
    signal grp_cluster_sort_build_tower_stream_fu_118_num_jet_clusters_ap_vld : STD_LOGIC;
    signal grp_cluster_sort_build_tower_stream_fu_118_em_objects_0_ap_vld : STD_LOGIC;
    signal grp_cluster_sort_build_tower_stream_fu_118_em_objects_1_ap_vld : STD_LOGIC;
    signal grp_cluster_sort_build_tower_stream_fu_118_em_objects_2_ap_vld : STD_LOGIC;
    signal grp_cluster_sort_build_tower_stream_fu_118_em_objects_3_ap_vld : STD_LOGIC;
    signal grp_cluster_sort_build_tower_stream_fu_118_em_objects_4_ap_vld : STD_LOGIC;
    signal grp_cluster_sort_build_tower_stream_fu_118_em_objects_5_ap_vld : STD_LOGIC;
    signal grp_cluster_sort_build_tower_stream_fu_118_em_objects_6_ap_vld : STD_LOGIC;
    signal grp_cluster_sort_build_tower_stream_fu_118_em_objects_7_ap_vld : STD_LOGIC;
    signal grp_cluster_sort_build_tower_stream_fu_118_jet_objects_0_ap_vld : STD_LOGIC;
    signal grp_cluster_sort_build_tower_stream_fu_118_jet_objects_1_ap_vld : STD_LOGIC;
    signal grp_cluster_sort_build_tower_stream_fu_118_jet_objects_2_ap_vld : STD_LOGIC;
    signal grp_cluster_sort_build_tower_stream_fu_118_jet_objects_3_ap_vld : STD_LOGIC;
    signal grp_cluster_sort_build_tower_stream_fu_118_jet_objects_4_ap_vld : STD_LOGIC;
    signal grp_cluster_sort_build_tower_stream_fu_118_jet_objects_5_ap_vld : STD_LOGIC;
    signal grp_cluster_sort_build_tower_stream_fu_118_jet_objects_6_ap_vld : STD_LOGIC;
    signal grp_cluster_sort_build_tower_stream_fu_118_jet_objects_7_ap_vld : STD_LOGIC;
    signal grp_cluster_sort_build_tower_stream_fu_118_ap_ready : STD_LOGIC;
    signal grp_cluster_sort_build_tower_stream_fu_118_ap_idle : STD_LOGIC;
    signal grp_cluster_sort_build_tower_stream_fu_118_ap_continue : STD_LOGIC;
    signal grp_cluster_sort_build_tower_stream_fu_118_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_sync_reg_grp_cluster_sort_build_tower_stream_fu_118_ap_ready : STD_LOGIC := '0';
    signal ap_sync_reg_grp_cluster_sort_build_tower_stream_fu_118_ap_done : STD_LOGIC := '0';
    signal ap_block_state3_on_subcall_done : BOOLEAN;
    signal ap_sync_grp_cluster_sort_build_tower_stream_fu_118_ap_ready : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal regslice_both_tower_in_U_apdone_blk : STD_LOGIC;
    signal tower_in_TDATA_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal tower_in_TVALID_int_regslice : STD_LOGIC;
    signal tower_in_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_tower_in_U_ack_in : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component calo_trigger_tower_stream_ref_cluster_sort_build_tower_stream IS
    port (
        tower_in_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
        em_seed_threshold : IN STD_LOGIC_VECTOR (11 downto 0);
        em_cluster_threshold : IN STD_LOGIC_VECTOR (19 downto 0);
        jet_seed_threshold : IN STD_LOGIC_VECTOR (11 downto 0);
        jet_cluster_threshold : IN STD_LOGIC_VECTOR (19 downto 0);
        em_objects_0 : OUT STD_LOGIC_VECTOR (88 downto 0);
        em_objects_1 : OUT STD_LOGIC_VECTOR (88 downto 0);
        em_objects_2 : OUT STD_LOGIC_VECTOR (88 downto 0);
        em_objects_3 : OUT STD_LOGIC_VECTOR (88 downto 0);
        em_objects_4 : OUT STD_LOGIC_VECTOR (88 downto 0);
        em_objects_5 : OUT STD_LOGIC_VECTOR (88 downto 0);
        em_objects_6 : OUT STD_LOGIC_VECTOR (88 downto 0);
        em_objects_7 : OUT STD_LOGIC_VECTOR (88 downto 0);
        jet_objects_0 : OUT STD_LOGIC_VECTOR (88 downto 0);
        jet_objects_1 : OUT STD_LOGIC_VECTOR (88 downto 0);
        jet_objects_2 : OUT STD_LOGIC_VECTOR (88 downto 0);
        jet_objects_3 : OUT STD_LOGIC_VECTOR (88 downto 0);
        jet_objects_4 : OUT STD_LOGIC_VECTOR (88 downto 0);
        jet_objects_5 : OUT STD_LOGIC_VECTOR (88 downto 0);
        jet_objects_6 : OUT STD_LOGIC_VECTOR (88 downto 0);
        jet_objects_7 : OUT STD_LOGIC_VECTOR (88 downto 0);
        ht : OUT STD_LOGIC_VECTOR (23 downto 0);
        num_em_clusters : OUT STD_LOGIC_VECTOR (31 downto 0);
        num_jet_clusters : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        tower_in_TVALID : IN STD_LOGIC;
        tower_in_TREADY : OUT STD_LOGIC;
        em_seed_threshold_ap_vld : IN STD_LOGIC;
        em_cluster_threshold_ap_vld : IN STD_LOGIC;
        jet_seed_threshold_ap_vld : IN STD_LOGIC;
        jet_cluster_threshold_ap_vld : IN STD_LOGIC;
        ht_ap_vld : OUT STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        num_em_clusters_ap_vld : OUT STD_LOGIC;
        num_jet_clusters_ap_vld : OUT STD_LOGIC;
        em_objects_0_ap_vld : OUT STD_LOGIC;
        em_objects_1_ap_vld : OUT STD_LOGIC;
        em_objects_2_ap_vld : OUT STD_LOGIC;
        em_objects_3_ap_vld : OUT STD_LOGIC;
        em_objects_4_ap_vld : OUT STD_LOGIC;
        em_objects_5_ap_vld : OUT STD_LOGIC;
        em_objects_6_ap_vld : OUT STD_LOGIC;
        em_objects_7_ap_vld : OUT STD_LOGIC;
        jet_objects_0_ap_vld : OUT STD_LOGIC;
        jet_objects_1_ap_vld : OUT STD_LOGIC;
        jet_objects_2_ap_vld : OUT STD_LOGIC;
        jet_objects_3_ap_vld : OUT STD_LOGIC;
        jet_objects_4_ap_vld : OUT STD_LOGIC;
        jet_objects_5_ap_vld : OUT STD_LOGIC;
        jet_objects_6_ap_vld : OUT STD_LOGIC;
        jet_objects_7_ap_vld : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;


    component calo_trigger_tower_stream_ref_CTRL_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        em_seed_threshold : OUT STD_LOGIC_VECTOR (11 downto 0);
        em_cluster_threshold : OUT STD_LOGIC_VECTOR (19 downto 0);
        jet_seed_threshold : OUT STD_LOGIC_VECTOR (11 downto 0);
        jet_cluster_threshold : OUT STD_LOGIC_VECTOR (19 downto 0);
        ht : IN STD_LOGIC_VECTOR (23 downto 0);
        ht_ap_vld : IN STD_LOGIC;
        num_em_clusters : IN STD_LOGIC_VECTOR (31 downto 0);
        num_em_clusters_ap_vld : IN STD_LOGIC;
        num_jet_clusters : IN STD_LOGIC_VECTOR (31 downto 0);
        num_jet_clusters_ap_vld : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component calo_trigger_tower_stream_ref_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_cluster_sort_build_tower_stream_fu_118 : component calo_trigger_tower_stream_ref_cluster_sort_build_tower_stream
    port map (
        tower_in_TDATA => tower_in_TDATA_int_regslice,
        em_seed_threshold => em_seed_threshold_read_reg_185,
        em_cluster_threshold => em_cluster_threshold_read_reg_180,
        jet_seed_threshold => jet_seed_threshold_read_reg_175,
        jet_cluster_threshold => jet_cluster_threshold_read_reg_170,
        em_objects_0 => grp_cluster_sort_build_tower_stream_fu_118_em_objects_0,
        em_objects_1 => grp_cluster_sort_build_tower_stream_fu_118_em_objects_1,
        em_objects_2 => grp_cluster_sort_build_tower_stream_fu_118_em_objects_2,
        em_objects_3 => grp_cluster_sort_build_tower_stream_fu_118_em_objects_3,
        em_objects_4 => grp_cluster_sort_build_tower_stream_fu_118_em_objects_4,
        em_objects_5 => grp_cluster_sort_build_tower_stream_fu_118_em_objects_5,
        em_objects_6 => grp_cluster_sort_build_tower_stream_fu_118_em_objects_6,
        em_objects_7 => grp_cluster_sort_build_tower_stream_fu_118_em_objects_7,
        jet_objects_0 => grp_cluster_sort_build_tower_stream_fu_118_jet_objects_0,
        jet_objects_1 => grp_cluster_sort_build_tower_stream_fu_118_jet_objects_1,
        jet_objects_2 => grp_cluster_sort_build_tower_stream_fu_118_jet_objects_2,
        jet_objects_3 => grp_cluster_sort_build_tower_stream_fu_118_jet_objects_3,
        jet_objects_4 => grp_cluster_sort_build_tower_stream_fu_118_jet_objects_4,
        jet_objects_5 => grp_cluster_sort_build_tower_stream_fu_118_jet_objects_5,
        jet_objects_6 => grp_cluster_sort_build_tower_stream_fu_118_jet_objects_6,
        jet_objects_7 => grp_cluster_sort_build_tower_stream_fu_118_jet_objects_7,
        ht => grp_cluster_sort_build_tower_stream_fu_118_ht,
        num_em_clusters => grp_cluster_sort_build_tower_stream_fu_118_num_em_clusters,
        num_jet_clusters => grp_cluster_sort_build_tower_stream_fu_118_num_jet_clusters,
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        tower_in_TVALID => tower_in_TVALID_int_regslice,
        tower_in_TREADY => grp_cluster_sort_build_tower_stream_fu_118_tower_in_TREADY,
        em_seed_threshold_ap_vld => ap_const_logic_1,
        em_cluster_threshold_ap_vld => ap_const_logic_1,
        jet_seed_threshold_ap_vld => ap_const_logic_1,
        jet_cluster_threshold_ap_vld => ap_const_logic_1,
        ht_ap_vld => grp_cluster_sort_build_tower_stream_fu_118_ht_ap_vld,
        ap_start => grp_cluster_sort_build_tower_stream_fu_118_ap_start,
        ap_done => grp_cluster_sort_build_tower_stream_fu_118_ap_done,
        num_em_clusters_ap_vld => grp_cluster_sort_build_tower_stream_fu_118_num_em_clusters_ap_vld,
        num_jet_clusters_ap_vld => grp_cluster_sort_build_tower_stream_fu_118_num_jet_clusters_ap_vld,
        em_objects_0_ap_vld => grp_cluster_sort_build_tower_stream_fu_118_em_objects_0_ap_vld,
        em_objects_1_ap_vld => grp_cluster_sort_build_tower_stream_fu_118_em_objects_1_ap_vld,
        em_objects_2_ap_vld => grp_cluster_sort_build_tower_stream_fu_118_em_objects_2_ap_vld,
        em_objects_3_ap_vld => grp_cluster_sort_build_tower_stream_fu_118_em_objects_3_ap_vld,
        em_objects_4_ap_vld => grp_cluster_sort_build_tower_stream_fu_118_em_objects_4_ap_vld,
        em_objects_5_ap_vld => grp_cluster_sort_build_tower_stream_fu_118_em_objects_5_ap_vld,
        em_objects_6_ap_vld => grp_cluster_sort_build_tower_stream_fu_118_em_objects_6_ap_vld,
        em_objects_7_ap_vld => grp_cluster_sort_build_tower_stream_fu_118_em_objects_7_ap_vld,
        jet_objects_0_ap_vld => grp_cluster_sort_build_tower_stream_fu_118_jet_objects_0_ap_vld,
        jet_objects_1_ap_vld => grp_cluster_sort_build_tower_stream_fu_118_jet_objects_1_ap_vld,
        jet_objects_2_ap_vld => grp_cluster_sort_build_tower_stream_fu_118_jet_objects_2_ap_vld,
        jet_objects_3_ap_vld => grp_cluster_sort_build_tower_stream_fu_118_jet_objects_3_ap_vld,
        jet_objects_4_ap_vld => grp_cluster_sort_build_tower_stream_fu_118_jet_objects_4_ap_vld,
        jet_objects_5_ap_vld => grp_cluster_sort_build_tower_stream_fu_118_jet_objects_5_ap_vld,
        jet_objects_6_ap_vld => grp_cluster_sort_build_tower_stream_fu_118_jet_objects_6_ap_vld,
        jet_objects_7_ap_vld => grp_cluster_sort_build_tower_stream_fu_118_jet_objects_7_ap_vld,
        ap_ready => grp_cluster_sort_build_tower_stream_fu_118_ap_ready,
        ap_idle => grp_cluster_sort_build_tower_stream_fu_118_ap_idle,
        ap_continue => grp_cluster_sort_build_tower_stream_fu_118_ap_continue);

    CTRL_s_axi_U : component calo_trigger_tower_stream_ref_CTRL_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CTRL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CTRL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_CTRL_AWVALID,
        AWREADY => s_axi_CTRL_AWREADY,
        AWADDR => s_axi_CTRL_AWADDR,
        WVALID => s_axi_CTRL_WVALID,
        WREADY => s_axi_CTRL_WREADY,
        WDATA => s_axi_CTRL_WDATA,
        WSTRB => s_axi_CTRL_WSTRB,
        ARVALID => s_axi_CTRL_ARVALID,
        ARREADY => s_axi_CTRL_ARREADY,
        ARADDR => s_axi_CTRL_ARADDR,
        RVALID => s_axi_CTRL_RVALID,
        RREADY => s_axi_CTRL_RREADY,
        RDATA => s_axi_CTRL_RDATA,
        RRESP => s_axi_CTRL_RRESP,
        BVALID => s_axi_CTRL_BVALID,
        BREADY => s_axi_CTRL_BREADY,
        BRESP => s_axi_CTRL_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        em_seed_threshold => em_seed_threshold,
        em_cluster_threshold => em_cluster_threshold,
        jet_seed_threshold => jet_seed_threshold,
        jet_cluster_threshold => jet_cluster_threshold,
        ht => grp_cluster_sort_build_tower_stream_fu_118_ht,
        ht_ap_vld => grp_cluster_sort_build_tower_stream_fu_118_ht_ap_vld,
        num_em_clusters => grp_cluster_sort_build_tower_stream_fu_118_num_em_clusters,
        num_em_clusters_ap_vld => grp_cluster_sort_build_tower_stream_fu_118_num_em_clusters_ap_vld,
        num_jet_clusters => grp_cluster_sort_build_tower_stream_fu_118_num_jet_clusters,
        num_jet_clusters_ap_vld => grp_cluster_sort_build_tower_stream_fu_118_num_jet_clusters_ap_vld,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    regslice_both_tower_in_U : component calo_trigger_tower_stream_ref_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tower_in_TDATA,
        vld_in => tower_in_TVALID,
        ack_in => regslice_both_tower_in_U_ack_in,
        data_out => tower_in_TDATA_int_regslice,
        vld_out => tower_in_TVALID_int_regslice,
        ack_out => tower_in_TREADY_int_regslice,
        apdone_blk => regslice_both_tower_in_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_sync_reg_grp_cluster_sort_build_tower_stream_fu_118_ap_done_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_grp_cluster_sort_build_tower_stream_fu_118_ap_done <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_boolean_0 = ap_block_state3_on_subcall_done))) then 
                    ap_sync_reg_grp_cluster_sort_build_tower_stream_fu_118_ap_done <= ap_const_logic_0;
                elsif ((grp_cluster_sort_build_tower_stream_fu_118_ap_done = ap_const_logic_1)) then 
                    ap_sync_reg_grp_cluster_sort_build_tower_stream_fu_118_ap_done <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_grp_cluster_sort_build_tower_stream_fu_118_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_grp_cluster_sort_build_tower_stream_fu_118_ap_ready <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_boolean_0 = ap_block_state3_on_subcall_done))) then 
                    ap_sync_reg_grp_cluster_sort_build_tower_stream_fu_118_ap_ready <= ap_const_logic_0;
                elsif ((grp_cluster_sort_build_tower_stream_fu_118_ap_ready = ap_const_logic_1)) then 
                    ap_sync_reg_grp_cluster_sort_build_tower_stream_fu_118_ap_ready <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_cluster_sort_build_tower_stream_fu_118_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_cluster_sort_build_tower_stream_fu_118_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_sync_grp_cluster_sort_build_tower_stream_fu_118_ap_ready = ap_const_logic_0)))) then 
                    grp_cluster_sort_build_tower_stream_fu_118_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_cluster_sort_build_tower_stream_fu_118_ap_ready = ap_const_logic_1)) then 
                    grp_cluster_sort_build_tower_stream_fu_118_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                em_cluster_threshold_read_reg_180 <= em_cluster_threshold;
                em_seed_threshold_read_reg_185 <= em_seed_threshold;
                jet_cluster_threshold_read_reg_170 <= jet_cluster_threshold;
                jet_seed_threshold_read_reg_175 <= jet_seed_threshold;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state3, ap_block_state3_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_boolean_0 = ap_block_state3_on_subcall_done))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(ap_block_state3_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state3_on_subcall_done)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state3_on_subcall_done_assign_proc : process(ap_sync_reg_grp_cluster_sort_build_tower_stream_fu_118_ap_ready, ap_sync_reg_grp_cluster_sort_build_tower_stream_fu_118_ap_done)
    begin
                ap_block_state3_on_subcall_done <= ((ap_sync_reg_grp_cluster_sort_build_tower_stream_fu_118_ap_ready and ap_sync_reg_grp_cluster_sort_build_tower_stream_fu_118_ap_done) = ap_const_logic_0);
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state3, ap_block_state3_on_subcall_done)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_boolean_0 = ap_block_state3_on_subcall_done))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state3, ap_block_state3_on_subcall_done)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_boolean_0 = ap_block_state3_on_subcall_done))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    ap_sync_grp_cluster_sort_build_tower_stream_fu_118_ap_ready <= (grp_cluster_sort_build_tower_stream_fu_118_ap_ready or ap_sync_reg_grp_cluster_sort_build_tower_stream_fu_118_ap_ready);
    em_objects_0 <= grp_cluster_sort_build_tower_stream_fu_118_em_objects_0;
    em_objects_0_ap_vld <= grp_cluster_sort_build_tower_stream_fu_118_em_objects_0_ap_vld;
    em_objects_1 <= grp_cluster_sort_build_tower_stream_fu_118_em_objects_1;
    em_objects_1_ap_vld <= grp_cluster_sort_build_tower_stream_fu_118_em_objects_1_ap_vld;
    em_objects_2 <= grp_cluster_sort_build_tower_stream_fu_118_em_objects_2;
    em_objects_2_ap_vld <= grp_cluster_sort_build_tower_stream_fu_118_em_objects_2_ap_vld;
    em_objects_3 <= grp_cluster_sort_build_tower_stream_fu_118_em_objects_3;
    em_objects_3_ap_vld <= grp_cluster_sort_build_tower_stream_fu_118_em_objects_3_ap_vld;
    em_objects_4 <= grp_cluster_sort_build_tower_stream_fu_118_em_objects_4;
    em_objects_4_ap_vld <= grp_cluster_sort_build_tower_stream_fu_118_em_objects_4_ap_vld;
    em_objects_5 <= grp_cluster_sort_build_tower_stream_fu_118_em_objects_5;
    em_objects_5_ap_vld <= grp_cluster_sort_build_tower_stream_fu_118_em_objects_5_ap_vld;
    em_objects_6 <= grp_cluster_sort_build_tower_stream_fu_118_em_objects_6;
    em_objects_6_ap_vld <= grp_cluster_sort_build_tower_stream_fu_118_em_objects_6_ap_vld;
    em_objects_7 <= grp_cluster_sort_build_tower_stream_fu_118_em_objects_7;
    em_objects_7_ap_vld <= grp_cluster_sort_build_tower_stream_fu_118_em_objects_7_ap_vld;

    grp_cluster_sort_build_tower_stream_fu_118_ap_continue_assign_proc : process(ap_CS_fsm_state3, ap_block_state3_on_subcall_done)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_boolean_0 = ap_block_state3_on_subcall_done))) then 
            grp_cluster_sort_build_tower_stream_fu_118_ap_continue <= ap_const_logic_1;
        else 
            grp_cluster_sort_build_tower_stream_fu_118_ap_continue <= ap_const_logic_0;
        end if; 
    end process;

    grp_cluster_sort_build_tower_stream_fu_118_ap_start <= grp_cluster_sort_build_tower_stream_fu_118_ap_start_reg;
    jet_objects_0 <= grp_cluster_sort_build_tower_stream_fu_118_jet_objects_0;
    jet_objects_0_ap_vld <= grp_cluster_sort_build_tower_stream_fu_118_jet_objects_0_ap_vld;
    jet_objects_1 <= grp_cluster_sort_build_tower_stream_fu_118_jet_objects_1;
    jet_objects_1_ap_vld <= grp_cluster_sort_build_tower_stream_fu_118_jet_objects_1_ap_vld;
    jet_objects_2 <= grp_cluster_sort_build_tower_stream_fu_118_jet_objects_2;
    jet_objects_2_ap_vld <= grp_cluster_sort_build_tower_stream_fu_118_jet_objects_2_ap_vld;
    jet_objects_3 <= grp_cluster_sort_build_tower_stream_fu_118_jet_objects_3;
    jet_objects_3_ap_vld <= grp_cluster_sort_build_tower_stream_fu_118_jet_objects_3_ap_vld;
    jet_objects_4 <= grp_cluster_sort_build_tower_stream_fu_118_jet_objects_4;
    jet_objects_4_ap_vld <= grp_cluster_sort_build_tower_stream_fu_118_jet_objects_4_ap_vld;
    jet_objects_5 <= grp_cluster_sort_build_tower_stream_fu_118_jet_objects_5;
    jet_objects_5_ap_vld <= grp_cluster_sort_build_tower_stream_fu_118_jet_objects_5_ap_vld;
    jet_objects_6 <= grp_cluster_sort_build_tower_stream_fu_118_jet_objects_6;
    jet_objects_6_ap_vld <= grp_cluster_sort_build_tower_stream_fu_118_jet_objects_6_ap_vld;
    jet_objects_7 <= grp_cluster_sort_build_tower_stream_fu_118_jet_objects_7;
    jet_objects_7_ap_vld <= grp_cluster_sort_build_tower_stream_fu_118_jet_objects_7_ap_vld;
    tower_in_TREADY <= regslice_both_tower_in_U_ack_in;

    tower_in_TREADY_int_regslice_assign_proc : process(grp_cluster_sort_build_tower_stream_fu_118_tower_in_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            tower_in_TREADY_int_regslice <= grp_cluster_sort_build_tower_stream_fu_118_tower_in_TREADY;
        else 
            tower_in_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

end behav;
