-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity calo_trigger_em_jet_stream_ref is
generic (
    C_S_AXI_CTRL_ADDR_WIDTH : INTEGER := 7;
    C_S_AXI_CTRL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    towers_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    towers_EN_A : OUT STD_LOGIC;
    towers_WEN_A : OUT STD_LOGIC_VECTOR (1 downto 0);
    towers_Din_A : OUT STD_LOGIC_VECTOR (15 downto 0);
    towers_Dout_A : IN STD_LOGIC_VECTOR (15 downto 0);
    towers_Clk_A : OUT STD_LOGIC;
    towers_Rst_A : OUT STD_LOGIC;
    towers_Addr_B : OUT STD_LOGIC_VECTOR (31 downto 0);
    towers_EN_B : OUT STD_LOGIC;
    towers_WEN_B : OUT STD_LOGIC_VECTOR (1 downto 0);
    towers_Din_B : OUT STD_LOGIC_VECTOR (15 downto 0);
    towers_Dout_B : IN STD_LOGIC_VECTOR (15 downto 0);
    towers_Clk_B : OUT STD_LOGIC;
    towers_Rst_B : OUT STD_LOGIC;
    em_objects_0 : OUT STD_LOGIC_VECTOR (88 downto 0);
    em_objects_0_ap_vld : OUT STD_LOGIC;
    em_objects_1 : OUT STD_LOGIC_VECTOR (88 downto 0);
    em_objects_1_ap_vld : OUT STD_LOGIC;
    em_objects_2 : OUT STD_LOGIC_VECTOR (88 downto 0);
    em_objects_2_ap_vld : OUT STD_LOGIC;
    em_objects_3 : OUT STD_LOGIC_VECTOR (88 downto 0);
    em_objects_3_ap_vld : OUT STD_LOGIC;
    em_objects_4 : OUT STD_LOGIC_VECTOR (88 downto 0);
    em_objects_4_ap_vld : OUT STD_LOGIC;
    em_objects_5 : OUT STD_LOGIC_VECTOR (88 downto 0);
    em_objects_5_ap_vld : OUT STD_LOGIC;
    em_objects_6 : OUT STD_LOGIC_VECTOR (88 downto 0);
    em_objects_6_ap_vld : OUT STD_LOGIC;
    em_objects_7 : OUT STD_LOGIC_VECTOR (88 downto 0);
    em_objects_7_ap_vld : OUT STD_LOGIC;
    jet_objects_0 : OUT STD_LOGIC_VECTOR (88 downto 0);
    jet_objects_0_ap_vld : OUT STD_LOGIC;
    jet_objects_1 : OUT STD_LOGIC_VECTOR (88 downto 0);
    jet_objects_1_ap_vld : OUT STD_LOGIC;
    jet_objects_2 : OUT STD_LOGIC_VECTOR (88 downto 0);
    jet_objects_2_ap_vld : OUT STD_LOGIC;
    jet_objects_3 : OUT STD_LOGIC_VECTOR (88 downto 0);
    jet_objects_3_ap_vld : OUT STD_LOGIC;
    jet_objects_4 : OUT STD_LOGIC_VECTOR (88 downto 0);
    jet_objects_4_ap_vld : OUT STD_LOGIC;
    jet_objects_5 : OUT STD_LOGIC_VECTOR (88 downto 0);
    jet_objects_5_ap_vld : OUT STD_LOGIC;
    jet_objects_6 : OUT STD_LOGIC_VECTOR (88 downto 0);
    jet_objects_6_ap_vld : OUT STD_LOGIC;
    jet_objects_7 : OUT STD_LOGIC_VECTOR (88 downto 0);
    jet_objects_7_ap_vld : OUT STD_LOGIC;
    s_axi_CTRL_AWVALID : IN STD_LOGIC;
    s_axi_CTRL_AWREADY : OUT STD_LOGIC;
    s_axi_CTRL_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_WVALID : IN STD_LOGIC;
    s_axi_CTRL_WREADY : OUT STD_LOGIC;
    s_axi_CTRL_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH/8-1 downto 0);
    s_axi_CTRL_ARVALID : IN STD_LOGIC;
    s_axi_CTRL_ARREADY : OUT STD_LOGIC;
    s_axi_CTRL_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_RVALID : OUT STD_LOGIC;
    s_axi_CTRL_RREADY : IN STD_LOGIC;
    s_axi_CTRL_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_CTRL_BVALID : OUT STD_LOGIC;
    s_axi_CTRL_BREADY : IN STD_LOGIC;
    s_axi_CTRL_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of calo_trigger_em_jet_stream_ref is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "calo_trigger_em_jet_stream_ref_calo_trigger_em_jet_stream_ref,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu13p-fsga2577-2-e,HLS_INPUT_CLOCK=25.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.274375,HLS_SYN_LAT=72365,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=8738,HLS_SYN_LUT=18912,HLS_VERSION=2024_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv6_3C : STD_LOGIC_VECTOR (5 downto 0) := "111100";
    constant ap_const_lv11_707 : STD_LOGIC_VECTOR (10 downto 0) := "11100000111";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal em_seed_threshold : STD_LOGIC_VECTOR (11 downto 0);
    signal em_cluster_threshold : STD_LOGIC_VECTOR (19 downto 0);
    signal jet_seed_threshold : STD_LOGIC_VECTOR (11 downto 0);
    signal jet_cluster_threshold : STD_LOGIC_VECTOR (19 downto 0);
    signal ht_ap_vld : STD_LOGIC;
    signal icmp_ln1616_reg_194 : STD_LOGIC_VECTOR (0 downto 0);
    signal jet_cluster_threshold_read_reg_432 : STD_LOGIC_VECTOR (19 downto 0);
    signal jet_seed_threshold_read_reg_437 : STD_LOGIC_VECTOR (11 downto 0);
    signal em_cluster_threshold_read_reg_442 : STD_LOGIC_VECTOR (19 downto 0);
    signal em_seed_threshold_read_reg_447 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln161_fu_355_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln161_reg_457 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal icmp_ln160_fu_361_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln160_reg_462 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln161_fu_395_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal zext_ln161_reg_466 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_flush_enable : STD_LOGIC;
    signal grp_cluster_sort_build_em_jet_stream_fu_205_towers_Addr_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_cluster_sort_build_em_jet_stream_fu_205_towers_EN_A : STD_LOGIC;
    signal grp_cluster_sort_build_em_jet_stream_fu_205_towers_Din_A : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_cluster_sort_build_em_jet_stream_fu_205_towers_WEN_A : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_cluster_sort_build_em_jet_stream_fu_205_towers_Addr_B : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_cluster_sort_build_em_jet_stream_fu_205_towers_EN_B : STD_LOGIC;
    signal grp_cluster_sort_build_em_jet_stream_fu_205_towers_Din_B : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_cluster_sort_build_em_jet_stream_fu_205_towers_WEN_B : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_0 : STD_LOGIC_VECTOR (88 downto 0);
    signal grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_1 : STD_LOGIC_VECTOR (88 downto 0);
    signal grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_2 : STD_LOGIC_VECTOR (88 downto 0);
    signal grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_3 : STD_LOGIC_VECTOR (88 downto 0);
    signal grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_4 : STD_LOGIC_VECTOR (88 downto 0);
    signal grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_5 : STD_LOGIC_VECTOR (88 downto 0);
    signal grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_6 : STD_LOGIC_VECTOR (88 downto 0);
    signal grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_7 : STD_LOGIC_VECTOR (88 downto 0);
    signal grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_0 : STD_LOGIC_VECTOR (88 downto 0);
    signal grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_1 : STD_LOGIC_VECTOR (88 downto 0);
    signal grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_2 : STD_LOGIC_VECTOR (88 downto 0);
    signal grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_3 : STD_LOGIC_VECTOR (88 downto 0);
    signal grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_4 : STD_LOGIC_VECTOR (88 downto 0);
    signal grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_5 : STD_LOGIC_VECTOR (88 downto 0);
    signal grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_6 : STD_LOGIC_VECTOR (88 downto 0);
    signal grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_7 : STD_LOGIC_VECTOR (88 downto 0);
    signal grp_cluster_sort_build_em_jet_stream_fu_205_num_em_clusters : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_cluster_sort_build_em_jet_stream_fu_205_num_jet_clusters : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_cluster_sort_build_em_jet_stream_fu_205_ap_start : STD_LOGIC;
    signal grp_cluster_sort_build_em_jet_stream_fu_205_num_em_clusters_ap_vld : STD_LOGIC;
    signal grp_cluster_sort_build_em_jet_stream_fu_205_ap_done : STD_LOGIC;
    signal grp_cluster_sort_build_em_jet_stream_fu_205_num_jet_clusters_ap_vld : STD_LOGIC;
    signal grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_0_ap_vld : STD_LOGIC;
    signal grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_1_ap_vld : STD_LOGIC;
    signal grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_2_ap_vld : STD_LOGIC;
    signal grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_3_ap_vld : STD_LOGIC;
    signal grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_4_ap_vld : STD_LOGIC;
    signal grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_5_ap_vld : STD_LOGIC;
    signal grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_6_ap_vld : STD_LOGIC;
    signal grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_7_ap_vld : STD_LOGIC;
    signal grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_0_ap_vld : STD_LOGIC;
    signal grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_1_ap_vld : STD_LOGIC;
    signal grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_2_ap_vld : STD_LOGIC;
    signal grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_3_ap_vld : STD_LOGIC;
    signal grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_4_ap_vld : STD_LOGIC;
    signal grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_5_ap_vld : STD_LOGIC;
    signal grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_6_ap_vld : STD_LOGIC;
    signal grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_7_ap_vld : STD_LOGIC;
    signal grp_cluster_sort_build_em_jet_stream_fu_205_ap_ready : STD_LOGIC;
    signal grp_cluster_sort_build_em_jet_stream_fu_205_ap_idle : STD_LOGIC;
    signal grp_cluster_sort_build_em_jet_stream_fu_205_ap_continue : STD_LOGIC;
    signal ap_phi_mux_icmp_ln1616_phi_fu_198_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal grp_cluster_sort_build_em_jet_stream_fu_205_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_sync_reg_grp_cluster_sort_build_em_jet_stream_fu_205_ap_ready : STD_LOGIC := '0';
    signal ap_sync_reg_grp_cluster_sort_build_em_jet_stream_fu_205_ap_done : STD_LOGIC := '0';
    signal ap_block_state5_on_subcall_done : BOOLEAN;
    signal ap_sync_grp_cluster_sort_build_em_jet_stream_fu_205_ap_ready : STD_LOGIC;
    signal zext_ln163_2_fu_338_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal indvar_flatten1_fu_134 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal add_ln160_1_fu_349_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal eta2_fu_138 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal eta_fu_294_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal phi3_fu_142 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal phi_fu_343_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal conv4_i4_i4_fu_146 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    signal ht_2_fu_389_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal towers_EN_A_local : STD_LOGIC;
    signal towers_Addr_A_local : STD_LOGIC_VECTOR (31 downto 0);
    signal towers_Addr_A_orig : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln160_fu_280_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_fu_310_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_shl_fu_302_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln163_fu_318_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln160_fu_286_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal sub_ln163_fu_322_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln163_1_fu_328_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln163_5_fu_332_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln163_3_fu_385_p0 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln163_3_fu_385_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component calo_trigger_em_jet_stream_ref_cluster_sort_build_em_jet_stream IS
    port (
        towers_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        towers_EN_A : OUT STD_LOGIC;
        towers_Din_A : OUT STD_LOGIC_VECTOR (15 downto 0);
        towers_Dout_A : IN STD_LOGIC_VECTOR (15 downto 0);
        towers_WEN_A : OUT STD_LOGIC_VECTOR (1 downto 0);
        towers_Addr_B : OUT STD_LOGIC_VECTOR (31 downto 0);
        towers_EN_B : OUT STD_LOGIC;
        towers_Din_B : OUT STD_LOGIC_VECTOR (15 downto 0);
        towers_Dout_B : IN STD_LOGIC_VECTOR (15 downto 0);
        towers_WEN_B : OUT STD_LOGIC_VECTOR (1 downto 0);
        em_seed_threshold : IN STD_LOGIC_VECTOR (11 downto 0);
        em_cluster_threshold : IN STD_LOGIC_VECTOR (19 downto 0);
        jet_seed_threshold : IN STD_LOGIC_VECTOR (11 downto 0);
        jet_cluster_threshold : IN STD_LOGIC_VECTOR (19 downto 0);
        em_objects_0 : OUT STD_LOGIC_VECTOR (88 downto 0);
        em_objects_1 : OUT STD_LOGIC_VECTOR (88 downto 0);
        em_objects_2 : OUT STD_LOGIC_VECTOR (88 downto 0);
        em_objects_3 : OUT STD_LOGIC_VECTOR (88 downto 0);
        em_objects_4 : OUT STD_LOGIC_VECTOR (88 downto 0);
        em_objects_5 : OUT STD_LOGIC_VECTOR (88 downto 0);
        em_objects_6 : OUT STD_LOGIC_VECTOR (88 downto 0);
        em_objects_7 : OUT STD_LOGIC_VECTOR (88 downto 0);
        jet_objects_0 : OUT STD_LOGIC_VECTOR (88 downto 0);
        jet_objects_1 : OUT STD_LOGIC_VECTOR (88 downto 0);
        jet_objects_2 : OUT STD_LOGIC_VECTOR (88 downto 0);
        jet_objects_3 : OUT STD_LOGIC_VECTOR (88 downto 0);
        jet_objects_4 : OUT STD_LOGIC_VECTOR (88 downto 0);
        jet_objects_5 : OUT STD_LOGIC_VECTOR (88 downto 0);
        jet_objects_6 : OUT STD_LOGIC_VECTOR (88 downto 0);
        jet_objects_7 : OUT STD_LOGIC_VECTOR (88 downto 0);
        num_em_clusters : OUT STD_LOGIC_VECTOR (31 downto 0);
        num_jet_clusters : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        em_seed_threshold_ap_vld : IN STD_LOGIC;
        em_cluster_threshold_ap_vld : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        jet_seed_threshold_ap_vld : IN STD_LOGIC;
        jet_cluster_threshold_ap_vld : IN STD_LOGIC;
        num_em_clusters_ap_vld : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        num_jet_clusters_ap_vld : OUT STD_LOGIC;
        em_objects_0_ap_vld : OUT STD_LOGIC;
        em_objects_1_ap_vld : OUT STD_LOGIC;
        em_objects_2_ap_vld : OUT STD_LOGIC;
        em_objects_3_ap_vld : OUT STD_LOGIC;
        em_objects_4_ap_vld : OUT STD_LOGIC;
        em_objects_5_ap_vld : OUT STD_LOGIC;
        em_objects_6_ap_vld : OUT STD_LOGIC;
        em_objects_7_ap_vld : OUT STD_LOGIC;
        jet_objects_0_ap_vld : OUT STD_LOGIC;
        jet_objects_1_ap_vld : OUT STD_LOGIC;
        jet_objects_2_ap_vld : OUT STD_LOGIC;
        jet_objects_3_ap_vld : OUT STD_LOGIC;
        jet_objects_4_ap_vld : OUT STD_LOGIC;
        jet_objects_5_ap_vld : OUT STD_LOGIC;
        jet_objects_6_ap_vld : OUT STD_LOGIC;
        jet_objects_7_ap_vld : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;


    component calo_trigger_em_jet_stream_ref_CTRL_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        em_seed_threshold : OUT STD_LOGIC_VECTOR (11 downto 0);
        em_cluster_threshold : OUT STD_LOGIC_VECTOR (19 downto 0);
        jet_seed_threshold : OUT STD_LOGIC_VECTOR (11 downto 0);
        jet_cluster_threshold : OUT STD_LOGIC_VECTOR (19 downto 0);
        ht : IN STD_LOGIC_VECTOR (23 downto 0);
        ht_ap_vld : IN STD_LOGIC;
        num_em_clusters : IN STD_LOGIC_VECTOR (31 downto 0);
        num_em_clusters_ap_vld : IN STD_LOGIC;
        num_jet_clusters : IN STD_LOGIC_VECTOR (31 downto 0);
        num_jet_clusters_ap_vld : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;



begin
    grp_cluster_sort_build_em_jet_stream_fu_205 : component calo_trigger_em_jet_stream_ref_cluster_sort_build_em_jet_stream
    port map (
        towers_Addr_A => grp_cluster_sort_build_em_jet_stream_fu_205_towers_Addr_A,
        towers_EN_A => grp_cluster_sort_build_em_jet_stream_fu_205_towers_EN_A,
        towers_Din_A => grp_cluster_sort_build_em_jet_stream_fu_205_towers_Din_A,
        towers_Dout_A => towers_Dout_A,
        towers_WEN_A => grp_cluster_sort_build_em_jet_stream_fu_205_towers_WEN_A,
        towers_Addr_B => grp_cluster_sort_build_em_jet_stream_fu_205_towers_Addr_B,
        towers_EN_B => grp_cluster_sort_build_em_jet_stream_fu_205_towers_EN_B,
        towers_Din_B => grp_cluster_sort_build_em_jet_stream_fu_205_towers_Din_B,
        towers_Dout_B => towers_Dout_B,
        towers_WEN_B => grp_cluster_sort_build_em_jet_stream_fu_205_towers_WEN_B,
        em_seed_threshold => em_seed_threshold_read_reg_447,
        em_cluster_threshold => em_cluster_threshold_read_reg_442,
        jet_seed_threshold => jet_seed_threshold_read_reg_437,
        jet_cluster_threshold => jet_cluster_threshold_read_reg_432,
        em_objects_0 => grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_0,
        em_objects_1 => grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_1,
        em_objects_2 => grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_2,
        em_objects_3 => grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_3,
        em_objects_4 => grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_4,
        em_objects_5 => grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_5,
        em_objects_6 => grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_6,
        em_objects_7 => grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_7,
        jet_objects_0 => grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_0,
        jet_objects_1 => grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_1,
        jet_objects_2 => grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_2,
        jet_objects_3 => grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_3,
        jet_objects_4 => grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_4,
        jet_objects_5 => grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_5,
        jet_objects_6 => grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_6,
        jet_objects_7 => grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_7,
        num_em_clusters => grp_cluster_sort_build_em_jet_stream_fu_205_num_em_clusters,
        num_jet_clusters => grp_cluster_sort_build_em_jet_stream_fu_205_num_jet_clusters,
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        em_seed_threshold_ap_vld => ap_const_logic_1,
        em_cluster_threshold_ap_vld => ap_const_logic_1,
        ap_start => grp_cluster_sort_build_em_jet_stream_fu_205_ap_start,
        jet_seed_threshold_ap_vld => ap_const_logic_1,
        jet_cluster_threshold_ap_vld => ap_const_logic_1,
        num_em_clusters_ap_vld => grp_cluster_sort_build_em_jet_stream_fu_205_num_em_clusters_ap_vld,
        ap_done => grp_cluster_sort_build_em_jet_stream_fu_205_ap_done,
        num_jet_clusters_ap_vld => grp_cluster_sort_build_em_jet_stream_fu_205_num_jet_clusters_ap_vld,
        em_objects_0_ap_vld => grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_0_ap_vld,
        em_objects_1_ap_vld => grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_1_ap_vld,
        em_objects_2_ap_vld => grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_2_ap_vld,
        em_objects_3_ap_vld => grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_3_ap_vld,
        em_objects_4_ap_vld => grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_4_ap_vld,
        em_objects_5_ap_vld => grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_5_ap_vld,
        em_objects_6_ap_vld => grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_6_ap_vld,
        em_objects_7_ap_vld => grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_7_ap_vld,
        jet_objects_0_ap_vld => grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_0_ap_vld,
        jet_objects_1_ap_vld => grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_1_ap_vld,
        jet_objects_2_ap_vld => grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_2_ap_vld,
        jet_objects_3_ap_vld => grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_3_ap_vld,
        jet_objects_4_ap_vld => grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_4_ap_vld,
        jet_objects_5_ap_vld => grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_5_ap_vld,
        jet_objects_6_ap_vld => grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_6_ap_vld,
        jet_objects_7_ap_vld => grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_7_ap_vld,
        ap_ready => grp_cluster_sort_build_em_jet_stream_fu_205_ap_ready,
        ap_idle => grp_cluster_sort_build_em_jet_stream_fu_205_ap_idle,
        ap_continue => grp_cluster_sort_build_em_jet_stream_fu_205_ap_continue);

    CTRL_s_axi_U : component calo_trigger_em_jet_stream_ref_CTRL_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CTRL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CTRL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_CTRL_AWVALID,
        AWREADY => s_axi_CTRL_AWREADY,
        AWADDR => s_axi_CTRL_AWADDR,
        WVALID => s_axi_CTRL_WVALID,
        WREADY => s_axi_CTRL_WREADY,
        WDATA => s_axi_CTRL_WDATA,
        WSTRB => s_axi_CTRL_WSTRB,
        ARVALID => s_axi_CTRL_ARVALID,
        ARREADY => s_axi_CTRL_ARREADY,
        ARADDR => s_axi_CTRL_ARADDR,
        RVALID => s_axi_CTRL_RVALID,
        RREADY => s_axi_CTRL_RREADY,
        RDATA => s_axi_CTRL_RDATA,
        RRESP => s_axi_CTRL_RRESP,
        BVALID => s_axi_CTRL_BVALID,
        BREADY => s_axi_CTRL_BREADY,
        BRESP => s_axi_CTRL_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        em_seed_threshold => em_seed_threshold,
        em_cluster_threshold => em_cluster_threshold,
        jet_seed_threshold => jet_seed_threshold,
        jet_cluster_threshold => jet_cluster_threshold,
        ht => zext_ln161_reg_466,
        ht_ap_vld => ht_ap_vld,
        num_em_clusters => grp_cluster_sort_build_em_jet_stream_fu_205_num_em_clusters,
        num_em_clusters_ap_vld => grp_cluster_sort_build_em_jet_stream_fu_205_num_em_clusters_ap_vld,
        num_jet_clusters => grp_cluster_sort_build_em_jet_stream_fu_205_num_jet_clusters,
        num_jet_clusters_ap_vld => grp_cluster_sort_build_em_jet_stream_fu_205_num_jet_clusters_ap_vld,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_pp0_flush_enable)) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_grp_cluster_sort_build_em_jet_stream_fu_205_ap_done_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_grp_cluster_sort_build_em_jet_stream_fu_205_ap_done <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_const_boolean_0 = ap_block_state5_on_subcall_done))) then 
                    ap_sync_reg_grp_cluster_sort_build_em_jet_stream_fu_205_ap_done <= ap_const_logic_0;
                elsif ((grp_cluster_sort_build_em_jet_stream_fu_205_ap_done = ap_const_logic_1)) then 
                    ap_sync_reg_grp_cluster_sort_build_em_jet_stream_fu_205_ap_done <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_grp_cluster_sort_build_em_jet_stream_fu_205_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_grp_cluster_sort_build_em_jet_stream_fu_205_ap_ready <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_const_boolean_0 = ap_block_state5_on_subcall_done))) then 
                    ap_sync_reg_grp_cluster_sort_build_em_jet_stream_fu_205_ap_ready <= ap_const_logic_0;
                elsif ((grp_cluster_sort_build_em_jet_stream_fu_205_ap_ready = ap_const_logic_1)) then 
                    ap_sync_reg_grp_cluster_sort_build_em_jet_stream_fu_205_ap_ready <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_cluster_sort_build_em_jet_stream_fu_205_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_cluster_sort_build_em_jet_stream_fu_205_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state4) or ((ap_sync_grp_cluster_sort_build_em_jet_stream_fu_205_ap_ready = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state5)))) then 
                    grp_cluster_sort_build_em_jet_stream_fu_205_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_cluster_sort_build_em_jet_stream_fu_205_ap_ready = ap_const_logic_1)) then 
                    grp_cluster_sort_build_em_jet_stream_fu_205_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    conv4_i4_i4_fu_146_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                conv4_i4_i4_fu_146 <= ap_const_lv23_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                conv4_i4_i4_fu_146 <= ht_2_fu_389_p2;
            end if; 
        end if;
    end process;

    eta2_fu_138_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                eta2_fu_138 <= ap_const_lv5_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                eta2_fu_138 <= eta_fu_294_p3;
            end if; 
        end if;
    end process;

    icmp_ln1616_reg_194_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln160_reg_462 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                icmp_ln1616_reg_194 <= icmp_ln161_reg_457;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                icmp_ln1616_reg_194 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    indvar_flatten1_fu_134_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                indvar_flatten1_fu_134 <= ap_const_lv11_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                indvar_flatten1_fu_134 <= add_ln160_1_fu_349_p2;
            end if; 
        end if;
    end process;

    phi3_fu_142_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                phi3_fu_142 <= ap_const_lv6_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                phi3_fu_142 <= phi_fu_343_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                em_cluster_threshold_read_reg_442 <= em_cluster_threshold;
                em_seed_threshold_read_reg_447 <= em_seed_threshold;
                jet_cluster_threshold_read_reg_432 <= jet_cluster_threshold;
                jet_seed_threshold_read_reg_437 <= jet_seed_threshold;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln160_reg_462 <= icmp_ln160_fu_361_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln161_reg_457 <= icmp_ln161_fu_355_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                    zext_ln161_reg_466(22 downto 0) <= zext_ln161_fu_395_p1(22 downto 0);
            end if;
        end if;
    end process;
    zext_ln161_reg_466(23) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, ap_CS_fsm_state5, ap_block_state5_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if (not(((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_const_boolean_0 = ap_block_state5_on_subcall_done))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    add_ln160_1_fu_349_p2 <= std_logic_vector(unsigned(indvar_flatten1_fu_134) + unsigned(ap_const_lv11_1));
    add_ln160_fu_280_p2 <= std_logic_vector(unsigned(eta2_fu_138) + unsigned(ap_const_lv5_1));
    add_ln163_5_fu_332_p2 <= std_logic_vector(unsigned(sub_ln163_fu_322_p2) + unsigned(zext_ln163_1_fu_328_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state4 <= ap_CS_fsm(2);
    ap_CS_fsm_state5 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(ap_block_state5_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state5_on_subcall_done)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;

        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state5_on_subcall_done_assign_proc : process(ap_sync_reg_grp_cluster_sort_build_em_jet_stream_fu_205_ap_ready, ap_sync_reg_grp_cluster_sort_build_em_jet_stream_fu_205_ap_done)
    begin
                ap_block_state5_on_subcall_done <= ((ap_sync_reg_grp_cluster_sort_build_em_jet_stream_fu_205_ap_ready and ap_sync_reg_grp_cluster_sort_build_em_jet_stream_fu_205_ap_done) = ap_const_logic_0);
    end process;


    ap_condition_pp0_flush_enable_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln160_fu_361_p2, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln160_fu_361_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_pp0_flush_enable <= ap_const_logic_1;
        else 
            ap_condition_pp0_flush_enable <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state5, ap_block_state5_on_subcall_done)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_const_boolean_0 = ap_block_state5_on_subcall_done))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_icmp_ln1616_phi_fu_198_p4_assign_proc : process(icmp_ln1616_reg_194, ap_CS_fsm_pp0_stage0, icmp_ln161_reg_457, icmp_ln160_reg_462, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln160_reg_462 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_icmp_ln1616_phi_fu_198_p4 <= icmp_ln161_reg_457;
        else 
            ap_phi_mux_icmp_ln1616_phi_fu_198_p4 <= icmp_ln1616_reg_194;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state5, ap_block_state5_on_subcall_done)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_const_boolean_0 = ap_block_state5_on_subcall_done))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    ap_sync_grp_cluster_sort_build_em_jet_stream_fu_205_ap_ready <= (grp_cluster_sort_build_em_jet_stream_fu_205_ap_ready or ap_sync_reg_grp_cluster_sort_build_em_jet_stream_fu_205_ap_ready);
    em_objects_0 <= grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_0;
    em_objects_0_ap_vld <= grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_0_ap_vld;
    em_objects_1 <= grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_1;
    em_objects_1_ap_vld <= grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_1_ap_vld;
    em_objects_2 <= grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_2;
    em_objects_2_ap_vld <= grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_2_ap_vld;
    em_objects_3 <= grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_3;
    em_objects_3_ap_vld <= grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_3_ap_vld;
    em_objects_4 <= grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_4;
    em_objects_4_ap_vld <= grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_4_ap_vld;
    em_objects_5 <= grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_5;
    em_objects_5_ap_vld <= grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_5_ap_vld;
    em_objects_6 <= grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_6;
    em_objects_6_ap_vld <= grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_6_ap_vld;
    em_objects_7 <= grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_7;
    em_objects_7_ap_vld <= grp_cluster_sort_build_em_jet_stream_fu_205_em_objects_7_ap_vld;
    eta_fu_294_p3 <= 
        add_ln160_fu_280_p2 when (ap_phi_mux_icmp_ln1616_phi_fu_198_p4(0) = '1') else 
        eta2_fu_138;

    grp_cluster_sort_build_em_jet_stream_fu_205_ap_continue_assign_proc : process(ap_CS_fsm_state5, ap_block_state5_on_subcall_done)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_const_boolean_0 = ap_block_state5_on_subcall_done))) then 
            grp_cluster_sort_build_em_jet_stream_fu_205_ap_continue <= ap_const_logic_1;
        else 
            grp_cluster_sort_build_em_jet_stream_fu_205_ap_continue <= ap_const_logic_0;
        end if; 
    end process;

    grp_cluster_sort_build_em_jet_stream_fu_205_ap_start <= grp_cluster_sort_build_em_jet_stream_fu_205_ap_start_reg;
    ht_2_fu_389_p2 <= std_logic_vector(unsigned(conv4_i4_i4_fu_146) + unsigned(zext_ln163_3_fu_385_p1));

    ht_ap_vld_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            ht_ap_vld <= ap_const_logic_1;
        else 
            ht_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln160_fu_361_p2 <= "1" when (indvar_flatten1_fu_134 = ap_const_lv11_707) else "0";
    icmp_ln161_fu_355_p2 <= "1" when (phi_fu_343_p2 = ap_const_lv6_3C) else "0";
    jet_objects_0 <= grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_0;
    jet_objects_0_ap_vld <= grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_0_ap_vld;
    jet_objects_1 <= grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_1;
    jet_objects_1_ap_vld <= grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_1_ap_vld;
    jet_objects_2 <= grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_2;
    jet_objects_2_ap_vld <= grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_2_ap_vld;
    jet_objects_3 <= grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_3;
    jet_objects_3_ap_vld <= grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_3_ap_vld;
    jet_objects_4 <= grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_4;
    jet_objects_4_ap_vld <= grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_4_ap_vld;
    jet_objects_5 <= grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_5;
    jet_objects_5_ap_vld <= grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_5_ap_vld;
    jet_objects_6 <= grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_6;
    jet_objects_6_ap_vld <= grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_6_ap_vld;
    jet_objects_7 <= grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_7;
    jet_objects_7_ap_vld <= grp_cluster_sort_build_em_jet_stream_fu_205_jet_objects_7_ap_vld;
    p_shl_fu_302_p3 <= (eta_fu_294_p3 & ap_const_lv6_0);
    phi_fu_343_p2 <= std_logic_vector(unsigned(select_ln160_fu_286_p3) + unsigned(ap_const_lv6_1));
    select_ln160_fu_286_p3 <= 
        ap_const_lv6_0 when (ap_phi_mux_icmp_ln1616_phi_fu_198_p4(0) = '1') else 
        phi3_fu_142;
    sub_ln163_fu_322_p2 <= std_logic_vector(unsigned(p_shl_fu_302_p3) - unsigned(zext_ln163_fu_318_p1));
    tmp_fu_310_p3 <= (eta_fu_294_p3 & ap_const_lv2_0);

    towers_Addr_A_assign_proc : process(grp_cluster_sort_build_em_jet_stream_fu_205_towers_Addr_A, ap_CS_fsm_state5, towers_Addr_A_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            towers_Addr_A <= grp_cluster_sort_build_em_jet_stream_fu_205_towers_Addr_A;
        else 
            towers_Addr_A <= towers_Addr_A_local;
        end if; 
    end process;

    towers_Addr_A_local <= std_logic_vector(shift_left(unsigned(towers_Addr_A_orig),to_integer(unsigned('0' & ap_const_lv32_1(31-1 downto 0)))));
    towers_Addr_A_orig <= zext_ln163_2_fu_338_p1(32 - 1 downto 0);
    towers_Addr_B <= grp_cluster_sort_build_em_jet_stream_fu_205_towers_Addr_B;
    towers_Clk_A <= ap_clk;
    towers_Clk_B <= ap_clk;
    towers_Din_A <= ap_const_lv16_0;
    towers_Din_B <= ap_const_lv16_0;

    towers_EN_A_assign_proc : process(grp_cluster_sort_build_em_jet_stream_fu_205_towers_EN_A, ap_CS_fsm_state5, towers_EN_A_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            towers_EN_A <= grp_cluster_sort_build_em_jet_stream_fu_205_towers_EN_A;
        else 
            towers_EN_A <= towers_EN_A_local;
        end if; 
    end process;


    towers_EN_A_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            towers_EN_A_local <= ap_const_logic_1;
        else 
            towers_EN_A_local <= ap_const_logic_0;
        end if; 
    end process;


    towers_EN_B_assign_proc : process(grp_cluster_sort_build_em_jet_stream_fu_205_towers_EN_B, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            towers_EN_B <= grp_cluster_sort_build_em_jet_stream_fu_205_towers_EN_B;
        else 
            towers_EN_B <= ap_const_logic_0;
        end if; 
    end process;

    towers_Rst_A <= ap_rst_n_inv;
    towers_Rst_B <= ap_rst_n_inv;
    towers_WEN_A <= ap_const_lv2_0;
    towers_WEN_B <= ap_const_lv2_0;
    zext_ln161_fu_395_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ht_2_fu_389_p2),24));
    zext_ln163_1_fu_328_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln160_fu_286_p3),11));
    zext_ln163_2_fu_338_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln163_5_fu_332_p2),64));
    zext_ln163_3_fu_385_p0 <= towers_Dout_A(12 - 1 downto 0);
    zext_ln163_3_fu_385_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln163_3_fu_385_p0),23));
    zext_ln163_fu_318_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_310_p3),11));
end behav;
