// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="calo_trigger_ref_calo_trigger_ref,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu13p-fsga2577-2-e,HLS_INPUT_CLOCK=25.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=9.749938,HLS_SYN_LAT=44167,HLS_SYN_TPT=none,HLS_SYN_MEM=11,HLS_SYN_DSP=0,HLS_SYN_FF=1009,HLS_SYN_LUT=4027,HLS_VERSION=2024_1}" *)

module calo_trigger_ref (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        grid_address0,
        grid_ce0,
        grid_q0,
        grid_address1,
        grid_ce1,
        grid_q1,
        seed_threshold,
        cluster_threshold,
        objects_address0,
        objects_ce0,
        objects_we0,
        objects_d0,
        objects_address1,
        objects_ce1,
        objects_we1,
        objects_d1,
        ht,
        ht_ap_vld,
        num_clusters,
        num_clusters_ap_vld
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [10:0] grid_address0;
output   grid_ce0;
input  [11:0] grid_q0;
output  [10:0] grid_address1;
output   grid_ce1;
input  [11:0] grid_q1;
input  [11:0] seed_threshold;
input  [19:0] cluster_threshold;
output  [2:0] objects_address0;
output   objects_ce0;
output   objects_we0;
output  [88:0] objects_d0;
output  [2:0] objects_address1;
output   objects_ce1;
output   objects_we1;
output  [88:0] objects_d1;
output  [23:0] ht;
output   ht_ap_vld;
output  [31:0] num_clusters;
output   num_clusters_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[10:0] grid_address0;
reg grid_ce0;
reg grid_ce1;
reg ht_ap_vld;
reg num_clusters_ap_vld;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [31:0] grp_find_clusters_3_5_s_fu_134_ap_return;
reg   [31:0] local_num_clusters_reg_221;
wire    ap_CS_fsm_state2;
reg   [2:0] top_clusters_valid_address0;
reg    top_clusters_valid_ce0;
reg    top_clusters_valid_we0;
wire   [0:0] top_clusters_valid_q0;
reg    top_clusters_valid_ce1;
wire   [0:0] top_clusters_valid_q1;
reg   [10:0] clusters_et_address0;
reg    clusters_et_ce0;
reg    clusters_et_we0;
wire   [15:0] clusters_et_q0;
reg   [10:0] clusters_isolation_et_address0;
reg    clusters_isolation_et_ce0;
reg    clusters_isolation_et_we0;
wire   [17:0] clusters_isolation_et_q0;
reg   [10:0] clusters_eta_address0;
reg    clusters_eta_ce0;
reg    clusters_eta_we0;
wire   [4:0] clusters_eta_q0;
reg   [10:0] clusters_phi_address0;
reg    clusters_phi_ce0;
reg    clusters_phi_we0;
wire   [5:0] clusters_phi_q0;
reg   [10:0] clusters_window_size_address0;
reg    clusters_window_size_ce0;
reg    clusters_window_size_we0;
wire   [0:0] clusters_window_size_q0;
reg   [10:0] clusters_iso_outer_size_address0;
reg    clusters_iso_outer_size_ce0;
reg    clusters_iso_outer_size_we0;
wire   [2:0] clusters_iso_outer_size_q0;
reg   [10:0] clusters_valid_address0;
reg    clusters_valid_ce0;
reg    clusters_valid_we0;
wire   [0:0] clusters_valid_q0;
reg   [2:0] top_clusters_et_address0;
reg    top_clusters_et_ce0;
reg    top_clusters_et_we0;
wire   [15:0] top_clusters_et_q0;
reg    top_clusters_et_ce1;
wire   [15:0] top_clusters_et_q1;
reg   [2:0] top_clusters_isolation_et_address0;
reg    top_clusters_isolation_et_ce0;
reg    top_clusters_isolation_et_we0;
wire   [17:0] top_clusters_isolation_et_q0;
reg    top_clusters_isolation_et_ce1;
wire   [17:0] top_clusters_isolation_et_q1;
reg   [2:0] top_clusters_eta_address0;
reg    top_clusters_eta_ce0;
reg    top_clusters_eta_we0;
wire   [4:0] top_clusters_eta_q0;
reg    top_clusters_eta_ce1;
wire   [4:0] top_clusters_eta_q1;
reg   [2:0] top_clusters_phi_address0;
reg    top_clusters_phi_ce0;
reg    top_clusters_phi_we0;
wire   [5:0] top_clusters_phi_q0;
reg    top_clusters_phi_ce1;
wire   [5:0] top_clusters_phi_q1;
reg   [2:0] top_clusters_window_size_address0;
reg    top_clusters_window_size_ce0;
reg    top_clusters_window_size_we0;
wire   [1:0] top_clusters_window_size_q0;
reg    top_clusters_window_size_ce1;
wire   [1:0] top_clusters_window_size_q1;
wire   [2:0] top_clusters_iso_outer_size_q1;
wire    grp_find_clusters_3_5_s_fu_134_ap_start;
wire    grp_find_clusters_3_5_s_fu_134_ap_done;
wire    grp_find_clusters_3_5_s_fu_134_ap_idle;
wire    grp_find_clusters_3_5_s_fu_134_ap_ready;
wire   [10:0] grp_find_clusters_3_5_s_fu_134_grid_address0;
wire    grp_find_clusters_3_5_s_fu_134_grid_ce0;
wire   [10:0] grp_find_clusters_3_5_s_fu_134_grid_address1;
wire    grp_find_clusters_3_5_s_fu_134_grid_ce1;
wire   [10:0] grp_find_clusters_3_5_s_fu_134_clusters_et_address0;
wire    grp_find_clusters_3_5_s_fu_134_clusters_et_ce0;
wire    grp_find_clusters_3_5_s_fu_134_clusters_et_we0;
wire   [15:0] grp_find_clusters_3_5_s_fu_134_clusters_et_d0;
wire   [10:0] grp_find_clusters_3_5_s_fu_134_clusters_isolation_et_address0;
wire    grp_find_clusters_3_5_s_fu_134_clusters_isolation_et_ce0;
wire    grp_find_clusters_3_5_s_fu_134_clusters_isolation_et_we0;
wire   [17:0] grp_find_clusters_3_5_s_fu_134_clusters_isolation_et_d0;
wire   [10:0] grp_find_clusters_3_5_s_fu_134_clusters_eta_address0;
wire    grp_find_clusters_3_5_s_fu_134_clusters_eta_ce0;
wire    grp_find_clusters_3_5_s_fu_134_clusters_eta_we0;
wire   [4:0] grp_find_clusters_3_5_s_fu_134_clusters_eta_d0;
wire   [10:0] grp_find_clusters_3_5_s_fu_134_clusters_phi_address0;
wire    grp_find_clusters_3_5_s_fu_134_clusters_phi_ce0;
wire    grp_find_clusters_3_5_s_fu_134_clusters_phi_we0;
wire   [5:0] grp_find_clusters_3_5_s_fu_134_clusters_phi_d0;
wire   [10:0] grp_find_clusters_3_5_s_fu_134_clusters_window_size_address0;
wire    grp_find_clusters_3_5_s_fu_134_clusters_window_size_ce0;
wire    grp_find_clusters_3_5_s_fu_134_clusters_window_size_we0;
wire   [0:0] grp_find_clusters_3_5_s_fu_134_clusters_window_size_d0;
wire   [10:0] grp_find_clusters_3_5_s_fu_134_clusters_iso_outer_size_address0;
wire    grp_find_clusters_3_5_s_fu_134_clusters_iso_outer_size_ce0;
wire    grp_find_clusters_3_5_s_fu_134_clusters_iso_outer_size_we0;
wire   [2:0] grp_find_clusters_3_5_s_fu_134_clusters_iso_outer_size_d0;
wire   [10:0] grp_find_clusters_3_5_s_fu_134_clusters_valid_address0;
wire    grp_find_clusters_3_5_s_fu_134_clusters_valid_ce0;
wire    grp_find_clusters_3_5_s_fu_134_clusters_valid_we0;
wire   [0:0] grp_find_clusters_3_5_s_fu_134_clusters_valid_d0;
wire    grp_select_top_n_fu_159_ap_start;
wire    grp_select_top_n_fu_159_ap_done;
wire    grp_select_top_n_fu_159_ap_idle;
wire    grp_select_top_n_fu_159_ap_ready;
wire   [10:0] grp_select_top_n_fu_159_clusters_et_address0;
wire    grp_select_top_n_fu_159_clusters_et_ce0;
wire   [10:0] grp_select_top_n_fu_159_clusters_isolation_et_address0;
wire    grp_select_top_n_fu_159_clusters_isolation_et_ce0;
wire   [10:0] grp_select_top_n_fu_159_clusters_eta_address0;
wire    grp_select_top_n_fu_159_clusters_eta_ce0;
wire   [10:0] grp_select_top_n_fu_159_clusters_phi_address0;
wire    grp_select_top_n_fu_159_clusters_phi_ce0;
wire   [10:0] grp_select_top_n_fu_159_clusters_window_size_address0;
wire    grp_select_top_n_fu_159_clusters_window_size_ce0;
wire   [10:0] grp_select_top_n_fu_159_clusters_iso_outer_size_address0;
wire    grp_select_top_n_fu_159_clusters_iso_outer_size_ce0;
wire   [10:0] grp_select_top_n_fu_159_clusters_valid_address0;
wire    grp_select_top_n_fu_159_clusters_valid_ce0;
wire   [2:0] grp_select_top_n_fu_159_top_clusters_et_address0;
wire    grp_select_top_n_fu_159_top_clusters_et_ce0;
wire    grp_select_top_n_fu_159_top_clusters_et_we0;
wire   [15:0] grp_select_top_n_fu_159_top_clusters_et_d0;
wire   [2:0] grp_select_top_n_fu_159_top_clusters_et_address1;
wire    grp_select_top_n_fu_159_top_clusters_et_ce1;
wire   [2:0] grp_select_top_n_fu_159_top_clusters_isolation_et_address0;
wire    grp_select_top_n_fu_159_top_clusters_isolation_et_ce0;
wire    grp_select_top_n_fu_159_top_clusters_isolation_et_we0;
wire   [17:0] grp_select_top_n_fu_159_top_clusters_isolation_et_d0;
wire   [2:0] grp_select_top_n_fu_159_top_clusters_isolation_et_address1;
wire    grp_select_top_n_fu_159_top_clusters_isolation_et_ce1;
wire   [2:0] grp_select_top_n_fu_159_top_clusters_eta_address0;
wire    grp_select_top_n_fu_159_top_clusters_eta_ce0;
wire    grp_select_top_n_fu_159_top_clusters_eta_we0;
wire   [4:0] grp_select_top_n_fu_159_top_clusters_eta_d0;
wire   [2:0] grp_select_top_n_fu_159_top_clusters_eta_address1;
wire    grp_select_top_n_fu_159_top_clusters_eta_ce1;
wire   [2:0] grp_select_top_n_fu_159_top_clusters_phi_address0;
wire    grp_select_top_n_fu_159_top_clusters_phi_ce0;
wire    grp_select_top_n_fu_159_top_clusters_phi_we0;
wire   [5:0] grp_select_top_n_fu_159_top_clusters_phi_d0;
wire   [2:0] grp_select_top_n_fu_159_top_clusters_phi_address1;
wire    grp_select_top_n_fu_159_top_clusters_phi_ce1;
wire   [2:0] grp_select_top_n_fu_159_top_clusters_window_size_address0;
wire    grp_select_top_n_fu_159_top_clusters_window_size_ce0;
wire    grp_select_top_n_fu_159_top_clusters_window_size_we0;
wire   [1:0] grp_select_top_n_fu_159_top_clusters_window_size_d0;
wire   [2:0] grp_select_top_n_fu_159_top_clusters_window_size_address1;
wire    grp_select_top_n_fu_159_top_clusters_window_size_ce1;
wire   [2:0] grp_select_top_n_fu_159_top_clusters_iso_outer_size_address0;
wire    grp_select_top_n_fu_159_top_clusters_iso_outer_size_ce0;
wire    grp_select_top_n_fu_159_top_clusters_iso_outer_size_we0;
wire   [2:0] grp_select_top_n_fu_159_top_clusters_iso_outer_size_d0;
wire   [2:0] grp_select_top_n_fu_159_top_clusters_iso_outer_size_address1;
wire    grp_select_top_n_fu_159_top_clusters_iso_outer_size_ce1;
wire   [2:0] grp_select_top_n_fu_159_top_clusters_valid_address0;
wire    grp_select_top_n_fu_159_top_clusters_valid_ce0;
wire    grp_select_top_n_fu_159_top_clusters_valid_we0;
wire   [0:0] grp_select_top_n_fu_159_top_clusters_valid_d0;
wire   [2:0] grp_select_top_n_fu_159_top_clusters_valid_address1;
wire    grp_select_top_n_fu_159_top_clusters_valid_ce1;
wire    grp_calo_trigger_ref_Pipeline_VITIS_LOOP_145_1_VITIS_LOOP_146_2_fu_178_ap_start;
wire    grp_calo_trigger_ref_Pipeline_VITIS_LOOP_145_1_VITIS_LOOP_146_2_fu_178_ap_done;
wire    grp_calo_trigger_ref_Pipeline_VITIS_LOOP_145_1_VITIS_LOOP_146_2_fu_178_ap_idle;
wire    grp_calo_trigger_ref_Pipeline_VITIS_LOOP_145_1_VITIS_LOOP_146_2_fu_178_ap_ready;
wire   [10:0] grp_calo_trigger_ref_Pipeline_VITIS_LOOP_145_1_VITIS_LOOP_146_2_fu_178_grid_address0;
wire    grp_calo_trigger_ref_Pipeline_VITIS_LOOP_145_1_VITIS_LOOP_146_2_fu_178_grid_ce0;
wire   [22:0] grp_calo_trigger_ref_Pipeline_VITIS_LOOP_145_1_VITIS_LOOP_146_2_fu_178_conv4_i4_i_i_out;
wire    grp_calo_trigger_ref_Pipeline_VITIS_LOOP_145_1_VITIS_LOOP_146_2_fu_178_conv4_i4_i_i_out_ap_vld;
wire    grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_ap_start;
wire    grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_ap_done;
wire    grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_ap_idle;
wire    grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_ap_ready;
wire   [2:0] grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_objects_address0;
wire    grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_objects_ce0;
wire    grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_objects_we0;
wire   [88:0] grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_objects_d0;
wire   [2:0] grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_objects_address1;
wire    grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_objects_ce1;
wire    grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_objects_we1;
wire   [88:0] grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_objects_d1;
wire   [2:0] grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_top_clusters_valid_address0;
wire    grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_top_clusters_valid_ce0;
wire   [2:0] grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_top_clusters_et_address0;
wire    grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_top_clusters_et_ce0;
wire   [2:0] grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_top_clusters_isolation_et_address0;
wire    grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_top_clusters_isolation_et_ce0;
wire   [2:0] grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_top_clusters_eta_address0;
wire    grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_top_clusters_eta_ce0;
wire   [2:0] grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_top_clusters_phi_address0;
wire    grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_top_clusters_phi_ce0;
wire   [2:0] grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_top_clusters_window_size_address0;
wire    grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_top_clusters_window_size_ce0;
reg    grp_find_clusters_3_5_s_fu_134_ap_start_reg;
reg    grp_select_top_n_fu_159_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_calo_trigger_ref_Pipeline_VITIS_LOOP_145_1_VITIS_LOOP_146_2_fu_178_ap_start_reg;
reg    grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_block_state4_on_subcall_done;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 grp_find_clusters_3_5_s_fu_134_ap_start_reg = 1'b0;
#0 grp_select_top_n_fu_159_ap_start_reg = 1'b0;
#0 grp_calo_trigger_ref_Pipeline_VITIS_LOOP_145_1_VITIS_LOOP_146_2_fu_178_ap_start_reg = 1'b0;
#0 grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_ap_start_reg = 1'b0;
end

calo_trigger_ref_top_clusters_valid_RAM_AUTO_1R1W #(
    .DataWidth( 1 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
top_clusters_valid_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(top_clusters_valid_address0),
    .ce0(top_clusters_valid_ce0),
    .we0(top_clusters_valid_we0),
    .d0(grp_select_top_n_fu_159_top_clusters_valid_d0),
    .q0(top_clusters_valid_q0),
    .address1(grp_select_top_n_fu_159_top_clusters_valid_address1),
    .ce1(top_clusters_valid_ce1),
    .q1(top_clusters_valid_q1)
);

calo_trigger_ref_clusters_et_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 1800 ),
    .AddressWidth( 11 ))
clusters_et_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(clusters_et_address0),
    .ce0(clusters_et_ce0),
    .we0(clusters_et_we0),
    .d0(grp_find_clusters_3_5_s_fu_134_clusters_et_d0),
    .q0(clusters_et_q0)
);

calo_trigger_ref_clusters_isolation_et_RAM_AUTO_1R1W #(
    .DataWidth( 18 ),
    .AddressRange( 1800 ),
    .AddressWidth( 11 ))
clusters_isolation_et_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(clusters_isolation_et_address0),
    .ce0(clusters_isolation_et_ce0),
    .we0(clusters_isolation_et_we0),
    .d0(grp_find_clusters_3_5_s_fu_134_clusters_isolation_et_d0),
    .q0(clusters_isolation_et_q0)
);

calo_trigger_ref_clusters_eta_RAM_AUTO_1R1W #(
    .DataWidth( 5 ),
    .AddressRange( 1800 ),
    .AddressWidth( 11 ))
clusters_eta_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(clusters_eta_address0),
    .ce0(clusters_eta_ce0),
    .we0(clusters_eta_we0),
    .d0(grp_find_clusters_3_5_s_fu_134_clusters_eta_d0),
    .q0(clusters_eta_q0)
);

calo_trigger_ref_clusters_phi_RAM_AUTO_1R1W #(
    .DataWidth( 6 ),
    .AddressRange( 1800 ),
    .AddressWidth( 11 ))
clusters_phi_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(clusters_phi_address0),
    .ce0(clusters_phi_ce0),
    .we0(clusters_phi_we0),
    .d0(grp_find_clusters_3_5_s_fu_134_clusters_phi_d0),
    .q0(clusters_phi_q0)
);

calo_trigger_ref_clusters_window_size_RAM_AUTO_1R1W #(
    .DataWidth( 1 ),
    .AddressRange( 1800 ),
    .AddressWidth( 11 ))
clusters_window_size_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(clusters_window_size_address0),
    .ce0(clusters_window_size_ce0),
    .we0(clusters_window_size_we0),
    .d0(grp_find_clusters_3_5_s_fu_134_clusters_window_size_d0),
    .q0(clusters_window_size_q0)
);

calo_trigger_ref_clusters_iso_outer_size_RAM_AUTO_1R1W #(
    .DataWidth( 3 ),
    .AddressRange( 1800 ),
    .AddressWidth( 11 ))
clusters_iso_outer_size_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(clusters_iso_outer_size_address0),
    .ce0(clusters_iso_outer_size_ce0),
    .we0(clusters_iso_outer_size_we0),
    .d0(grp_find_clusters_3_5_s_fu_134_clusters_iso_outer_size_d0),
    .q0(clusters_iso_outer_size_q0)
);

calo_trigger_ref_clusters_window_size_RAM_AUTO_1R1W #(
    .DataWidth( 1 ),
    .AddressRange( 1800 ),
    .AddressWidth( 11 ))
clusters_valid_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(clusters_valid_address0),
    .ce0(clusters_valid_ce0),
    .we0(clusters_valid_we0),
    .d0(grp_find_clusters_3_5_s_fu_134_clusters_valid_d0),
    .q0(clusters_valid_q0)
);

calo_trigger_ref_top_clusters_et_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
top_clusters_et_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(top_clusters_et_address0),
    .ce0(top_clusters_et_ce0),
    .we0(top_clusters_et_we0),
    .d0(grp_select_top_n_fu_159_top_clusters_et_d0),
    .q0(top_clusters_et_q0),
    .address1(grp_select_top_n_fu_159_top_clusters_et_address1),
    .ce1(top_clusters_et_ce1),
    .q1(top_clusters_et_q1)
);

calo_trigger_ref_top_clusters_isolation_et_RAM_AUTO_1R1W #(
    .DataWidth( 18 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
top_clusters_isolation_et_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(top_clusters_isolation_et_address0),
    .ce0(top_clusters_isolation_et_ce0),
    .we0(top_clusters_isolation_et_we0),
    .d0(grp_select_top_n_fu_159_top_clusters_isolation_et_d0),
    .q0(top_clusters_isolation_et_q0),
    .address1(grp_select_top_n_fu_159_top_clusters_isolation_et_address1),
    .ce1(top_clusters_isolation_et_ce1),
    .q1(top_clusters_isolation_et_q1)
);

calo_trigger_ref_top_clusters_eta_RAM_AUTO_1R1W #(
    .DataWidth( 5 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
top_clusters_eta_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(top_clusters_eta_address0),
    .ce0(top_clusters_eta_ce0),
    .we0(top_clusters_eta_we0),
    .d0(grp_select_top_n_fu_159_top_clusters_eta_d0),
    .q0(top_clusters_eta_q0),
    .address1(grp_select_top_n_fu_159_top_clusters_eta_address1),
    .ce1(top_clusters_eta_ce1),
    .q1(top_clusters_eta_q1)
);

calo_trigger_ref_top_clusters_phi_RAM_AUTO_1R1W #(
    .DataWidth( 6 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
top_clusters_phi_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(top_clusters_phi_address0),
    .ce0(top_clusters_phi_ce0),
    .we0(top_clusters_phi_we0),
    .d0(grp_select_top_n_fu_159_top_clusters_phi_d0),
    .q0(top_clusters_phi_q0),
    .address1(grp_select_top_n_fu_159_top_clusters_phi_address1),
    .ce1(top_clusters_phi_ce1),
    .q1(top_clusters_phi_q1)
);

calo_trigger_ref_top_clusters_window_size_RAM_AUTO_1R1W #(
    .DataWidth( 2 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
top_clusters_window_size_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(top_clusters_window_size_address0),
    .ce0(top_clusters_window_size_ce0),
    .we0(top_clusters_window_size_we0),
    .d0(grp_select_top_n_fu_159_top_clusters_window_size_d0),
    .q0(top_clusters_window_size_q0),
    .address1(grp_select_top_n_fu_159_top_clusters_window_size_address1),
    .ce1(top_clusters_window_size_ce1),
    .q1(top_clusters_window_size_q1)
);

calo_trigger_ref_top_clusters_iso_outer_size_RAM_AUTO_1R1W #(
    .DataWidth( 3 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
top_clusters_iso_outer_size_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_select_top_n_fu_159_top_clusters_iso_outer_size_address0),
    .ce0(grp_select_top_n_fu_159_top_clusters_iso_outer_size_ce0),
    .we0(grp_select_top_n_fu_159_top_clusters_iso_outer_size_we0),
    .d0(grp_select_top_n_fu_159_top_clusters_iso_outer_size_d0),
    .address1(grp_select_top_n_fu_159_top_clusters_iso_outer_size_address1),
    .ce1(grp_select_top_n_fu_159_top_clusters_iso_outer_size_ce1),
    .q1(top_clusters_iso_outer_size_q1)
);

calo_trigger_ref_find_clusters_3_5_s grp_find_clusters_3_5_s_fu_134(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_find_clusters_3_5_s_fu_134_ap_start),
    .ap_done(grp_find_clusters_3_5_s_fu_134_ap_done),
    .ap_idle(grp_find_clusters_3_5_s_fu_134_ap_idle),
    .ap_ready(grp_find_clusters_3_5_s_fu_134_ap_ready),
    .grid_address0(grp_find_clusters_3_5_s_fu_134_grid_address0),
    .grid_ce0(grp_find_clusters_3_5_s_fu_134_grid_ce0),
    .grid_q0(grid_q0),
    .grid_address1(grp_find_clusters_3_5_s_fu_134_grid_address1),
    .grid_ce1(grp_find_clusters_3_5_s_fu_134_grid_ce1),
    .grid_q1(grid_q1),
    .seed_threshold(seed_threshold),
    .cluster_threshold(cluster_threshold),
    .clusters_et_address0(grp_find_clusters_3_5_s_fu_134_clusters_et_address0),
    .clusters_et_ce0(grp_find_clusters_3_5_s_fu_134_clusters_et_ce0),
    .clusters_et_we0(grp_find_clusters_3_5_s_fu_134_clusters_et_we0),
    .clusters_et_d0(grp_find_clusters_3_5_s_fu_134_clusters_et_d0),
    .clusters_isolation_et_address0(grp_find_clusters_3_5_s_fu_134_clusters_isolation_et_address0),
    .clusters_isolation_et_ce0(grp_find_clusters_3_5_s_fu_134_clusters_isolation_et_ce0),
    .clusters_isolation_et_we0(grp_find_clusters_3_5_s_fu_134_clusters_isolation_et_we0),
    .clusters_isolation_et_d0(grp_find_clusters_3_5_s_fu_134_clusters_isolation_et_d0),
    .clusters_eta_address0(grp_find_clusters_3_5_s_fu_134_clusters_eta_address0),
    .clusters_eta_ce0(grp_find_clusters_3_5_s_fu_134_clusters_eta_ce0),
    .clusters_eta_we0(grp_find_clusters_3_5_s_fu_134_clusters_eta_we0),
    .clusters_eta_d0(grp_find_clusters_3_5_s_fu_134_clusters_eta_d0),
    .clusters_phi_address0(grp_find_clusters_3_5_s_fu_134_clusters_phi_address0),
    .clusters_phi_ce0(grp_find_clusters_3_5_s_fu_134_clusters_phi_ce0),
    .clusters_phi_we0(grp_find_clusters_3_5_s_fu_134_clusters_phi_we0),
    .clusters_phi_d0(grp_find_clusters_3_5_s_fu_134_clusters_phi_d0),
    .clusters_window_size_address0(grp_find_clusters_3_5_s_fu_134_clusters_window_size_address0),
    .clusters_window_size_ce0(grp_find_clusters_3_5_s_fu_134_clusters_window_size_ce0),
    .clusters_window_size_we0(grp_find_clusters_3_5_s_fu_134_clusters_window_size_we0),
    .clusters_window_size_d0(grp_find_clusters_3_5_s_fu_134_clusters_window_size_d0),
    .clusters_iso_outer_size_address0(grp_find_clusters_3_5_s_fu_134_clusters_iso_outer_size_address0),
    .clusters_iso_outer_size_ce0(grp_find_clusters_3_5_s_fu_134_clusters_iso_outer_size_ce0),
    .clusters_iso_outer_size_we0(grp_find_clusters_3_5_s_fu_134_clusters_iso_outer_size_we0),
    .clusters_iso_outer_size_d0(grp_find_clusters_3_5_s_fu_134_clusters_iso_outer_size_d0),
    .clusters_valid_address0(grp_find_clusters_3_5_s_fu_134_clusters_valid_address0),
    .clusters_valid_ce0(grp_find_clusters_3_5_s_fu_134_clusters_valid_ce0),
    .clusters_valid_we0(grp_find_clusters_3_5_s_fu_134_clusters_valid_we0),
    .clusters_valid_d0(grp_find_clusters_3_5_s_fu_134_clusters_valid_d0),
    .ap_return(grp_find_clusters_3_5_s_fu_134_ap_return)
);

calo_trigger_ref_select_top_n grp_select_top_n_fu_159(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_select_top_n_fu_159_ap_start),
    .ap_done(grp_select_top_n_fu_159_ap_done),
    .ap_idle(grp_select_top_n_fu_159_ap_idle),
    .ap_ready(grp_select_top_n_fu_159_ap_ready),
    .clusters_et_address0(grp_select_top_n_fu_159_clusters_et_address0),
    .clusters_et_ce0(grp_select_top_n_fu_159_clusters_et_ce0),
    .clusters_et_q0(clusters_et_q0),
    .clusters_isolation_et_address0(grp_select_top_n_fu_159_clusters_isolation_et_address0),
    .clusters_isolation_et_ce0(grp_select_top_n_fu_159_clusters_isolation_et_ce0),
    .clusters_isolation_et_q0(clusters_isolation_et_q0),
    .clusters_eta_address0(grp_select_top_n_fu_159_clusters_eta_address0),
    .clusters_eta_ce0(grp_select_top_n_fu_159_clusters_eta_ce0),
    .clusters_eta_q0(clusters_eta_q0),
    .clusters_phi_address0(grp_select_top_n_fu_159_clusters_phi_address0),
    .clusters_phi_ce0(grp_select_top_n_fu_159_clusters_phi_ce0),
    .clusters_phi_q0(clusters_phi_q0),
    .clusters_window_size_address0(grp_select_top_n_fu_159_clusters_window_size_address0),
    .clusters_window_size_ce0(grp_select_top_n_fu_159_clusters_window_size_ce0),
    .clusters_window_size_q0(clusters_window_size_q0),
    .clusters_iso_outer_size_address0(grp_select_top_n_fu_159_clusters_iso_outer_size_address0),
    .clusters_iso_outer_size_ce0(grp_select_top_n_fu_159_clusters_iso_outer_size_ce0),
    .clusters_iso_outer_size_q0(clusters_iso_outer_size_q0),
    .clusters_valid_address0(grp_select_top_n_fu_159_clusters_valid_address0),
    .clusters_valid_ce0(grp_select_top_n_fu_159_clusters_valid_ce0),
    .clusters_valid_q0(clusters_valid_q0),
    .num_clusters(local_num_clusters_reg_221),
    .top_clusters_et_address0(grp_select_top_n_fu_159_top_clusters_et_address0),
    .top_clusters_et_ce0(grp_select_top_n_fu_159_top_clusters_et_ce0),
    .top_clusters_et_we0(grp_select_top_n_fu_159_top_clusters_et_we0),
    .top_clusters_et_d0(grp_select_top_n_fu_159_top_clusters_et_d0),
    .top_clusters_et_q0(top_clusters_et_q0),
    .top_clusters_et_address1(grp_select_top_n_fu_159_top_clusters_et_address1),
    .top_clusters_et_ce1(grp_select_top_n_fu_159_top_clusters_et_ce1),
    .top_clusters_et_q1(top_clusters_et_q1),
    .top_clusters_isolation_et_address0(grp_select_top_n_fu_159_top_clusters_isolation_et_address0),
    .top_clusters_isolation_et_ce0(grp_select_top_n_fu_159_top_clusters_isolation_et_ce0),
    .top_clusters_isolation_et_we0(grp_select_top_n_fu_159_top_clusters_isolation_et_we0),
    .top_clusters_isolation_et_d0(grp_select_top_n_fu_159_top_clusters_isolation_et_d0),
    .top_clusters_isolation_et_address1(grp_select_top_n_fu_159_top_clusters_isolation_et_address1),
    .top_clusters_isolation_et_ce1(grp_select_top_n_fu_159_top_clusters_isolation_et_ce1),
    .top_clusters_isolation_et_q1(top_clusters_isolation_et_q1),
    .top_clusters_eta_address0(grp_select_top_n_fu_159_top_clusters_eta_address0),
    .top_clusters_eta_ce0(grp_select_top_n_fu_159_top_clusters_eta_ce0),
    .top_clusters_eta_we0(grp_select_top_n_fu_159_top_clusters_eta_we0),
    .top_clusters_eta_d0(grp_select_top_n_fu_159_top_clusters_eta_d0),
    .top_clusters_eta_q0(top_clusters_eta_q0),
    .top_clusters_eta_address1(grp_select_top_n_fu_159_top_clusters_eta_address1),
    .top_clusters_eta_ce1(grp_select_top_n_fu_159_top_clusters_eta_ce1),
    .top_clusters_eta_q1(top_clusters_eta_q1),
    .top_clusters_phi_address0(grp_select_top_n_fu_159_top_clusters_phi_address0),
    .top_clusters_phi_ce0(grp_select_top_n_fu_159_top_clusters_phi_ce0),
    .top_clusters_phi_we0(grp_select_top_n_fu_159_top_clusters_phi_we0),
    .top_clusters_phi_d0(grp_select_top_n_fu_159_top_clusters_phi_d0),
    .top_clusters_phi_q0(top_clusters_phi_q0),
    .top_clusters_phi_address1(grp_select_top_n_fu_159_top_clusters_phi_address1),
    .top_clusters_phi_ce1(grp_select_top_n_fu_159_top_clusters_phi_ce1),
    .top_clusters_phi_q1(top_clusters_phi_q1),
    .top_clusters_window_size_address0(grp_select_top_n_fu_159_top_clusters_window_size_address0),
    .top_clusters_window_size_ce0(grp_select_top_n_fu_159_top_clusters_window_size_ce0),
    .top_clusters_window_size_we0(grp_select_top_n_fu_159_top_clusters_window_size_we0),
    .top_clusters_window_size_d0(grp_select_top_n_fu_159_top_clusters_window_size_d0),
    .top_clusters_window_size_address1(grp_select_top_n_fu_159_top_clusters_window_size_address1),
    .top_clusters_window_size_ce1(grp_select_top_n_fu_159_top_clusters_window_size_ce1),
    .top_clusters_window_size_q1(top_clusters_window_size_q1),
    .top_clusters_iso_outer_size_address0(grp_select_top_n_fu_159_top_clusters_iso_outer_size_address0),
    .top_clusters_iso_outer_size_ce0(grp_select_top_n_fu_159_top_clusters_iso_outer_size_ce0),
    .top_clusters_iso_outer_size_we0(grp_select_top_n_fu_159_top_clusters_iso_outer_size_we0),
    .top_clusters_iso_outer_size_d0(grp_select_top_n_fu_159_top_clusters_iso_outer_size_d0),
    .top_clusters_iso_outer_size_address1(grp_select_top_n_fu_159_top_clusters_iso_outer_size_address1),
    .top_clusters_iso_outer_size_ce1(grp_select_top_n_fu_159_top_clusters_iso_outer_size_ce1),
    .top_clusters_iso_outer_size_q1(top_clusters_iso_outer_size_q1),
    .top_clusters_valid_address0(grp_select_top_n_fu_159_top_clusters_valid_address0),
    .top_clusters_valid_ce0(grp_select_top_n_fu_159_top_clusters_valid_ce0),
    .top_clusters_valid_we0(grp_select_top_n_fu_159_top_clusters_valid_we0),
    .top_clusters_valid_d0(grp_select_top_n_fu_159_top_clusters_valid_d0),
    .top_clusters_valid_q0(top_clusters_valid_q0),
    .top_clusters_valid_address1(grp_select_top_n_fu_159_top_clusters_valid_address1),
    .top_clusters_valid_ce1(grp_select_top_n_fu_159_top_clusters_valid_ce1),
    .top_clusters_valid_q1(top_clusters_valid_q1)
);

calo_trigger_ref_calo_trigger_ref_Pipeline_VITIS_LOOP_145_1_VITIS_LOOP_146_2 grp_calo_trigger_ref_Pipeline_VITIS_LOOP_145_1_VITIS_LOOP_146_2_fu_178(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_calo_trigger_ref_Pipeline_VITIS_LOOP_145_1_VITIS_LOOP_146_2_fu_178_ap_start),
    .ap_done(grp_calo_trigger_ref_Pipeline_VITIS_LOOP_145_1_VITIS_LOOP_146_2_fu_178_ap_done),
    .ap_idle(grp_calo_trigger_ref_Pipeline_VITIS_LOOP_145_1_VITIS_LOOP_146_2_fu_178_ap_idle),
    .ap_ready(grp_calo_trigger_ref_Pipeline_VITIS_LOOP_145_1_VITIS_LOOP_146_2_fu_178_ap_ready),
    .grid_address0(grp_calo_trigger_ref_Pipeline_VITIS_LOOP_145_1_VITIS_LOOP_146_2_fu_178_grid_address0),
    .grid_ce0(grp_calo_trigger_ref_Pipeline_VITIS_LOOP_145_1_VITIS_LOOP_146_2_fu_178_grid_ce0),
    .grid_q0(grid_q0),
    .conv4_i4_i_i_out(grp_calo_trigger_ref_Pipeline_VITIS_LOOP_145_1_VITIS_LOOP_146_2_fu_178_conv4_i4_i_i_out),
    .conv4_i4_i_i_out_ap_vld(grp_calo_trigger_ref_Pipeline_VITIS_LOOP_145_1_VITIS_LOOP_146_2_fu_178_conv4_i4_i_i_out_ap_vld)
);

calo_trigger_ref_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1 grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_ap_start),
    .ap_done(grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_ap_done),
    .ap_idle(grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_ap_idle),
    .ap_ready(grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_ap_ready),
    .objects_address0(grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_objects_address0),
    .objects_ce0(grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_objects_ce0),
    .objects_we0(grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_objects_we0),
    .objects_d0(grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_objects_d0),
    .objects_address1(grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_objects_address1),
    .objects_ce1(grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_objects_ce1),
    .objects_we1(grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_objects_we1),
    .objects_d1(grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_objects_d1),
    .top_clusters_valid_address0(grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_top_clusters_valid_address0),
    .top_clusters_valid_ce0(grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_top_clusters_valid_ce0),
    .top_clusters_valid_q0(top_clusters_valid_q0),
    .top_clusters_et_address0(grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_top_clusters_et_address0),
    .top_clusters_et_ce0(grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_top_clusters_et_ce0),
    .top_clusters_et_q0(top_clusters_et_q0),
    .top_clusters_isolation_et_address0(grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_top_clusters_isolation_et_address0),
    .top_clusters_isolation_et_ce0(grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_top_clusters_isolation_et_ce0),
    .top_clusters_isolation_et_q0(top_clusters_isolation_et_q0),
    .top_clusters_eta_address0(grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_top_clusters_eta_address0),
    .top_clusters_eta_ce0(grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_top_clusters_eta_ce0),
    .top_clusters_eta_q0(top_clusters_eta_q0),
    .top_clusters_phi_address0(grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_top_clusters_phi_address0),
    .top_clusters_phi_ce0(grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_top_clusters_phi_ce0),
    .top_clusters_phi_q0(top_clusters_phi_q0),
    .top_clusters_window_size_address0(grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_top_clusters_window_size_address0),
    .top_clusters_window_size_ce0(grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_top_clusters_window_size_ce0),
    .top_clusters_window_size_q0(top_clusters_window_size_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_calo_trigger_ref_Pipeline_VITIS_LOOP_145_1_VITIS_LOOP_146_2_fu_178_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_calo_trigger_ref_Pipeline_VITIS_LOOP_145_1_VITIS_LOOP_146_2_fu_178_ap_start_reg <= 1'b1;
        end else if ((grp_calo_trigger_ref_Pipeline_VITIS_LOOP_145_1_VITIS_LOOP_146_2_fu_178_ap_ready == 1'b1)) begin
            grp_calo_trigger_ref_Pipeline_VITIS_LOOP_145_1_VITIS_LOOP_146_2_fu_178_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_ap_start_reg <= 1'b1;
        end else if ((grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_ap_ready == 1'b1)) begin
            grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_find_clusters_3_5_s_fu_134_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_find_clusters_3_5_s_fu_134_ap_start_reg <= 1'b1;
        end else if ((grp_find_clusters_3_5_s_fu_134_ap_ready == 1'b1)) begin
            grp_find_clusters_3_5_s_fu_134_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_select_top_n_fu_159_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_select_top_n_fu_159_ap_start_reg <= 1'b1;
        end else if ((grp_select_top_n_fu_159_ap_ready == 1'b1)) begin
            grp_select_top_n_fu_159_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        local_num_clusters_reg_221 <= grp_find_clusters_3_5_s_fu_134_ap_return;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_find_clusters_3_5_s_fu_134_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state4_on_subcall_done)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        clusters_et_address0 = grp_select_top_n_fu_159_clusters_et_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        clusters_et_address0 = grp_find_clusters_3_5_s_fu_134_clusters_et_address0;
    end else begin
        clusters_et_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        clusters_et_ce0 = grp_select_top_n_fu_159_clusters_et_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        clusters_et_ce0 = grp_find_clusters_3_5_s_fu_134_clusters_et_ce0;
    end else begin
        clusters_et_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        clusters_et_we0 = grp_find_clusters_3_5_s_fu_134_clusters_et_we0;
    end else begin
        clusters_et_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        clusters_eta_address0 = grp_select_top_n_fu_159_clusters_eta_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        clusters_eta_address0 = grp_find_clusters_3_5_s_fu_134_clusters_eta_address0;
    end else begin
        clusters_eta_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        clusters_eta_ce0 = grp_select_top_n_fu_159_clusters_eta_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        clusters_eta_ce0 = grp_find_clusters_3_5_s_fu_134_clusters_eta_ce0;
    end else begin
        clusters_eta_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        clusters_eta_we0 = grp_find_clusters_3_5_s_fu_134_clusters_eta_we0;
    end else begin
        clusters_eta_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        clusters_iso_outer_size_address0 = grp_select_top_n_fu_159_clusters_iso_outer_size_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        clusters_iso_outer_size_address0 = grp_find_clusters_3_5_s_fu_134_clusters_iso_outer_size_address0;
    end else begin
        clusters_iso_outer_size_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        clusters_iso_outer_size_ce0 = grp_select_top_n_fu_159_clusters_iso_outer_size_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        clusters_iso_outer_size_ce0 = grp_find_clusters_3_5_s_fu_134_clusters_iso_outer_size_ce0;
    end else begin
        clusters_iso_outer_size_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        clusters_iso_outer_size_we0 = grp_find_clusters_3_5_s_fu_134_clusters_iso_outer_size_we0;
    end else begin
        clusters_iso_outer_size_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        clusters_isolation_et_address0 = grp_select_top_n_fu_159_clusters_isolation_et_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        clusters_isolation_et_address0 = grp_find_clusters_3_5_s_fu_134_clusters_isolation_et_address0;
    end else begin
        clusters_isolation_et_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        clusters_isolation_et_ce0 = grp_select_top_n_fu_159_clusters_isolation_et_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        clusters_isolation_et_ce0 = grp_find_clusters_3_5_s_fu_134_clusters_isolation_et_ce0;
    end else begin
        clusters_isolation_et_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        clusters_isolation_et_we0 = grp_find_clusters_3_5_s_fu_134_clusters_isolation_et_we0;
    end else begin
        clusters_isolation_et_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        clusters_phi_address0 = grp_select_top_n_fu_159_clusters_phi_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        clusters_phi_address0 = grp_find_clusters_3_5_s_fu_134_clusters_phi_address0;
    end else begin
        clusters_phi_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        clusters_phi_ce0 = grp_select_top_n_fu_159_clusters_phi_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        clusters_phi_ce0 = grp_find_clusters_3_5_s_fu_134_clusters_phi_ce0;
    end else begin
        clusters_phi_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        clusters_phi_we0 = grp_find_clusters_3_5_s_fu_134_clusters_phi_we0;
    end else begin
        clusters_phi_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        clusters_valid_address0 = grp_select_top_n_fu_159_clusters_valid_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        clusters_valid_address0 = grp_find_clusters_3_5_s_fu_134_clusters_valid_address0;
    end else begin
        clusters_valid_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        clusters_valid_ce0 = grp_select_top_n_fu_159_clusters_valid_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        clusters_valid_ce0 = grp_find_clusters_3_5_s_fu_134_clusters_valid_ce0;
    end else begin
        clusters_valid_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        clusters_valid_we0 = grp_find_clusters_3_5_s_fu_134_clusters_valid_we0;
    end else begin
        clusters_valid_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        clusters_window_size_address0 = grp_select_top_n_fu_159_clusters_window_size_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        clusters_window_size_address0 = grp_find_clusters_3_5_s_fu_134_clusters_window_size_address0;
    end else begin
        clusters_window_size_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        clusters_window_size_ce0 = grp_select_top_n_fu_159_clusters_window_size_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        clusters_window_size_ce0 = grp_find_clusters_3_5_s_fu_134_clusters_window_size_ce0;
    end else begin
        clusters_window_size_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        clusters_window_size_we0 = grp_find_clusters_3_5_s_fu_134_clusters_window_size_we0;
    end else begin
        clusters_window_size_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grid_address0 = grp_calo_trigger_ref_Pipeline_VITIS_LOOP_145_1_VITIS_LOOP_146_2_fu_178_grid_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_address0 = grp_find_clusters_3_5_s_fu_134_grid_address0;
    end else begin
        grid_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grid_ce0 = grp_calo_trigger_ref_Pipeline_VITIS_LOOP_145_1_VITIS_LOOP_146_2_fu_178_grid_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_ce0 = grp_find_clusters_3_5_s_fu_134_grid_ce0;
    end else begin
        grid_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_ce1 = grp_find_clusters_3_5_s_fu_134_grid_ce1;
    end else begin
        grid_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        ht_ap_vld = 1'b1;
    end else begin
        ht_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_find_clusters_3_5_s_fu_134_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        num_clusters_ap_vld = 1'b1;
    end else begin
        num_clusters_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        top_clusters_et_address0 = grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_top_clusters_et_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        top_clusters_et_address0 = grp_select_top_n_fu_159_top_clusters_et_address0;
    end else begin
        top_clusters_et_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        top_clusters_et_ce0 = grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_top_clusters_et_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        top_clusters_et_ce0 = grp_select_top_n_fu_159_top_clusters_et_ce0;
    end else begin
        top_clusters_et_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        top_clusters_et_ce1 = grp_select_top_n_fu_159_top_clusters_et_ce1;
    end else begin
        top_clusters_et_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        top_clusters_et_we0 = grp_select_top_n_fu_159_top_clusters_et_we0;
    end else begin
        top_clusters_et_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        top_clusters_eta_address0 = grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_top_clusters_eta_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        top_clusters_eta_address0 = grp_select_top_n_fu_159_top_clusters_eta_address0;
    end else begin
        top_clusters_eta_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        top_clusters_eta_ce0 = grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_top_clusters_eta_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        top_clusters_eta_ce0 = grp_select_top_n_fu_159_top_clusters_eta_ce0;
    end else begin
        top_clusters_eta_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        top_clusters_eta_ce1 = grp_select_top_n_fu_159_top_clusters_eta_ce1;
    end else begin
        top_clusters_eta_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        top_clusters_eta_we0 = grp_select_top_n_fu_159_top_clusters_eta_we0;
    end else begin
        top_clusters_eta_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        top_clusters_isolation_et_address0 = grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_top_clusters_isolation_et_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        top_clusters_isolation_et_address0 = grp_select_top_n_fu_159_top_clusters_isolation_et_address0;
    end else begin
        top_clusters_isolation_et_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        top_clusters_isolation_et_ce0 = grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_top_clusters_isolation_et_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        top_clusters_isolation_et_ce0 = grp_select_top_n_fu_159_top_clusters_isolation_et_ce0;
    end else begin
        top_clusters_isolation_et_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        top_clusters_isolation_et_ce1 = grp_select_top_n_fu_159_top_clusters_isolation_et_ce1;
    end else begin
        top_clusters_isolation_et_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        top_clusters_isolation_et_we0 = grp_select_top_n_fu_159_top_clusters_isolation_et_we0;
    end else begin
        top_clusters_isolation_et_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        top_clusters_phi_address0 = grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_top_clusters_phi_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        top_clusters_phi_address0 = grp_select_top_n_fu_159_top_clusters_phi_address0;
    end else begin
        top_clusters_phi_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        top_clusters_phi_ce0 = grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_top_clusters_phi_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        top_clusters_phi_ce0 = grp_select_top_n_fu_159_top_clusters_phi_ce0;
    end else begin
        top_clusters_phi_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        top_clusters_phi_ce1 = grp_select_top_n_fu_159_top_clusters_phi_ce1;
    end else begin
        top_clusters_phi_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        top_clusters_phi_we0 = grp_select_top_n_fu_159_top_clusters_phi_we0;
    end else begin
        top_clusters_phi_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        top_clusters_valid_address0 = grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_top_clusters_valid_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        top_clusters_valid_address0 = grp_select_top_n_fu_159_top_clusters_valid_address0;
    end else begin
        top_clusters_valid_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        top_clusters_valid_ce0 = grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_top_clusters_valid_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        top_clusters_valid_ce0 = grp_select_top_n_fu_159_top_clusters_valid_ce0;
    end else begin
        top_clusters_valid_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        top_clusters_valid_ce1 = grp_select_top_n_fu_159_top_clusters_valid_ce1;
    end else begin
        top_clusters_valid_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        top_clusters_valid_we0 = grp_select_top_n_fu_159_top_clusters_valid_we0;
    end else begin
        top_clusters_valid_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        top_clusters_window_size_address0 = grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_top_clusters_window_size_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        top_clusters_window_size_address0 = grp_select_top_n_fu_159_top_clusters_window_size_address0;
    end else begin
        top_clusters_window_size_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        top_clusters_window_size_ce0 = grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_top_clusters_window_size_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        top_clusters_window_size_ce0 = grp_select_top_n_fu_159_top_clusters_window_size_ce0;
    end else begin
        top_clusters_window_size_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        top_clusters_window_size_ce1 = grp_select_top_n_fu_159_top_clusters_window_size_ce1;
    end else begin
        top_clusters_window_size_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        top_clusters_window_size_we0 = grp_select_top_n_fu_159_top_clusters_window_size_we0;
    end else begin
        top_clusters_window_size_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_find_clusters_3_5_s_fu_134_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

always @ (*) begin
    ap_block_state4_on_subcall_done = ((grp_calo_trigger_ref_Pipeline_VITIS_LOOP_145_1_VITIS_LOOP_146_2_fu_178_ap_done == 1'b0) | (grp_select_top_n_fu_159_ap_done == 1'b0));
end

assign grid_address1 = grp_find_clusters_3_5_s_fu_134_grid_address1;

assign grp_calo_trigger_ref_Pipeline_VITIS_LOOP_145_1_VITIS_LOOP_146_2_fu_178_ap_start = grp_calo_trigger_ref_Pipeline_VITIS_LOOP_145_1_VITIS_LOOP_146_2_fu_178_ap_start_reg;

assign grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_ap_start = grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_ap_start_reg;

assign grp_find_clusters_3_5_s_fu_134_ap_start = grp_find_clusters_3_5_s_fu_134_ap_start_reg;

assign grp_select_top_n_fu_159_ap_start = grp_select_top_n_fu_159_ap_start_reg;

assign ht = grp_calo_trigger_ref_Pipeline_VITIS_LOOP_145_1_VITIS_LOOP_146_2_fu_178_conv4_i4_i_i_out;

assign num_clusters = grp_find_clusters_3_5_s_fu_134_ap_return;

assign objects_address0 = grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_objects_address0;

assign objects_address1 = grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_objects_address1;

assign objects_ce0 = grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_objects_ce0;

assign objects_ce1 = grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_objects_ce1;

assign objects_d0 = grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_objects_d0;

assign objects_d1 = grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_objects_d1;

assign objects_we0 = grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_objects_we0;

assign objects_we1 = grp_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1_fu_185_objects_we1;

endmodule //calo_trigger_ref
