// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module calo_trigger_ref_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        objects_address0,
        objects_ce0,
        objects_we0,
        objects_d0,
        objects_address1,
        objects_ce1,
        objects_we1,
        objects_d1,
        top_clusters_valid_address0,
        top_clusters_valid_ce0,
        top_clusters_valid_q0,
        top_clusters_et_address0,
        top_clusters_et_ce0,
        top_clusters_et_q0,
        top_clusters_isolation_et_address0,
        top_clusters_isolation_et_ce0,
        top_clusters_isolation_et_q0,
        top_clusters_eta_address0,
        top_clusters_eta_ce0,
        top_clusters_eta_q0,
        top_clusters_phi_address0,
        top_clusters_phi_ce0,
        top_clusters_phi_q0,
        top_clusters_window_size_address0,
        top_clusters_window_size_ce0,
        top_clusters_window_size_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [2:0] objects_address0;
output   objects_ce0;
output   objects_we0;
output  [88:0] objects_d0;
output  [2:0] objects_address1;
output   objects_ce1;
output   objects_we1;
output  [88:0] objects_d1;
output  [2:0] top_clusters_valid_address0;
output   top_clusters_valid_ce0;
input  [0:0] top_clusters_valid_q0;
output  [2:0] top_clusters_et_address0;
output   top_clusters_et_ce0;
input  [15:0] top_clusters_et_q0;
output  [2:0] top_clusters_isolation_et_address0;
output   top_clusters_isolation_et_ce0;
input  [17:0] top_clusters_isolation_et_q0;
output  [2:0] top_clusters_eta_address0;
output   top_clusters_eta_ce0;
input  [4:0] top_clusters_eta_q0;
output  [2:0] top_clusters_phi_address0;
output   top_clusters_phi_ce0;
input  [5:0] top_clusters_phi_q0;
output  [2:0] top_clusters_window_size_address0;
output   top_clusters_window_size_ce0;
input  [1:0] top_clusters_window_size_q0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln156_fu_166_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln156_fu_178_p1;
reg   [63:0] zext_ln156_reg_259;
reg   [2:0] objects_addr_reg_268;
reg   [2:0] objects_addr_reg_268_pp0_iter1_reg;
reg   [0:0] top_clusters_valid_load_reg_278;
wire    ap_block_pp0_stage0;
reg   [3:0] i_fu_58;
wire   [3:0] add_ln156_fu_172_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_i_2;
reg    objects_we1_local;
reg    objects_ce1_local;
reg    objects_we0_local;
wire   [88:0] or_ln1_fu_239_p3;
reg    objects_ce0_local;
reg    top_clusters_valid_ce0_local;
reg    top_clusters_et_ce0_local;
reg    top_clusters_isolation_et_ce0_local;
reg    top_clusters_eta_ce0_local;
reg    top_clusters_phi_ce0_local;
reg    top_clusters_window_size_ce0_local;
wire   [0:0] icmp_ln177_fu_205_p2;
wire   [1:0] select_ln177_fu_211_p3;
wire   [3:0] zext_ln177_fu_201_p1;
wire   [5:0] zext_ln172_fu_197_p1;
wire  signed [19:0] sext_ln171_fu_193_p1;
wire   [19:0] zext_ln170_fu_189_p1;
wire   [57:0] or_ln_fu_219_p7;
wire   [87:0] zext_ln183_fu_235_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 i_fu_58 = 4'd0;
#0 ap_done_reg = 1'b0;
end

calo_trigger_ref_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln156_fu_166_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_58 <= add_ln156_fu_172_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_58 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        objects_addr_reg_268 <= zext_ln156_fu_178_p1;
        objects_addr_reg_268_pp0_iter1_reg <= objects_addr_reg_268;
        top_clusters_valid_load_reg_278 <= top_clusters_valid_q0;
        zext_ln156_reg_259[3 : 0] <= zext_ln156_fu_178_p1[3 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln156_fu_166_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_2 = 4'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_58;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        objects_ce0_local = 1'b1;
    end else begin
        objects_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        objects_ce1_local = 1'b1;
    end else begin
        objects_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (top_clusters_valid_load_reg_278 == 1'd1))) begin
        objects_we0_local = 1'b1;
    end else begin
        objects_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln156_fu_166_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        objects_we1_local = 1'b1;
    end else begin
        objects_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        top_clusters_et_ce0_local = 1'b1;
    end else begin
        top_clusters_et_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        top_clusters_eta_ce0_local = 1'b1;
    end else begin
        top_clusters_eta_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        top_clusters_isolation_et_ce0_local = 1'b1;
    end else begin
        top_clusters_isolation_et_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        top_clusters_phi_ce0_local = 1'b1;
    end else begin
        top_clusters_phi_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        top_clusters_valid_ce0_local = 1'b1;
    end else begin
        top_clusters_valid_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        top_clusters_window_size_ce0_local = 1'b1;
    end else begin
        top_clusters_window_size_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln156_fu_172_p2 = (ap_sig_allocacmp_i_2 + 4'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln156_fu_166_p2 = ((ap_sig_allocacmp_i_2 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln177_fu_205_p2 = ((top_clusters_window_size_q0 == 2'd3) ? 1'b1 : 1'b0);

assign objects_address0 = objects_addr_reg_268_pp0_iter1_reg;

assign objects_address1 = zext_ln156_fu_178_p1;

assign objects_ce0 = objects_ce0_local;

assign objects_ce1 = objects_ce1_local;

assign objects_d0 = or_ln1_fu_239_p3;

assign objects_d1 = 89'd0;

assign objects_we0 = objects_we0_local;

assign objects_we1 = objects_we1_local;

assign or_ln1_fu_239_p3 = {{1'd1}, {zext_ln183_fu_235_p1}};

assign or_ln_fu_219_p7 = {{{{{{select_ln177_fu_211_p3}, {zext_ln177_fu_201_p1}}, {top_clusters_phi_q0}}, {zext_ln172_fu_197_p1}}, {sext_ln171_fu_193_p1}}, {zext_ln170_fu_189_p1}};

assign select_ln177_fu_211_p3 = ((icmp_ln177_fu_205_p2[0:0] == 1'b1) ? 2'd1 : 2'd2);

assign sext_ln171_fu_193_p1 = $signed(top_clusters_isolation_et_q0);

assign top_clusters_et_address0 = zext_ln156_reg_259;

assign top_clusters_et_ce0 = top_clusters_et_ce0_local;

assign top_clusters_eta_address0 = zext_ln156_reg_259;

assign top_clusters_eta_ce0 = top_clusters_eta_ce0_local;

assign top_clusters_isolation_et_address0 = zext_ln156_reg_259;

assign top_clusters_isolation_et_ce0 = top_clusters_isolation_et_ce0_local;

assign top_clusters_phi_address0 = zext_ln156_reg_259;

assign top_clusters_phi_ce0 = top_clusters_phi_ce0_local;

assign top_clusters_valid_address0 = zext_ln156_fu_178_p1;

assign top_clusters_valid_ce0 = top_clusters_valid_ce0_local;

assign top_clusters_window_size_address0 = zext_ln156_reg_259;

assign top_clusters_window_size_ce0 = top_clusters_window_size_ce0_local;

assign zext_ln156_fu_178_p1 = ap_sig_allocacmp_i_2;

assign zext_ln170_fu_189_p1 = top_clusters_et_q0;

assign zext_ln172_fu_197_p1 = top_clusters_eta_q0;

assign zext_ln177_fu_201_p1 = top_clusters_window_size_q0;

assign zext_ln183_fu_235_p1 = or_ln_fu_219_p7;

always @ (posedge ap_clk) begin
    zext_ln156_reg_259[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
end

endmodule //calo_trigger_ref_calo_trigger_ref_Pipeline_VITIS_LOOP_156_1
