// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module calo_trigger_ref_find_clusters_3_5_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        grid_Addr_A,
        grid_EN_A,
        grid_WEN_A,
        grid_Din_A,
        grid_Dout_A,
        grid_Addr_B,
        grid_EN_B,
        grid_WEN_B,
        grid_Din_B,
        grid_Dout_B,
        seed_threshold,
        cluster_threshold,
        clusters_et_address0,
        clusters_et_ce0,
        clusters_et_we0,
        clusters_et_d0,
        clusters_isolation_et_address0,
        clusters_isolation_et_ce0,
        clusters_isolation_et_we0,
        clusters_isolation_et_d0,
        clusters_eta_address0,
        clusters_eta_ce0,
        clusters_eta_we0,
        clusters_eta_d0,
        clusters_phi_address0,
        clusters_phi_ce0,
        clusters_phi_we0,
        clusters_phi_d0,
        clusters_window_size_address0,
        clusters_window_size_ce0,
        clusters_window_size_we0,
        clusters_window_size_d0,
        clusters_iso_outer_size_address0,
        clusters_iso_outer_size_ce0,
        clusters_iso_outer_size_we0,
        clusters_iso_outer_size_d0,
        clusters_valid_address0,
        clusters_valid_ce0,
        clusters_valid_we0,
        clusters_valid_d0,
        ap_return
);

parameter    ap_ST_fsm_pp0_stage0 = 13'd1;
parameter    ap_ST_fsm_pp0_stage1 = 13'd2;
parameter    ap_ST_fsm_pp0_stage2 = 13'd4;
parameter    ap_ST_fsm_pp0_stage3 = 13'd8;
parameter    ap_ST_fsm_pp0_stage4 = 13'd16;
parameter    ap_ST_fsm_pp0_stage5 = 13'd32;
parameter    ap_ST_fsm_pp0_stage6 = 13'd64;
parameter    ap_ST_fsm_pp0_stage7 = 13'd128;
parameter    ap_ST_fsm_pp0_stage8 = 13'd256;
parameter    ap_ST_fsm_pp0_stage9 = 13'd512;
parameter    ap_ST_fsm_pp0_stage10 = 13'd1024;
parameter    ap_ST_fsm_pp0_stage11 = 13'd2048;
parameter    ap_ST_fsm_pp0_stage12 = 13'd4096;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] grid_Addr_A;
output   grid_EN_A;
output  [1:0] grid_WEN_A;
output  [15:0] grid_Din_A;
input  [15:0] grid_Dout_A;
output  [31:0] grid_Addr_B;
output   grid_EN_B;
output  [1:0] grid_WEN_B;
output  [15:0] grid_Din_B;
input  [15:0] grid_Dout_B;
input  [11:0] seed_threshold;
input  [19:0] cluster_threshold;
output  [10:0] clusters_et_address0;
output   clusters_et_ce0;
output   clusters_et_we0;
output  [15:0] clusters_et_d0;
output  [10:0] clusters_isolation_et_address0;
output   clusters_isolation_et_ce0;
output   clusters_isolation_et_we0;
output  [15:0] clusters_isolation_et_d0;
output  [10:0] clusters_eta_address0;
output   clusters_eta_ce0;
output   clusters_eta_we0;
output  [4:0] clusters_eta_d0;
output  [10:0] clusters_phi_address0;
output   clusters_phi_ce0;
output   clusters_phi_we0;
output  [5:0] clusters_phi_d0;
output  [10:0] clusters_window_size_address0;
output   clusters_window_size_ce0;
output   clusters_window_size_we0;
output  [0:0] clusters_window_size_d0;
output  [10:0] clusters_iso_outer_size_address0;
output   clusters_iso_outer_size_ce0;
output   clusters_iso_outer_size_we0;
output  [2:0] clusters_iso_outer_size_d0;
output  [10:0] clusters_valid_address0;
output   clusters_valid_ce0;
output   clusters_valid_we0;
output  [0:0] clusters_valid_d0;
output  [31:0] ap_return;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [12:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_pp0_stage6_subdone;
reg   [0:0] icmp_ln232_reg_1621;
reg    ap_condition_exit_pp0_iter0_stage6;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage12;
wire    ap_block_pp0_stage12_subdone;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln232_fu_473_p2;
wire   [5:0] select_ln232_fu_497_p3;
reg   [5:0] select_ln232_reg_1625;
wire   [4:0] select_ln232_1_fu_517_p3;
reg   [4:0] select_ln232_1_reg_1633;
wire   [4:0] select_ln232_2_fu_525_p3;
reg   [4:0] select_ln232_2_reg_1639;
wire   [10:0] sub_ln235_fu_553_p2;
reg   [10:0] sub_ln235_reg_1647;
wire   [10:0] zext_ln235_1_fu_559_p1;
reg   [10:0] zext_ln235_1_reg_1655;
wire   [10:0] sub_ln188_fu_609_p2;
reg   [10:0] sub_ln188_reg_1668;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
wire   [6:0] zext_ln233_fu_625_p1;
reg   [6:0] zext_ln233_reg_1681;
reg   [11:0] center_et_reg_1689;
wire   [0:0] icmp_ln237_fu_628_p2;
reg   [0:0] icmp_ln237_reg_1702;
reg   [0:0] icmp_ln237_reg_1702_pp0_iter1_reg;
wire   [7:0] phi_idx_3_fu_684_p3;
reg   [7:0] phi_idx_3_reg_1711;
wire   [0:0] grp_fu_440_p2;
reg   [0:0] is_max_reg_1716;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
reg   [11:0] neighbor_1_reg_1721;
wire  signed [10:0] sext_ln188_fu_720_p1;
reg  signed [10:0] sext_ln188_reg_1728;
wire  signed [10:0] sext_ln188_1_fu_734_p1;
reg  signed [10:0] sext_ln188_1_reg_1741;
wire   [10:0] sub_ln188_1_fu_770_p2;
reg   [10:0] sub_ln188_1_reg_1754;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_11001;
reg   [11:0] neighbor_2_reg_1767;
reg   [11:0] neighbor_3_reg_1777;
wire   [0:0] and_ln190_2_fu_820_p2;
reg   [0:0] and_ln190_2_reg_1783;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4_11001;
reg   [11:0] neighbor_4_reg_1798;
reg   [11:0] neighbor_5_reg_1804;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_pp0_stage5_11001;
wire   [0:0] or_ln190_fu_922_p2;
reg   [0:0] or_ln190_reg_1815;
reg   [0:0] or_ln190_reg_1815_pp0_iter1_reg;
wire   [13:0] add_ln159_2_fu_968_p2;
reg   [13:0] add_ln159_2_reg_1819;
wire   [12:0] add_ln159_3_fu_974_p2;
reg   [12:0] add_ln159_3_reg_1824;
wire   [10:0] sub_ln159_fu_1008_p2;
reg   [10:0] sub_ln159_reg_1829;
wire    ap_block_pp0_stage6_11001;
wire   [0:0] icmp_ln248_fu_1081_p2;
reg   [0:0] icmp_ln248_reg_1841;
wire   [6:0] phi_idx_5_fu_1151_p3;
reg   [6:0] phi_idx_5_reg_1850;
wire   [7:0] phi_idx_6_fu_1163_p3;
reg   [7:0] phi_idx_6_reg_1855;
wire   [0:0] icmp_ln257_fu_1171_p2;
reg   [0:0] icmp_ln257_reg_1860;
wire   [63:0] zext_ln258_fu_1177_p1;
reg   [63:0] zext_ln258_reg_1864;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_pp0_stage7_11001;
wire   [12:0] add_ln211_fu_1229_p2;
reg   [12:0] add_ln211_reg_1879;
wire  signed [10:0] sext_ln159_fu_1243_p1;
reg  signed [10:0] sext_ln159_reg_1884;
wire    ap_CS_fsm_pp0_stage8;
wire    ap_block_pp0_stage8_11001;
wire  signed [10:0] sext_ln159_1_fu_1256_p1;
reg  signed [10:0] sext_ln159_1_reg_1897;
wire   [13:0] add_ln211_2_fu_1282_p2;
reg   [13:0] add_ln211_2_reg_1909;
wire    ap_CS_fsm_pp0_stage9;
wire    ap_block_pp0_stage9_11001;
wire   [12:0] add_ln211_3_fu_1314_p2;
reg   [12:0] add_ln211_3_reg_1924;
reg   [10:0] grid_addr_23_reg_1929;
wire    ap_CS_fsm_pp0_stage10;
wire    ap_block_pp0_stage10_11001;
reg   [10:0] grid_addr_24_reg_1934;
reg   [10:0] grid_addr_22_reg_1939;
wire   [10:0] add_ln159_19_fu_1390_p2;
reg   [10:0] add_ln159_19_reg_1949;
wire   [10:0] add_ln159_20_fu_1394_p2;
reg   [10:0] add_ln159_20_reg_1954;
wire   [10:0] add_ln159_24_fu_1408_p2;
reg   [10:0] add_ln159_24_reg_1964;
wire   [14:0] add_ln211_6_fu_1447_p2;
reg   [14:0] add_ln211_6_reg_1969;
wire    ap_CS_fsm_pp0_stage11;
wire    ap_block_pp0_stage11_11001;
wire   [12:0] add_ln211_7_fu_1469_p2;
reg   [12:0] add_ln211_7_reg_1984;
wire   [13:0] add_ln211_9_fu_1496_p2;
reg   [13:0] add_ln211_9_reg_1989;
wire    ap_block_pp0_stage12_11001;
wire   [12:0] add_ln211_10_fu_1510_p2;
reg   [12:0] add_ln211_10_reg_1994;
reg   [11:0] grid_load_15_reg_1999;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [63:0] zext_ln235_2_fu_569_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln188_2_fu_620_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln188_5_fu_675_p1;
wire   [63:0] zext_ln188_6_fu_729_p1;
wire    ap_block_pp0_stage2;
wire   [63:0] zext_ln188_9_fu_742_p1;
wire   [63:0] zext_ln188_7_fu_794_p1;
wire    ap_block_pp0_stage3;
wire   [63:0] zext_ln188_10_fu_804_p1;
wire   [63:0] zext_ln188_3_fu_830_p1;
wire    ap_block_pp0_stage4;
wire   [63:0] zext_ln188_8_fu_839_p1;
wire   [63:0] zext_ln159_28_fu_848_p1;
wire    ap_block_pp0_stage5;
wire   [63:0] zext_ln159_29_fu_1019_p1;
wire    ap_block_pp0_stage6;
wire   [63:0] zext_ln159_32_fu_1126_p1;
wire   [63:0] zext_ln159_24_fu_1207_p1;
wire    ap_block_pp0_stage7;
wire   [63:0] zext_ln159_26_fu_1216_p1;
wire   [63:0] zext_ln159_33_fu_1251_p1;
wire    ap_block_pp0_stage8;
wire   [63:0] zext_ln159_38_fu_1264_p1;
wire   [63:0] zext_ln159_34_fu_1292_p1;
wire    ap_block_pp0_stage9;
wire   [63:0] zext_ln159_39_fu_1305_p1;
wire   [63:0] zext_ln159_25_fu_1356_p1;
wire    ap_block_pp0_stage10;
wire   [63:0] zext_ln159_27_fu_1366_p1;
wire   [63:0] zext_ln159_30_fu_1376_p1;
wire   [63:0] zext_ln159_35_fu_1385_p1;
wire   [63:0] zext_ln159_40_fu_1403_p1;
wire   [63:0] zext_ln159_36_fu_1453_p1;
wire    ap_block_pp0_stage11;
wire   [63:0] zext_ln159_41_fu_1457_p1;
wire   [63:0] zext_ln159_37_fu_1516_p1;
reg   [5:0] phi_idx_1_fu_100;
wire   [5:0] phi_fu_692_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_phi_idx_1_load;
reg   [4:0] eta_fu_104;
reg   [4:0] ap_sig_allocacmp_eta_load;
reg   [10:0] indvar_flatten_fu_108;
wire   [10:0] add_ln232_1_fu_479_p2;
reg   [10:0] ap_sig_allocacmp_indvar_flatten_load;
reg   [31:0] empty_fu_112;
wire   [31:0] add_ln265_fu_1187_p2;
reg   [31:0] inc347_fu_116;
reg    grid_EN_B_local;
reg   [31:0] grid_Addr_B_orig;
reg    grid_EN_A_local;
reg   [31:0] grid_Addr_A_orig;
wire    ap_block_pp0_stage12;
reg    clusters_et_we0_local;
wire   [15:0] cluster_et_fu_1070_p2;
reg    clusters_et_ce0_local;
reg    clusters_eta_we0_local;
reg    clusters_eta_ce0_local;
reg    clusters_phi_we0_local;
reg    clusters_phi_ce0_local;
reg    clusters_window_size_we0_local;
reg    clusters_window_size_ce0_local;
reg    clusters_iso_outer_size_we0_local;
reg    clusters_iso_outer_size_ce0_local;
reg    clusters_valid_we0_local;
reg    clusters_valid_ce0_local;
reg    clusters_isolation_et_we0_local;
wire   [15:0] isolation_et_fu_1566_p2;
reg    clusters_isolation_et_ce0_local;
wire   [11:0] grp_fu_440_p0;
wire   [0:0] icmp_ln233_fu_491_p2;
wire   [4:0] add_ln232_fu_505_p2;
wire   [4:0] add_ln232_2_fu_511_p2;
wire   [6:0] tmp_fu_541_p3;
wire   [10:0] p_shl1_fu_533_p3;
wire   [10:0] zext_ln235_fu_549_p1;
wire   [10:0] add_ln235_fu_563_p2;
wire   [4:0] empty_61_fu_584_p2;
wire   [6:0] tmp_1_fu_597_p3;
wire   [10:0] p_shl2_fu_589_p3;
wire   [10:0] zext_ln188_fu_605_p1;
wire   [10:0] add_ln188_fu_615_p2;
wire   [11:0] icmp_ln237_fu_628_p0;
wire  signed [6:0] add_ln185_fu_633_p2;
wire   [0:0] tmp_5_fu_643_p3;
wire   [6:0] add_ln133_fu_651_p2;
wire   [6:0] phi_idx_fu_657_p3;
wire   [10:0] zext_ln188_4_fu_665_p1;
wire   [10:0] add_ln188_2_fu_669_p2;
wire   [7:0] zext_ln132_fu_680_p1;
wire  signed [7:0] sext_ln130_fu_639_p1;
wire   [0:0] icmp_ln134_fu_697_p2;
wire   [6:0] add_ln135_fu_703_p2;
wire   [6:0] zext_ln134_fu_708_p1;
wire   [6:0] phi_idx_2_fu_712_p3;
wire   [10:0] add_ln188_3_fu_724_p2;
wire   [10:0] add_ln188_6_fu_737_p2;
wire   [6:0] tmp_2_fu_759_p3;
wire   [10:0] p_shl3_fu_752_p3;
wire   [10:0] zext_ln188_1_fu_766_p1;
wire   [0:0] icmp_ln190_fu_780_p2;
wire   [10:0] add_ln188_4_fu_790_p2;
wire   [10:0] add_ln188_7_fu_799_p2;
wire   [0:0] icmp_ln192_fu_776_p2;
wire   [0:0] xor_ln190_1_fu_784_p2;
wire   [0:0] and_ln190_1_fu_814_p2;
wire   [0:0] and_ln190_fu_809_p2;
wire   [10:0] add_ln188_1_fu_826_p2;
wire   [10:0] add_ln188_5_fu_835_p2;
wire   [10:0] add_ln159_11_fu_844_p2;
wire   [0:0] icmp_ln190_1_fu_853_p2;
wire   [0:0] icmp_ln190_2_fu_863_p2;
wire   [11:0] icmp_ln190_3_fu_873_p1;
wire   [0:0] icmp_ln190_3_fu_873_p2;
wire   [0:0] xor_ln190_3_fu_867_p2;
wire   [0:0] xor_ln190_4_fu_878_p2;
wire   [0:0] xor_ln190_2_fu_857_p2;
wire   [0:0] icmp_ln190_5_fu_884_p2;
wire   [0:0] and_ln190_5_fu_894_p2;
wire   [0:0] and_ln190_4_fu_888_p2;
wire   [0:0] and_ln190_6_fu_900_p2;
wire   [11:0] icmp_ln190_6_fu_911_p0;
wire   [0:0] and_ln190_3_fu_906_p2;
wire   [0:0] icmp_ln190_6_fu_911_p2;
wire   [0:0] xor_ln190_fu_916_p2;
wire   [11:0] zext_ln159_5_fu_940_p0;
wire   [11:0] zext_ln159_6_fu_944_p0;
wire   [12:0] zext_ln159_5_fu_940_p1;
wire   [12:0] zext_ln159_6_fu_944_p1;
wire   [12:0] add_ln159_fu_948_p2;
wire   [12:0] zext_ln159_4_fu_937_p1;
wire   [12:0] zext_ln159_3_fu_934_p1;
wire   [12:0] add_ln159_1_fu_958_p2;
wire   [13:0] zext_ln159_8_fu_964_p1;
wire   [13:0] zext_ln159_7_fu_954_p1;
wire   [12:0] zext_ln159_2_fu_931_p1;
wire   [12:0] zext_ln156_fu_928_p1;
wire   [4:0] empty_62_fu_983_p2;
wire   [6:0] tmp_3_fu_996_p3;
wire   [10:0] p_shl4_fu_988_p3;
wire   [10:0] zext_ln159_9_fu_1004_p1;
wire   [10:0] add_ln159_12_fu_1014_p2;
wire   [11:0] zext_ln159_fu_1024_p0;
wire   [12:0] zext_ln155_fu_1028_p1;
wire   [12:0] zext_ln159_fu_1024_p1;
wire   [12:0] add_ln159_4_fu_1040_p2;
wire   [13:0] zext_ln159_12_fu_1046_p1;
wire   [13:0] zext_ln159_1_fu_1031_p1;
wire   [13:0] add_ln159_5_fu_1050_p2;
wire   [14:0] zext_ln159_13_fu_1056_p1;
wire   [14:0] zext_ln159_11_fu_1037_p1;
wire   [14:0] add_ln159_6_fu_1060_p2;
wire   [15:0] zext_ln159_14_fu_1066_p1;
wire   [15:0] zext_ln159_10_fu_1034_p1;
wire   [19:0] zext_ln246_fu_1077_p1;
wire  signed [6:0] add_ln156_fu_1086_p2;
wire   [0:0] tmp_6_fu_1095_p3;
wire   [6:0] add_ln133_1_fu_1103_p2;
wire   [6:0] phi_idx_4_fu_1108_p3;
wire   [10:0] zext_ln159_31_fu_1116_p1;
wire   [10:0] add_ln159_15_fu_1120_p2;
wire   [5:0] add_ln156_1_fu_1131_p2;
wire   [0:0] icmp_ln134_1_fu_1136_p2;
wire   [6:0] add_ln135_1_fu_1142_p2;
wire   [6:0] zext_ln134_1_fu_1147_p1;
wire   [7:0] zext_ln132_1_fu_1159_p1;
wire  signed [7:0] sext_ln130_1_fu_1091_p1;
wire   [10:0] add_ln159_7_fu_1203_p2;
wire   [10:0] add_ln159_9_fu_1212_p2;
wire   [11:0] zext_ln146_fu_1221_p0;
wire   [11:0] zext_ln130_fu_1225_p0;
wire   [12:0] zext_ln130_fu_1225_p1;
wire   [12:0] zext_ln146_fu_1221_p1;
wire   [11:0] zext_ln156_1_fu_1235_p0;
wire   [11:0] zext_ln156_2_fu_1239_p0;
wire   [10:0] add_ln159_16_fu_1246_p2;
wire   [10:0] add_ln159_21_fu_1259_p2;
wire   [12:0] zext_ln156_1_fu_1235_p1;
wire   [12:0] zext_ln156_2_fu_1239_p1;
wire   [12:0] add_ln211_1_fu_1272_p2;
wire   [13:0] zext_ln211_1_fu_1278_p1;
wire   [13:0] zext_ln211_fu_1269_p1;
wire   [10:0] add_ln159_17_fu_1288_p2;
wire   [11:0] zext_ln133_fu_1297_p0;
wire   [10:0] add_ln159_22_fu_1301_p2;
wire   [11:0] zext_ln146_1_fu_1310_p0;
wire   [12:0] zext_ln133_fu_1297_p1;
wire   [12:0] zext_ln146_1_fu_1310_p1;
wire   [4:0] empty_63_fu_1320_p2;
wire   [6:0] tmp_4_fu_1333_p3;
wire   [10:0] p_shl_fu_1325_p3;
wire   [10:0] zext_ln159_23_fu_1341_p1;
wire   [10:0] sub_ln159_1_fu_1345_p2;
wire   [10:0] add_ln159_8_fu_1351_p2;
wire   [10:0] add_ln159_10_fu_1361_p2;
wire   [10:0] add_ln159_13_fu_1371_p2;
wire   [10:0] add_ln159_18_fu_1381_p2;
wire   [10:0] add_ln159_23_fu_1399_p2;
wire   [11:0] zext_ln155_1_fu_1413_p0;
wire   [11:0] zext_ln159_15_fu_1417_p0;
wire   [12:0] zext_ln155_1_fu_1413_p1;
wire   [12:0] zext_ln159_15_fu_1417_p1;
wire   [12:0] add_ln211_4_fu_1427_p2;
wire   [13:0] zext_ln211_4_fu_1433_p1;
wire   [13:0] zext_ln211_3_fu_1424_p1;
wire   [13:0] add_ln211_5_fu_1437_p2;
wire   [14:0] zext_ln211_5_fu_1443_p1;
wire   [14:0] zext_ln211_2_fu_1421_p1;
wire   [11:0] zext_ln159_16_fu_1461_p0;
wire   [11:0] zext_ln159_17_fu_1465_p0;
wire   [12:0] zext_ln159_16_fu_1461_p1;
wire   [12:0] zext_ln159_17_fu_1465_p1;
wire   [11:0] zext_ln159_18_fu_1475_p0;
wire   [11:0] zext_ln159_19_fu_1479_p0;
wire   [12:0] zext_ln159_18_fu_1475_p1;
wire   [12:0] zext_ln159_19_fu_1479_p1;
wire   [12:0] add_ln211_8_fu_1486_p2;
wire   [13:0] zext_ln211_8_fu_1492_p1;
wire   [13:0] zext_ln211_7_fu_1483_p1;
wire   [11:0] zext_ln159_20_fu_1502_p0;
wire   [11:0] zext_ln159_21_fu_1506_p0;
wire   [12:0] zext_ln159_20_fu_1502_p1;
wire   [12:0] zext_ln159_21_fu_1506_p1;
wire   [11:0] zext_ln143_fu_1523_p0;
wire   [12:0] zext_ln159_22_fu_1520_p1;
wire   [12:0] zext_ln143_fu_1523_p1;
wire   [12:0] add_ln211_11_fu_1536_p2;
wire   [13:0] zext_ln211_11_fu_1542_p1;
wire   [13:0] zext_ln211_10_fu_1533_p1;
wire   [13:0] add_ln211_12_fu_1546_p2;
wire   [14:0] zext_ln211_12_fu_1552_p1;
wire   [14:0] zext_ln211_9_fu_1530_p1;
wire   [14:0] add_ln211_13_fu_1556_p2;
wire   [15:0] zext_ln211_13_fu_1562_p1;
wire   [15:0] zext_ln211_6_fu_1527_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [12:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to1;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage3_subdone;
wire    ap_block_pp0_stage4_subdone;
wire    ap_block_pp0_stage5_subdone;
wire    ap_block_pp0_stage7_subdone;
wire    ap_block_pp0_stage8_subdone;
wire    ap_block_pp0_stage9_subdone;
wire    ap_block_pp0_stage10_subdone;
wire    ap_block_pp0_stage11_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 13'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 phi_idx_1_fu_100 = 6'd0;
#0 eta_fu_104 = 5'd0;
#0 indvar_flatten_fu_108 = 11'd0;
#0 empty_fu_112 = 32'd0;
#0 inc347_fu_116 = 32'd0;
#0 ap_done_reg = 1'b0;
end

calo_trigger_ref_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage6),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage6_subdone) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage6)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage6_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage12_subdone) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_fu_112 <= 32'd0;
    end else if (((icmp_ln232_reg_1621 == 1'd0) & (1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln257_fu_1171_p2 == 1'd1) & (icmp_ln248_fu_1081_p2 == 1'd0) & (or_ln190_reg_1815 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage6) & (icmp_ln237_reg_1702 == 1'd0))) begin
        empty_fu_112 <= add_ln265_fu_1187_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln232_fu_473_p2 == 1'd0))) begin
            eta_fu_104 <= select_ln232_2_fu_525_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            eta_fu_104 <= 5'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inc347_fu_116 <= 32'd0;
    end else if (((icmp_ln232_reg_1621 == 1'd0) & (1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln257_fu_1171_p2 == 1'd1) & (icmp_ln248_fu_1081_p2 == 1'd0) & (or_ln190_reg_1815 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage6) & (icmp_ln237_reg_1702 == 1'd0))) begin
        inc347_fu_116 <= add_ln265_fu_1187_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln232_fu_473_p2 == 1'd0))) begin
            indvar_flatten_fu_108 <= add_ln232_1_fu_479_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_108 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        phi_idx_1_fu_100 <= 6'd0;
    end else if (((icmp_ln232_reg_1621 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        phi_idx_1_fu_100 <= phi_fu_692_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage10_11001) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        add_ln159_19_reg_1949 <= add_ln159_19_fu_1390_p2;
        add_ln159_20_reg_1954 <= add_ln159_20_fu_1394_p2;
        add_ln159_24_reg_1964 <= add_ln159_24_fu_1408_p2;
        add_ln211_6_reg_1969 <= add_ln211_6_fu_1447_p2;
        grid_addr_22_reg_1939 <= zext_ln159_30_fu_1376_p1;
        grid_addr_23_reg_1929 <= zext_ln159_25_fu_1356_p1;
        grid_addr_24_reg_1934 <= zext_ln159_27_fu_1366_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        add_ln159_2_reg_1819 <= add_ln159_2_fu_968_p2;
        add_ln159_3_reg_1824 <= add_ln159_3_fu_974_p2;
        or_ln190_reg_1815 <= or_ln190_fu_922_p2;
        or_ln190_reg_1815_pp0_iter1_reg <= or_ln190_reg_1815;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln211_10_reg_1994 <= add_ln211_10_fu_1510_p2;
        icmp_ln232_reg_1621 <= icmp_ln232_fu_473_p2;
        select_ln232_1_reg_1633 <= select_ln232_1_fu_517_p3;
        select_ln232_2_reg_1639 <= select_ln232_2_fu_525_p3;
        select_ln232_reg_1625 <= select_ln232_fu_497_p3;
        sub_ln235_reg_1647[10 : 2] <= sub_ln235_fu_553_p2[10 : 2];
        zext_ln235_1_reg_1655[5 : 0] <= zext_ln235_1_fu_559_p1[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage8_11001) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        add_ln211_2_reg_1909 <= add_ln211_2_fu_1282_p2;
        sext_ln159_1_reg_1897 <= sext_ln159_1_fu_1256_p1;
        sext_ln159_reg_1884 <= sext_ln159_fu_1243_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        add_ln211_3_reg_1924 <= add_ln211_3_fu_1314_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage11_11001) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        add_ln211_7_reg_1984 <= add_ln211_7_fu_1469_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage12_11001) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        add_ln211_9_reg_1989 <= add_ln211_9_fu_1496_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        add_ln211_reg_1879 <= add_ln211_fu_1229_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        and_ln190_2_reg_1783 <= and_ln190_2_fu_820_p2;
        sub_ln188_1_reg_1754[10 : 2] <= sub_ln188_1_fu_770_p2[10 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        center_et_reg_1689 <= grid_Dout_B;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grid_load_15_reg_1999 <= grid_Dout_A;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        icmp_ln237_reg_1702 <= icmp_ln237_fu_628_p2;
        icmp_ln237_reg_1702_pp0_iter1_reg <= icmp_ln237_reg_1702;
        phi_idx_3_reg_1711 <= phi_idx_3_fu_684_p3;
        sub_ln188_reg_1668[10 : 2] <= sub_ln188_fu_609_p2[10 : 2];
        zext_ln233_reg_1681[5 : 0] <= zext_ln233_fu_625_p1[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        icmp_ln248_reg_1841 <= icmp_ln248_fu_1081_p2;
        icmp_ln257_reg_1860 <= icmp_ln257_fu_1171_p2;
        phi_idx_5_reg_1850 <= phi_idx_5_fu_1151_p3;
        phi_idx_6_reg_1855 <= phi_idx_6_fu_1163_p3;
        sub_ln159_reg_1829[10 : 2] <= sub_ln159_fu_1008_p2[10 : 2];
        zext_ln258_reg_1864[31 : 0] <= zext_ln258_fu_1177_p1[31 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        is_max_reg_1716 <= grp_fu_440_p2;
        neighbor_1_reg_1721 <= grid_Dout_A;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        neighbor_2_reg_1767 <= grid_Dout_B;
        neighbor_3_reg_1777 <= grid_Dout_A;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        neighbor_4_reg_1798 <= grid_Dout_B;
        neighbor_5_reg_1804 <= grid_Dout_A;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        sext_ln188_1_reg_1741 <= sext_ln188_1_fu_734_p1;
        sext_ln188_reg_1728 <= sext_ln188_fu_720_p1;
    end
end

always @ (*) begin
    if (((icmp_ln232_reg_1621 == 1'd1) & (1'b0 == ap_block_pp0_stage6_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        ap_condition_exit_pp0_iter0_stage6 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage6 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage6_subdone) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage12_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_eta_load = 5'd2;
    end else begin
        ap_sig_allocacmp_eta_load = eta_fu_104;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 11'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_108;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_phi_idx_1_load = 6'd0;
    end else begin
        ap_sig_allocacmp_phi_idx_1_load = phi_idx_1_fu_100;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        clusters_et_ce0_local = 1'b1;
    end else begin
        clusters_et_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln232_reg_1621 == 1'd0) & (1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln257_fu_1171_p2 == 1'd1) & (icmp_ln248_fu_1081_p2 == 1'd0) & (or_ln190_reg_1815 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage6) & (icmp_ln237_reg_1702 == 1'd0))) begin
        clusters_et_we0_local = 1'b1;
    end else begin
        clusters_et_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        clusters_eta_ce0_local = 1'b1;
    end else begin
        clusters_eta_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln232_reg_1621 == 1'd0) & (1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln257_fu_1171_p2 == 1'd1) & (icmp_ln248_fu_1081_p2 == 1'd0) & (or_ln190_reg_1815 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage6) & (icmp_ln237_reg_1702 == 1'd0))) begin
        clusters_eta_we0_local = 1'b1;
    end else begin
        clusters_eta_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        clusters_iso_outer_size_ce0_local = 1'b1;
    end else begin
        clusters_iso_outer_size_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln232_reg_1621 == 1'd0) & (1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln257_fu_1171_p2 == 1'd1) & (icmp_ln248_fu_1081_p2 == 1'd0) & (or_ln190_reg_1815 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage6) & (icmp_ln237_reg_1702 == 1'd0))) begin
        clusters_iso_outer_size_we0_local = 1'b1;
    end else begin
        clusters_iso_outer_size_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        clusters_isolation_et_ce0_local = 1'b1;
    end else begin
        clusters_isolation_et_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln257_reg_1860 == 1'd1) & (icmp_ln248_reg_1841 == 1'd0) & (or_ln190_reg_1815_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage6) & (icmp_ln237_reg_1702_pp0_iter1_reg == 1'd0))) begin
        clusters_isolation_et_we0_local = 1'b1;
    end else begin
        clusters_isolation_et_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        clusters_phi_ce0_local = 1'b1;
    end else begin
        clusters_phi_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln232_reg_1621 == 1'd0) & (1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln257_fu_1171_p2 == 1'd1) & (icmp_ln248_fu_1081_p2 == 1'd0) & (or_ln190_reg_1815 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage6) & (icmp_ln237_reg_1702 == 1'd0))) begin
        clusters_phi_we0_local = 1'b1;
    end else begin
        clusters_phi_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        clusters_valid_ce0_local = 1'b1;
    end else begin
        clusters_valid_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln232_reg_1621 == 1'd0) & (1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln257_fu_1171_p2 == 1'd1) & (icmp_ln248_fu_1081_p2 == 1'd0) & (or_ln190_reg_1815 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage6) & (icmp_ln237_reg_1702 == 1'd0))) begin
        clusters_valid_we0_local = 1'b1;
    end else begin
        clusters_valid_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        clusters_window_size_ce0_local = 1'b1;
    end else begin
        clusters_window_size_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln232_reg_1621 == 1'd0) & (1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln257_fu_1171_p2 == 1'd1) & (icmp_ln248_fu_1081_p2 == 1'd0) & (or_ln190_reg_1815 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage6) & (icmp_ln237_reg_1702 == 1'd0))) begin
        clusters_window_size_we0_local = 1'b1;
    end else begin
        clusters_window_size_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grid_Addr_A_orig = zext_ln159_37_fu_1516_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grid_Addr_A_orig = grid_addr_24_reg_1934;
    end else if (((1'b0 == ap_block_pp0_stage12) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        grid_Addr_A_orig = grid_addr_23_reg_1929;
    end else if (((1'b0 == ap_block_pp0_stage11) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        grid_Addr_A_orig = zext_ln159_41_fu_1457_p1;
    end else if (((1'b0 == ap_block_pp0_stage10) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        grid_Addr_A_orig = zext_ln159_40_fu_1403_p1;
    end else if (((1'b0 == ap_block_pp0_stage9) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        grid_Addr_A_orig = zext_ln159_39_fu_1305_p1;
    end else if (((1'b0 == ap_block_pp0_stage8) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        grid_Addr_A_orig = zext_ln159_38_fu_1264_p1;
    end else if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        grid_Addr_A_orig = zext_ln159_26_fu_1216_p1;
    end else if (((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        grid_Addr_A_orig = zext_ln159_29_fu_1019_p1;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grid_Addr_A_orig = zext_ln188_8_fu_839_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grid_Addr_A_orig = zext_ln188_10_fu_804_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grid_Addr_A_orig = zext_ln188_9_fu_742_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grid_Addr_A_orig = zext_ln188_2_fu_620_p1;
    end else begin
        grid_Addr_A_orig = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage12) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
            grid_Addr_B_orig = grid_addr_22_reg_1939;
        end else if (((1'b0 == ap_block_pp0_stage11) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
            grid_Addr_B_orig = zext_ln159_36_fu_1453_p1;
        end else if (((1'b0 == ap_block_pp0_stage10) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
            grid_Addr_B_orig = zext_ln159_35_fu_1385_p1;
        end else if (((1'b0 == ap_block_pp0_stage9) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
            grid_Addr_B_orig = zext_ln159_34_fu_1292_p1;
        end else if (((1'b0 == ap_block_pp0_stage8) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
            grid_Addr_B_orig = zext_ln159_33_fu_1251_p1;
        end else if (((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            grid_Addr_B_orig = zext_ln159_24_fu_1207_p1;
        end else if (((1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            grid_Addr_B_orig = zext_ln159_32_fu_1126_p1;
        end else if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            grid_Addr_B_orig = zext_ln159_28_fu_848_p1;
        end else if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            grid_Addr_B_orig = zext_ln188_3_fu_830_p1;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grid_Addr_B_orig = zext_ln188_7_fu_794_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grid_Addr_B_orig = zext_ln188_6_fu_729_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grid_Addr_B_orig = zext_ln188_5_fu_675_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grid_Addr_B_orig = zext_ln235_2_fu_569_p1;
        end else begin
            grid_Addr_B_orig = 'bx;
        end
    end else begin
        grid_Addr_B_orig = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage12_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((1'b0 == ap_block_pp0_stage11_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((1'b0 == ap_block_pp0_stage10_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((1'b0 == ap_block_pp0_stage9_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) 
    & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grid_EN_A_local = 1'b1;
    end else begin
        grid_EN_A_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage12_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((1'b0 == ap_block_pp0_stage11_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((1'b0 == ap_block_pp0_stage10_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((1'b0 == ap_block_pp0_stage9_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) 
    & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grid_EN_B_local = 1'b1;
    end else begin
        grid_EN_B_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage6)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        ap_ST_fsm_pp0_stage8 : begin
            if ((1'b0 == ap_block_pp0_stage8_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end
        end
        ap_ST_fsm_pp0_stage9 : begin
            if ((1'b0 == ap_block_pp0_stage9_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end
        end
        ap_ST_fsm_pp0_stage10 : begin
            if ((1'b0 == ap_block_pp0_stage10_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage10;
            end
        end
        ap_ST_fsm_pp0_stage11 : begin
            if ((1'b0 == ap_block_pp0_stage11_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage11;
            end
        end
        ap_ST_fsm_pp0_stage12 : begin
            if ((1'b0 == ap_block_pp0_stage12_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage12;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln133_1_fu_1103_p2 = (zext_ln233_reg_1681 + 7'd58);

assign add_ln133_fu_651_p2 = (zext_ln233_fu_625_p1 + 7'd59);

assign add_ln135_1_fu_1142_p2 = ($signed(zext_ln233_reg_1681) + $signed(7'd70));

assign add_ln135_fu_703_p2 = ($signed(zext_ln233_reg_1681) + $signed(7'd69));

assign add_ln156_1_fu_1131_p2 = (select_ln232_reg_1625 + 6'd2);

assign add_ln156_fu_1086_p2 = ($signed(zext_ln233_reg_1681) + $signed(7'd126));

assign add_ln159_10_fu_1361_p2 = ($signed(sub_ln159_1_fu_1345_p2) + $signed(sext_ln188_reg_1728));

assign add_ln159_11_fu_844_p2 = ($signed(sub_ln188_reg_1668) + $signed(sext_ln188_1_reg_1741));

assign add_ln159_12_fu_1014_p2 = ($signed(sub_ln159_fu_1008_p2) + $signed(sext_ln188_1_reg_1741));

assign add_ln159_13_fu_1371_p2 = ($signed(sub_ln159_1_fu_1345_p2) + $signed(sext_ln188_1_reg_1741));

assign add_ln159_15_fu_1120_p2 = (sub_ln159_fu_1008_p2 + zext_ln159_31_fu_1116_p1);

assign add_ln159_16_fu_1246_p2 = ($signed(sub_ln159_reg_1829) + $signed(sext_ln159_fu_1243_p1));

assign add_ln159_17_fu_1288_p2 = ($signed(sub_ln188_reg_1668) + $signed(sext_ln159_reg_1884));

assign add_ln159_18_fu_1381_p2 = ($signed(sub_ln235_reg_1647) + $signed(sext_ln159_reg_1884));

assign add_ln159_19_fu_1390_p2 = ($signed(sub_ln188_1_reg_1754) + $signed(sext_ln159_reg_1884));

assign add_ln159_1_fu_958_p2 = (zext_ln159_4_fu_937_p1 + zext_ln159_3_fu_934_p1);

assign add_ln159_20_fu_1394_p2 = ($signed(sub_ln159_1_fu_1345_p2) + $signed(sext_ln159_reg_1884));

assign add_ln159_21_fu_1259_p2 = ($signed(sub_ln188_reg_1668) + $signed(sext_ln159_1_fu_1256_p1));

assign add_ln159_22_fu_1301_p2 = ($signed(sub_ln235_reg_1647) + $signed(sext_ln159_1_reg_1897));

assign add_ln159_23_fu_1399_p2 = ($signed(sub_ln188_1_reg_1754) + $signed(sext_ln159_1_reg_1897));

assign add_ln159_24_fu_1408_p2 = ($signed(sub_ln159_1_fu_1345_p2) + $signed(sext_ln159_1_reg_1897));

assign add_ln159_2_fu_968_p2 = (zext_ln159_8_fu_964_p1 + zext_ln159_7_fu_954_p1);

assign add_ln159_3_fu_974_p2 = (zext_ln159_2_fu_931_p1 + zext_ln156_fu_928_p1);

assign add_ln159_4_fu_1040_p2 = (zext_ln155_fu_1028_p1 + zext_ln159_fu_1024_p1);

assign add_ln159_5_fu_1050_p2 = (zext_ln159_12_fu_1046_p1 + zext_ln159_1_fu_1031_p1);

assign add_ln159_6_fu_1060_p2 = (zext_ln159_13_fu_1056_p1 + zext_ln159_11_fu_1037_p1);

assign add_ln159_7_fu_1203_p2 = (sub_ln159_reg_1829 + zext_ln235_1_reg_1655);

assign add_ln159_8_fu_1351_p2 = (sub_ln159_1_fu_1345_p2 + zext_ln235_1_reg_1655);

assign add_ln159_9_fu_1212_p2 = ($signed(sub_ln159_reg_1829) + $signed(sext_ln188_reg_1728));

assign add_ln159_fu_948_p2 = (zext_ln159_5_fu_940_p1 + zext_ln159_6_fu_944_p1);

assign add_ln185_fu_633_p2 = ($signed(zext_ln233_fu_625_p1) + $signed(7'd127));

assign add_ln188_1_fu_826_p2 = (sub_ln188_1_reg_1754 + zext_ln235_1_reg_1655);

assign add_ln188_2_fu_669_p2 = (sub_ln188_fu_609_p2 + zext_ln188_4_fu_665_p1);

assign add_ln188_3_fu_724_p2 = ($signed(sub_ln188_reg_1668) + $signed(sext_ln188_fu_720_p1));

assign add_ln188_4_fu_790_p2 = ($signed(sub_ln235_reg_1647) + $signed(sext_ln188_reg_1728));

assign add_ln188_5_fu_835_p2 = ($signed(sub_ln188_1_reg_1754) + $signed(sext_ln188_reg_1728));

assign add_ln188_6_fu_737_p2 = ($signed(sub_ln235_reg_1647) + $signed(sext_ln188_1_fu_734_p1));

assign add_ln188_7_fu_799_p2 = ($signed(sub_ln188_1_fu_770_p2) + $signed(sext_ln188_1_reg_1741));

assign add_ln188_fu_615_p2 = (sub_ln188_fu_609_p2 + zext_ln235_1_reg_1655);

assign add_ln211_10_fu_1510_p2 = (zext_ln159_20_fu_1502_p1 + zext_ln159_21_fu_1506_p1);

assign add_ln211_11_fu_1536_p2 = (zext_ln159_22_fu_1520_p1 + zext_ln143_fu_1523_p1);

assign add_ln211_12_fu_1546_p2 = (zext_ln211_11_fu_1542_p1 + zext_ln211_10_fu_1533_p1);

assign add_ln211_13_fu_1556_p2 = (zext_ln211_12_fu_1552_p1 + zext_ln211_9_fu_1530_p1);

assign add_ln211_1_fu_1272_p2 = (zext_ln156_1_fu_1235_p1 + zext_ln156_2_fu_1239_p1);

assign add_ln211_2_fu_1282_p2 = (zext_ln211_1_fu_1278_p1 + zext_ln211_fu_1269_p1);

assign add_ln211_3_fu_1314_p2 = (zext_ln133_fu_1297_p1 + zext_ln146_1_fu_1310_p1);

assign add_ln211_4_fu_1427_p2 = (zext_ln155_1_fu_1413_p1 + zext_ln159_15_fu_1417_p1);

assign add_ln211_5_fu_1437_p2 = (zext_ln211_4_fu_1433_p1 + zext_ln211_3_fu_1424_p1);

assign add_ln211_6_fu_1447_p2 = (zext_ln211_5_fu_1443_p1 + zext_ln211_2_fu_1421_p1);

assign add_ln211_7_fu_1469_p2 = (zext_ln159_16_fu_1461_p1 + zext_ln159_17_fu_1465_p1);

assign add_ln211_8_fu_1486_p2 = (zext_ln159_18_fu_1475_p1 + zext_ln159_19_fu_1479_p1);

assign add_ln211_9_fu_1496_p2 = (zext_ln211_8_fu_1492_p1 + zext_ln211_7_fu_1483_p1);

assign add_ln211_fu_1229_p2 = (zext_ln130_fu_1225_p1 + zext_ln146_fu_1221_p1);

assign add_ln232_1_fu_479_p2 = (ap_sig_allocacmp_indvar_flatten_load + 11'd1);

assign add_ln232_2_fu_511_p2 = (ap_sig_allocacmp_eta_load + 5'd1);

assign add_ln232_fu_505_p2 = (ap_sig_allocacmp_eta_load + 5'd2);

assign add_ln235_fu_563_p2 = (sub_ln235_fu_553_p2 + zext_ln235_1_fu_559_p1);

assign add_ln265_fu_1187_p2 = (empty_fu_112 + 32'd1);

assign and_ln190_1_fu_814_p2 = (xor_ln190_1_fu_784_p2 & grp_fu_440_p2);

assign and_ln190_2_fu_820_p2 = (and_ln190_fu_809_p2 & and_ln190_1_fu_814_p2);

assign and_ln190_3_fu_906_p2 = (and_ln190_6_fu_900_p2 & and_ln190_2_reg_1783);

assign and_ln190_4_fu_888_p2 = (xor_ln190_4_fu_878_p2 & xor_ln190_3_fu_867_p2);

assign and_ln190_5_fu_894_p2 = (xor_ln190_2_fu_857_p2 & icmp_ln190_5_fu_884_p2);

assign and_ln190_6_fu_900_p2 = (and_ln190_5_fu_894_p2 & and_ln190_4_fu_888_p2);

assign and_ln190_fu_809_p2 = (is_max_reg_1716 & icmp_ln192_fu_776_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage10 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_pp0_stage11 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_pp0_stage12 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_pp0_stage8 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_pp0_stage9 = ap_CS_fsm[32'd9];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage11 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage11_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage11_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage12 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage12_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage12_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage6;

assign ap_ready = ap_ready_sig;

assign ap_return = inc347_fu_116;

assign cluster_et_fu_1070_p2 = (zext_ln159_14_fu_1066_p1 + zext_ln159_10_fu_1034_p1);

assign clusters_et_address0 = zext_ln258_fu_1177_p1;

assign clusters_et_ce0 = clusters_et_ce0_local;

assign clusters_et_d0 = cluster_et_fu_1070_p2;

assign clusters_et_we0 = clusters_et_we0_local;

assign clusters_eta_address0 = zext_ln258_fu_1177_p1;

assign clusters_eta_ce0 = clusters_eta_ce0_local;

assign clusters_eta_d0 = select_ln232_2_reg_1639;

assign clusters_eta_we0 = clusters_eta_we0_local;

assign clusters_iso_outer_size_address0 = zext_ln258_fu_1177_p1;

assign clusters_iso_outer_size_ce0 = clusters_iso_outer_size_ce0_local;

assign clusters_iso_outer_size_d0 = 3'd5;

assign clusters_iso_outer_size_we0 = clusters_iso_outer_size_we0_local;

assign clusters_isolation_et_address0 = zext_ln258_reg_1864;

assign clusters_isolation_et_ce0 = clusters_isolation_et_ce0_local;

assign clusters_isolation_et_d0 = isolation_et_fu_1566_p2;

assign clusters_isolation_et_we0 = clusters_isolation_et_we0_local;

assign clusters_phi_address0 = zext_ln258_fu_1177_p1;

assign clusters_phi_ce0 = clusters_phi_ce0_local;

assign clusters_phi_d0 = select_ln232_reg_1625;

assign clusters_phi_we0 = clusters_phi_we0_local;

assign clusters_valid_address0 = zext_ln258_fu_1177_p1;

assign clusters_valid_ce0 = clusters_valid_ce0_local;

assign clusters_valid_d0 = 1'd1;

assign clusters_valid_we0 = clusters_valid_we0_local;

assign clusters_window_size_address0 = zext_ln258_fu_1177_p1;

assign clusters_window_size_ce0 = clusters_window_size_ce0_local;

assign clusters_window_size_d0 = 1'd1;

assign clusters_window_size_we0 = clusters_window_size_we0_local;

assign empty_61_fu_584_p2 = ($signed(select_ln232_2_reg_1639) + $signed(5'd31));

assign empty_62_fu_983_p2 = ($signed(select_ln232_2_reg_1639) + $signed(5'd30));

assign empty_63_fu_1320_p2 = (select_ln232_2_reg_1639 + 5'd2);

assign grid_Addr_A = grid_Addr_A_orig << 32'd1;

assign grid_Addr_B = grid_Addr_B_orig << 32'd1;

assign grid_Din_A = 16'd0;

assign grid_Din_B = 16'd0;

assign grid_EN_A = grid_EN_A_local;

assign grid_EN_B = grid_EN_B_local;

assign grid_WEN_A = 2'd0;

assign grid_WEN_B = 2'd0;

assign grp_fu_440_p0 = grid_Dout_B;

assign grp_fu_440_p2 = ((grp_fu_440_p0 < center_et_reg_1689) ? 1'b1 : 1'b0);

assign icmp_ln134_1_fu_1136_p2 = ((add_ln156_1_fu_1131_p2 > 6'd59) ? 1'b1 : 1'b0);

assign icmp_ln134_fu_697_p2 = ((phi_fu_692_p2 > 6'd59) ? 1'b1 : 1'b0);

assign icmp_ln190_1_fu_853_p2 = ((center_et_reg_1689 < neighbor_4_reg_1798) ? 1'b1 : 1'b0);

assign icmp_ln190_2_fu_863_p2 = ((center_et_reg_1689 < neighbor_5_reg_1804) ? 1'b1 : 1'b0);

assign icmp_ln190_3_fu_873_p1 = grid_Dout_B;

assign icmp_ln190_3_fu_873_p2 = ((center_et_reg_1689 < icmp_ln190_3_fu_873_p1) ? 1'b1 : 1'b0);

assign icmp_ln190_5_fu_884_p2 = ((neighbor_3_reg_1777 < center_et_reg_1689) ? 1'b1 : 1'b0);

assign icmp_ln190_6_fu_911_p0 = grid_Dout_A;

assign icmp_ln190_6_fu_911_p2 = ((icmp_ln190_6_fu_911_p0 > center_et_reg_1689) ? 1'b1 : 1'b0);

assign icmp_ln190_fu_780_p2 = ((center_et_reg_1689 < neighbor_1_reg_1721) ? 1'b1 : 1'b0);

assign icmp_ln192_fu_776_p2 = ((neighbor_1_reg_1721 != center_et_reg_1689) ? 1'b1 : 1'b0);

assign icmp_ln232_fu_473_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 11'd1560) ? 1'b1 : 1'b0);

assign icmp_ln233_fu_491_p2 = ((ap_sig_allocacmp_phi_idx_1_load == 6'd60) ? 1'b1 : 1'b0);

assign icmp_ln237_fu_628_p0 = grid_Dout_B;

assign icmp_ln237_fu_628_p2 = ((icmp_ln237_fu_628_p0 < seed_threshold) ? 1'b1 : 1'b0);

assign icmp_ln248_fu_1081_p2 = ((zext_ln246_fu_1077_p1 < cluster_threshold) ? 1'b1 : 1'b0);

assign icmp_ln257_fu_1171_p2 = (($signed(empty_fu_112) < $signed(32'd1800)) ? 1'b1 : 1'b0);

assign isolation_et_fu_1566_p2 = (zext_ln211_13_fu_1562_p1 + zext_ln211_6_fu_1527_p1);

assign or_ln190_fu_922_p2 = (xor_ln190_fu_916_p2 | icmp_ln190_6_fu_911_p2);

assign p_shl1_fu_533_p3 = {{select_ln232_2_fu_525_p3}, {6'd0}};

assign p_shl2_fu_589_p3 = {{empty_61_fu_584_p2}, {6'd0}};

assign p_shl3_fu_752_p3 = {{select_ln232_1_reg_1633}, {6'd0}};

assign p_shl4_fu_988_p3 = {{empty_62_fu_983_p2}, {6'd0}};

assign p_shl_fu_1325_p3 = {{empty_63_fu_1320_p2}, {6'd0}};

assign phi_fu_692_p2 = (select_ln232_reg_1625 + 6'd1);

assign phi_idx_2_fu_712_p3 = ((icmp_ln134_fu_697_p2[0:0] == 1'b1) ? add_ln135_fu_703_p2 : zext_ln134_fu_708_p1);

assign phi_idx_3_fu_684_p3 = ((tmp_5_fu_643_p3[0:0] == 1'b1) ? zext_ln132_fu_680_p1 : sext_ln130_fu_639_p1);

assign phi_idx_4_fu_1108_p3 = ((tmp_6_fu_1095_p3[0:0] == 1'b1) ? add_ln133_1_fu_1103_p2 : add_ln156_fu_1086_p2);

assign phi_idx_5_fu_1151_p3 = ((icmp_ln134_1_fu_1136_p2[0:0] == 1'b1) ? add_ln135_1_fu_1142_p2 : zext_ln134_1_fu_1147_p1);

assign phi_idx_6_fu_1163_p3 = ((tmp_6_fu_1095_p3[0:0] == 1'b1) ? zext_ln132_1_fu_1159_p1 : sext_ln130_1_fu_1091_p1);

assign phi_idx_fu_657_p3 = ((tmp_5_fu_643_p3[0:0] == 1'b1) ? add_ln133_fu_651_p2 : add_ln185_fu_633_p2);

assign select_ln232_1_fu_517_p3 = ((icmp_ln233_fu_491_p2[0:0] == 1'b1) ? add_ln232_fu_505_p2 : add_ln232_2_fu_511_p2);

assign select_ln232_2_fu_525_p3 = ((icmp_ln233_fu_491_p2[0:0] == 1'b1) ? add_ln232_2_fu_511_p2 : ap_sig_allocacmp_eta_load);

assign select_ln232_fu_497_p3 = ((icmp_ln233_fu_491_p2[0:0] == 1'b1) ? 6'd0 : ap_sig_allocacmp_phi_idx_1_load);

assign sext_ln130_1_fu_1091_p1 = add_ln156_fu_1086_p2;

assign sext_ln130_fu_639_p1 = add_ln185_fu_633_p2;

assign sext_ln159_1_fu_1256_p1 = $signed(phi_idx_6_reg_1855);

assign sext_ln159_fu_1243_p1 = $signed(phi_idx_5_reg_1850);

assign sext_ln188_1_fu_734_p1 = $signed(phi_idx_3_reg_1711);

assign sext_ln188_fu_720_p1 = $signed(phi_idx_2_fu_712_p3);

assign sub_ln159_1_fu_1345_p2 = (p_shl_fu_1325_p3 - zext_ln159_23_fu_1341_p1);

assign sub_ln159_fu_1008_p2 = (p_shl4_fu_988_p3 - zext_ln159_9_fu_1004_p1);

assign sub_ln188_1_fu_770_p2 = (p_shl3_fu_752_p3 - zext_ln188_1_fu_766_p1);

assign sub_ln188_fu_609_p2 = (p_shl2_fu_589_p3 - zext_ln188_fu_605_p1);

assign sub_ln235_fu_553_p2 = (p_shl1_fu_533_p3 - zext_ln235_fu_549_p1);

assign tmp_1_fu_597_p3 = {{empty_61_fu_584_p2}, {2'd0}};

assign tmp_2_fu_759_p3 = {{select_ln232_1_reg_1633}, {2'd0}};

assign tmp_3_fu_996_p3 = {{empty_62_fu_983_p2}, {2'd0}};

assign tmp_4_fu_1333_p3 = {{empty_63_fu_1320_p2}, {2'd0}};

assign tmp_5_fu_643_p3 = add_ln185_fu_633_p2[32'd6];

assign tmp_6_fu_1095_p3 = add_ln156_fu_1086_p2[32'd6];

assign tmp_fu_541_p3 = {{select_ln232_2_fu_525_p3}, {2'd0}};

assign xor_ln190_1_fu_784_p2 = (icmp_ln190_fu_780_p2 ^ 1'd1);

assign xor_ln190_2_fu_857_p2 = (icmp_ln190_1_fu_853_p2 ^ 1'd1);

assign xor_ln190_3_fu_867_p2 = (icmp_ln190_2_fu_863_p2 ^ 1'd1);

assign xor_ln190_4_fu_878_p2 = (icmp_ln190_3_fu_873_p2 ^ 1'd1);

assign xor_ln190_fu_916_p2 = (1'd1 ^ and_ln190_3_fu_906_p2);

assign zext_ln130_fu_1225_p0 = grid_Dout_A;

assign zext_ln130_fu_1225_p1 = zext_ln130_fu_1225_p0;

assign zext_ln132_1_fu_1159_p1 = add_ln133_1_fu_1103_p2;

assign zext_ln132_fu_680_p1 = add_ln133_fu_651_p2;

assign zext_ln133_fu_1297_p0 = grid_Dout_B;

assign zext_ln133_fu_1297_p1 = zext_ln133_fu_1297_p0;

assign zext_ln134_1_fu_1147_p1 = add_ln156_1_fu_1131_p2;

assign zext_ln134_fu_708_p1 = phi_fu_692_p2;

assign zext_ln143_fu_1523_p0 = grid_Dout_A;

assign zext_ln143_fu_1523_p1 = zext_ln143_fu_1523_p0;

assign zext_ln146_1_fu_1310_p0 = grid_Dout_A;

assign zext_ln146_1_fu_1310_p1 = zext_ln146_1_fu_1310_p0;

assign zext_ln146_fu_1221_p0 = grid_Dout_B;

assign zext_ln146_fu_1221_p1 = zext_ln146_fu_1221_p0;

assign zext_ln155_1_fu_1413_p0 = grid_Dout_B;

assign zext_ln155_1_fu_1413_p1 = zext_ln155_1_fu_1413_p0;

assign zext_ln155_fu_1028_p1 = neighbor_2_reg_1767;

assign zext_ln156_1_fu_1235_p0 = grid_Dout_B;

assign zext_ln156_1_fu_1235_p1 = zext_ln156_1_fu_1235_p0;

assign zext_ln156_2_fu_1239_p0 = grid_Dout_A;

assign zext_ln156_2_fu_1239_p1 = zext_ln156_2_fu_1239_p0;

assign zext_ln156_fu_928_p1 = neighbor_1_reg_1721;

assign zext_ln159_10_fu_1034_p1 = add_ln159_2_reg_1819;

assign zext_ln159_11_fu_1037_p1 = add_ln159_3_reg_1824;

assign zext_ln159_12_fu_1046_p1 = add_ln159_4_fu_1040_p2;

assign zext_ln159_13_fu_1056_p1 = add_ln159_5_fu_1050_p2;

assign zext_ln159_14_fu_1066_p1 = add_ln159_6_fu_1060_p2;

assign zext_ln159_15_fu_1417_p0 = grid_Dout_A;

assign zext_ln159_15_fu_1417_p1 = zext_ln159_15_fu_1417_p0;

assign zext_ln159_16_fu_1461_p0 = grid_Dout_B;

assign zext_ln159_16_fu_1461_p1 = zext_ln159_16_fu_1461_p0;

assign zext_ln159_17_fu_1465_p0 = grid_Dout_A;

assign zext_ln159_17_fu_1465_p1 = zext_ln159_17_fu_1465_p0;

assign zext_ln159_18_fu_1475_p0 = grid_Dout_B;

assign zext_ln159_18_fu_1475_p1 = zext_ln159_18_fu_1475_p0;

assign zext_ln159_19_fu_1479_p0 = grid_Dout_A;

assign zext_ln159_19_fu_1479_p1 = zext_ln159_19_fu_1479_p0;

assign zext_ln159_1_fu_1031_p1 = neighbor_3_reg_1777;

assign zext_ln159_20_fu_1502_p0 = grid_Dout_B;

assign zext_ln159_20_fu_1502_p1 = zext_ln159_20_fu_1502_p0;

assign zext_ln159_21_fu_1506_p0 = grid_Dout_A;

assign zext_ln159_21_fu_1506_p1 = zext_ln159_21_fu_1506_p0;

assign zext_ln159_22_fu_1520_p1 = grid_load_15_reg_1999;

assign zext_ln159_23_fu_1341_p1 = tmp_4_fu_1333_p3;

assign zext_ln159_24_fu_1207_p1 = add_ln159_7_fu_1203_p2;

assign zext_ln159_25_fu_1356_p1 = add_ln159_8_fu_1351_p2;

assign zext_ln159_26_fu_1216_p1 = add_ln159_9_fu_1212_p2;

assign zext_ln159_27_fu_1366_p1 = add_ln159_10_fu_1361_p2;

assign zext_ln159_28_fu_848_p1 = add_ln159_11_fu_844_p2;

assign zext_ln159_29_fu_1019_p1 = add_ln159_12_fu_1014_p2;

assign zext_ln159_2_fu_931_p1 = center_et_reg_1689;

assign zext_ln159_30_fu_1376_p1 = add_ln159_13_fu_1371_p2;

assign zext_ln159_31_fu_1116_p1 = phi_idx_4_fu_1108_p3;

assign zext_ln159_32_fu_1126_p1 = add_ln159_15_fu_1120_p2;

assign zext_ln159_33_fu_1251_p1 = add_ln159_16_fu_1246_p2;

assign zext_ln159_34_fu_1292_p1 = add_ln159_17_fu_1288_p2;

assign zext_ln159_35_fu_1385_p1 = add_ln159_18_fu_1381_p2;

assign zext_ln159_36_fu_1453_p1 = add_ln159_19_reg_1949;

assign zext_ln159_37_fu_1516_p1 = add_ln159_20_reg_1954;

assign zext_ln159_38_fu_1264_p1 = add_ln159_21_fu_1259_p2;

assign zext_ln159_39_fu_1305_p1 = add_ln159_22_fu_1301_p2;

assign zext_ln159_3_fu_934_p1 = neighbor_4_reg_1798;

assign zext_ln159_40_fu_1403_p1 = add_ln159_23_fu_1399_p2;

assign zext_ln159_41_fu_1457_p1 = add_ln159_24_reg_1964;

assign zext_ln159_4_fu_937_p1 = neighbor_5_reg_1804;

assign zext_ln159_5_fu_940_p0 = grid_Dout_B;

assign zext_ln159_5_fu_940_p1 = zext_ln159_5_fu_940_p0;

assign zext_ln159_6_fu_944_p0 = grid_Dout_A;

assign zext_ln159_6_fu_944_p1 = zext_ln159_6_fu_944_p0;

assign zext_ln159_7_fu_954_p1 = add_ln159_fu_948_p2;

assign zext_ln159_8_fu_964_p1 = add_ln159_1_fu_958_p2;

assign zext_ln159_9_fu_1004_p1 = tmp_3_fu_996_p3;

assign zext_ln159_fu_1024_p0 = grid_Dout_B;

assign zext_ln159_fu_1024_p1 = zext_ln159_fu_1024_p0;

assign zext_ln188_10_fu_804_p1 = add_ln188_7_fu_799_p2;

assign zext_ln188_1_fu_766_p1 = tmp_2_fu_759_p3;

assign zext_ln188_2_fu_620_p1 = add_ln188_fu_615_p2;

assign zext_ln188_3_fu_830_p1 = add_ln188_1_fu_826_p2;

assign zext_ln188_4_fu_665_p1 = phi_idx_fu_657_p3;

assign zext_ln188_5_fu_675_p1 = add_ln188_2_fu_669_p2;

assign zext_ln188_6_fu_729_p1 = add_ln188_3_fu_724_p2;

assign zext_ln188_7_fu_794_p1 = add_ln188_4_fu_790_p2;

assign zext_ln188_8_fu_839_p1 = add_ln188_5_fu_835_p2;

assign zext_ln188_9_fu_742_p1 = add_ln188_6_fu_737_p2;

assign zext_ln188_fu_605_p1 = tmp_1_fu_597_p3;

assign zext_ln211_10_fu_1533_p1 = add_ln211_10_reg_1994;

assign zext_ln211_11_fu_1542_p1 = add_ln211_11_fu_1536_p2;

assign zext_ln211_12_fu_1552_p1 = add_ln211_12_fu_1546_p2;

assign zext_ln211_13_fu_1562_p1 = add_ln211_13_fu_1556_p2;

assign zext_ln211_1_fu_1278_p1 = add_ln211_1_fu_1272_p2;

assign zext_ln211_2_fu_1421_p1 = add_ln211_2_reg_1909;

assign zext_ln211_3_fu_1424_p1 = add_ln211_3_reg_1924;

assign zext_ln211_4_fu_1433_p1 = add_ln211_4_fu_1427_p2;

assign zext_ln211_5_fu_1443_p1 = add_ln211_5_fu_1437_p2;

assign zext_ln211_6_fu_1527_p1 = add_ln211_6_reg_1969;

assign zext_ln211_7_fu_1483_p1 = add_ln211_7_reg_1984;

assign zext_ln211_8_fu_1492_p1 = add_ln211_8_fu_1486_p2;

assign zext_ln211_9_fu_1530_p1 = add_ln211_9_reg_1989;

assign zext_ln211_fu_1269_p1 = add_ln211_reg_1879;

assign zext_ln233_fu_625_p1 = select_ln232_reg_1625;

assign zext_ln235_1_fu_559_p1 = select_ln232_fu_497_p3;

assign zext_ln235_2_fu_569_p1 = add_ln235_fu_563_p2;

assign zext_ln235_fu_549_p1 = tmp_fu_541_p3;

assign zext_ln246_fu_1077_p1 = cluster_et_fu_1070_p2;

assign zext_ln258_fu_1177_p1 = empty_fu_112;

always @ (posedge ap_clk) begin
    sub_ln235_reg_1647[1:0] <= 2'b00;
    zext_ln235_1_reg_1655[10:6] <= 5'b00000;
    sub_ln188_reg_1668[1:0] <= 2'b00;
    zext_ln233_reg_1681[6] <= 1'b0;
    sub_ln188_1_reg_1754[1:0] <= 2'b00;
    sub_ln159_reg_1829[1:0] <= 2'b00;
    zext_ln258_reg_1864[63:32] <= 32'b00000000000000000000000000000000;
end

endmodule //calo_trigger_ref_find_clusters_3_5_s
