// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="calo_trigger_stream_ref_calo_trigger_stream_ref,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu13p-fsga2577-2-e,HLS_INPUT_CLOCK=25.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.516000,HLS_SYN_LAT=22086,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=4003,HLS_SYN_LUT=7879,HLS_VERSION=2024_1}" *)

module calo_trigger_stream_ref (
        ap_clk,
        ap_rst_n,
        towers_Addr_A,
        towers_EN_A,
        towers_WEN_A,
        towers_Din_A,
        towers_Dout_A,
        towers_Clk_A,
        towers_Rst_A,
        towers_Addr_B,
        towers_EN_B,
        towers_WEN_B,
        towers_Din_B,
        towers_Dout_B,
        towers_Clk_B,
        towers_Rst_B,
        trigger_objects_0,
        trigger_objects_0_ap_vld,
        trigger_objects_1,
        trigger_objects_1_ap_vld,
        trigger_objects_2,
        trigger_objects_2_ap_vld,
        trigger_objects_3,
        trigger_objects_3_ap_vld,
        trigger_objects_4,
        trigger_objects_4_ap_vld,
        trigger_objects_5,
        trigger_objects_5_ap_vld,
        trigger_objects_6,
        trigger_objects_6_ap_vld,
        trigger_objects_7,
        trigger_objects_7_ap_vld,
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_pp0_stage0 = 4'd2;
parameter    ap_ST_fsm_state4 = 4'd4;
parameter    ap_ST_fsm_state5 = 4'd8;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output  [31:0] towers_Addr_A;
output   towers_EN_A;
output  [1:0] towers_WEN_A;
output  [15:0] towers_Din_A;
input  [15:0] towers_Dout_A;
output   towers_Clk_A;
output   towers_Rst_A;
output  [31:0] towers_Addr_B;
output   towers_EN_B;
output  [1:0] towers_WEN_B;
output  [15:0] towers_Din_B;
input  [15:0] towers_Dout_B;
output   towers_Clk_B;
output   towers_Rst_B;
output  [88:0] trigger_objects_0;
output   trigger_objects_0_ap_vld;
output  [88:0] trigger_objects_1;
output   trigger_objects_1_ap_vld;
output  [88:0] trigger_objects_2;
output   trigger_objects_2_ap_vld;
output  [88:0] trigger_objects_3;
output   trigger_objects_3_ap_vld;
output  [88:0] trigger_objects_4;
output   trigger_objects_4_ap_vld;
output  [88:0] trigger_objects_5;
output   trigger_objects_5_ap_vld;
output  [88:0] trigger_objects_6;
output   trigger_objects_6_ap_vld;
output  [88:0] trigger_objects_7;
output   trigger_objects_7_ap_vld;
input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;
output   interrupt;

reg[31:0] towers_Addr_A;
reg towers_EN_A;
reg towers_EN_B;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [11:0] seed_threshold;
wire   [19:0] cluster_threshold;
reg    ht_ap_vld;
reg   [0:0] icmp_ln1616_reg_154;
reg   [19:0] cluster_threshold_read_reg_372;
reg   [11:0] seed_threshold_read_reg_377;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln161_fu_295_p2;
reg   [0:0] icmp_ln161_reg_387;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] icmp_ln160_fu_301_p2;
reg   [0:0] icmp_ln160_reg_392;
wire   [23:0] zext_ln161_fu_335_p1;
reg   [23:0] zext_ln161_reg_396;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_flush_enable;
wire   [31:0] grp_cluster_sort_build_stream_fu_165_towers_Addr_A;
wire    grp_cluster_sort_build_stream_fu_165_towers_EN_A;
wire   [15:0] grp_cluster_sort_build_stream_fu_165_towers_Din_A;
wire   [1:0] grp_cluster_sort_build_stream_fu_165_towers_WEN_A;
wire   [31:0] grp_cluster_sort_build_stream_fu_165_towers_Addr_B;
wire    grp_cluster_sort_build_stream_fu_165_towers_EN_B;
wire   [15:0] grp_cluster_sort_build_stream_fu_165_towers_Din_B;
wire   [1:0] grp_cluster_sort_build_stream_fu_165_towers_WEN_B;
wire   [88:0] grp_cluster_sort_build_stream_fu_165_trigger_objects_0;
wire   [88:0] grp_cluster_sort_build_stream_fu_165_trigger_objects_1;
wire   [88:0] grp_cluster_sort_build_stream_fu_165_trigger_objects_2;
wire   [88:0] grp_cluster_sort_build_stream_fu_165_trigger_objects_3;
wire   [88:0] grp_cluster_sort_build_stream_fu_165_trigger_objects_4;
wire   [88:0] grp_cluster_sort_build_stream_fu_165_trigger_objects_5;
wire   [88:0] grp_cluster_sort_build_stream_fu_165_trigger_objects_6;
wire   [88:0] grp_cluster_sort_build_stream_fu_165_trigger_objects_7;
wire   [31:0] grp_cluster_sort_build_stream_fu_165_num_clusters;
wire    grp_cluster_sort_build_stream_fu_165_ap_start;
wire    grp_cluster_sort_build_stream_fu_165_num_clusters_ap_vld;
wire    grp_cluster_sort_build_stream_fu_165_ap_done;
wire    grp_cluster_sort_build_stream_fu_165_trigger_objects_0_ap_vld;
wire    grp_cluster_sort_build_stream_fu_165_trigger_objects_1_ap_vld;
wire    grp_cluster_sort_build_stream_fu_165_trigger_objects_2_ap_vld;
wire    grp_cluster_sort_build_stream_fu_165_trigger_objects_3_ap_vld;
wire    grp_cluster_sort_build_stream_fu_165_trigger_objects_4_ap_vld;
wire    grp_cluster_sort_build_stream_fu_165_trigger_objects_5_ap_vld;
wire    grp_cluster_sort_build_stream_fu_165_trigger_objects_6_ap_vld;
wire    grp_cluster_sort_build_stream_fu_165_trigger_objects_7_ap_vld;
wire    grp_cluster_sort_build_stream_fu_165_ap_ready;
wire    grp_cluster_sort_build_stream_fu_165_ap_idle;
reg    grp_cluster_sort_build_stream_fu_165_ap_continue;
reg   [0:0] ap_phi_mux_icmp_ln1616_phi_fu_158_p4;
wire    ap_block_pp0_stage0;
reg    grp_cluster_sort_build_stream_fu_165_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg    ap_sync_reg_grp_cluster_sort_build_stream_fu_165_ap_ready;
reg    ap_sync_reg_grp_cluster_sort_build_stream_fu_165_ap_done;
reg    ap_block_state5_on_subcall_done;
wire    ap_sync_grp_cluster_sort_build_stream_fu_165_ap_ready;
wire   [63:0] zext_ln163_3_fu_278_p1;
reg   [10:0] indvar_flatten1_fu_106;
wire   [10:0] add_ln160_1_fu_289_p2;
reg   [4:0] eta2_fu_110;
wire   [4:0] eta_fu_234_p3;
reg   [5:0] phi3_fu_114;
wire   [5:0] phi_fu_283_p2;
reg   [22:0] conv4_i4_i4_fu_118;
wire   [22:0] ht_2_fu_329_p2;
reg    towers_EN_A_local;
wire   [31:0] towers_Addr_A_local;
wire   [31:0] towers_Addr_A_orig;
wire   [4:0] add_ln160_fu_220_p2;
wire   [6:0] tmp_fu_250_p3;
wire   [10:0] p_shl_fu_242_p3;
wire   [10:0] zext_ln163_fu_258_p1;
wire   [5:0] select_ln160_fu_226_p3;
wire   [10:0] sub_ln163_fu_262_p2;
wire   [10:0] zext_ln163_2_fu_268_p1;
wire   [10:0] add_ln163_1_fu_272_p2;
wire   [11:0] zext_ln163_4_fu_325_p0;
wire   [22:0] zext_ln163_4_fu_325_p1;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 grp_cluster_sort_build_stream_fu_165_ap_start_reg = 1'b0;
#0 ap_sync_reg_grp_cluster_sort_build_stream_fu_165_ap_ready = 1'b0;
#0 ap_sync_reg_grp_cluster_sort_build_stream_fu_165_ap_done = 1'b0;
#0 indvar_flatten1_fu_106 = 11'd0;
#0 eta2_fu_110 = 5'd0;
#0 phi3_fu_114 = 6'd0;
#0 conv4_i4_i4_fu_118 = 23'd0;
end

calo_trigger_stream_ref_cluster_sort_build_stream grp_cluster_sort_build_stream_fu_165(
    .towers_Addr_A(grp_cluster_sort_build_stream_fu_165_towers_Addr_A),
    .towers_EN_A(grp_cluster_sort_build_stream_fu_165_towers_EN_A),
    .towers_Din_A(grp_cluster_sort_build_stream_fu_165_towers_Din_A),
    .towers_Dout_A(towers_Dout_A),
    .towers_WEN_A(grp_cluster_sort_build_stream_fu_165_towers_WEN_A),
    .towers_Addr_B(grp_cluster_sort_build_stream_fu_165_towers_Addr_B),
    .towers_EN_B(grp_cluster_sort_build_stream_fu_165_towers_EN_B),
    .towers_Din_B(grp_cluster_sort_build_stream_fu_165_towers_Din_B),
    .towers_Dout_B(towers_Dout_B),
    .towers_WEN_B(grp_cluster_sort_build_stream_fu_165_towers_WEN_B),
    .seed_threshold(seed_threshold_read_reg_377),
    .cluster_threshold(cluster_threshold_read_reg_372),
    .trigger_objects_0(grp_cluster_sort_build_stream_fu_165_trigger_objects_0),
    .trigger_objects_1(grp_cluster_sort_build_stream_fu_165_trigger_objects_1),
    .trigger_objects_2(grp_cluster_sort_build_stream_fu_165_trigger_objects_2),
    .trigger_objects_3(grp_cluster_sort_build_stream_fu_165_trigger_objects_3),
    .trigger_objects_4(grp_cluster_sort_build_stream_fu_165_trigger_objects_4),
    .trigger_objects_5(grp_cluster_sort_build_stream_fu_165_trigger_objects_5),
    .trigger_objects_6(grp_cluster_sort_build_stream_fu_165_trigger_objects_6),
    .trigger_objects_7(grp_cluster_sort_build_stream_fu_165_trigger_objects_7),
    .num_clusters(grp_cluster_sort_build_stream_fu_165_num_clusters),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .seed_threshold_ap_vld(1'b1),
    .cluster_threshold_ap_vld(1'b1),
    .ap_start(grp_cluster_sort_build_stream_fu_165_ap_start),
    .num_clusters_ap_vld(grp_cluster_sort_build_stream_fu_165_num_clusters_ap_vld),
    .ap_done(grp_cluster_sort_build_stream_fu_165_ap_done),
    .trigger_objects_0_ap_vld(grp_cluster_sort_build_stream_fu_165_trigger_objects_0_ap_vld),
    .trigger_objects_1_ap_vld(grp_cluster_sort_build_stream_fu_165_trigger_objects_1_ap_vld),
    .trigger_objects_2_ap_vld(grp_cluster_sort_build_stream_fu_165_trigger_objects_2_ap_vld),
    .trigger_objects_3_ap_vld(grp_cluster_sort_build_stream_fu_165_trigger_objects_3_ap_vld),
    .trigger_objects_4_ap_vld(grp_cluster_sort_build_stream_fu_165_trigger_objects_4_ap_vld),
    .trigger_objects_5_ap_vld(grp_cluster_sort_build_stream_fu_165_trigger_objects_5_ap_vld),
    .trigger_objects_6_ap_vld(grp_cluster_sort_build_stream_fu_165_trigger_objects_6_ap_vld),
    .trigger_objects_7_ap_vld(grp_cluster_sort_build_stream_fu_165_trigger_objects_7_ap_vld),
    .ap_ready(grp_cluster_sort_build_stream_fu_165_ap_ready),
    .ap_idle(grp_cluster_sort_build_stream_fu_165_ap_idle),
    .ap_continue(grp_cluster_sort_build_stream_fu_165_ap_continue)
);

calo_trigger_stream_ref_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .seed_threshold(seed_threshold),
    .cluster_threshold(cluster_threshold),
    .ht(zext_ln161_reg_396),
    .ht_ap_vld(ht_ap_vld),
    .num_clusters(grp_cluster_sort_build_stream_fu_165_num_clusters),
    .num_clusters_ap_vld(grp_cluster_sort_build_stream_fu_165_num_clusters_ap_vld),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp0_flush_enable)) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_grp_cluster_sort_build_stream_fu_165_ap_done <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5))) begin
            ap_sync_reg_grp_cluster_sort_build_stream_fu_165_ap_done <= 1'b0;
        end else if ((grp_cluster_sort_build_stream_fu_165_ap_done == 1'b1)) begin
            ap_sync_reg_grp_cluster_sort_build_stream_fu_165_ap_done <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_grp_cluster_sort_build_stream_fu_165_ap_ready <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5))) begin
            ap_sync_reg_grp_cluster_sort_build_stream_fu_165_ap_ready <= 1'b0;
        end else if ((grp_cluster_sort_build_stream_fu_165_ap_ready == 1'b1)) begin
            ap_sync_reg_grp_cluster_sort_build_stream_fu_165_ap_ready <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_cluster_sort_build_stream_fu_165_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state4) | ((ap_sync_grp_cluster_sort_build_stream_fu_165_ap_ready == 1'b0) & (1'b1 == ap_CS_fsm_state5)))) begin
            grp_cluster_sort_build_stream_fu_165_ap_start_reg <= 1'b1;
        end else if ((grp_cluster_sort_build_stream_fu_165_ap_ready == 1'b1)) begin
            grp_cluster_sort_build_stream_fu_165_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        conv4_i4_i4_fu_118 <= 23'd0;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv4_i4_i4_fu_118 <= ht_2_fu_329_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        eta2_fu_110 <= 5'd0;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        eta2_fu_110 <= eta_fu_234_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln160_reg_392 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln1616_reg_154 <= icmp_ln161_reg_387;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        icmp_ln1616_reg_154 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvar_flatten1_fu_106 <= 11'd0;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten1_fu_106 <= add_ln160_1_fu_289_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        phi3_fu_114 <= 6'd0;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        phi3_fu_114 <= phi_fu_283_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        cluster_threshold_read_reg_372 <= cluster_threshold;
        seed_threshold_read_reg_377 <= seed_threshold;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln160_reg_392 <= icmp_ln160_fu_301_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln161_reg_387 <= icmp_ln161_fu_295_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        zext_ln161_reg_396[22 : 0] <= zext_ln161_fu_335_p1[22 : 0];
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state5_on_subcall_done)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln160_fu_301_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_pp0_flush_enable = 1'b1;
    end else begin
        ap_condition_pp0_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln160_reg_392 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_icmp_ln1616_phi_fu_158_p4 = icmp_ln161_reg_387;
    end else begin
        ap_phi_mux_icmp_ln1616_phi_fu_158_p4 = icmp_ln1616_reg_154;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5))) begin
        grp_cluster_sort_build_stream_fu_165_ap_continue = 1'b1;
    end else begin
        grp_cluster_sort_build_stream_fu_165_ap_continue = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ht_ap_vld = 1'b1;
    end else begin
        ht_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        towers_Addr_A = grp_cluster_sort_build_stream_fu_165_towers_Addr_A;
    end else begin
        towers_Addr_A = towers_Addr_A_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        towers_EN_A = grp_cluster_sort_build_stream_fu_165_towers_EN_A;
    end else begin
        towers_EN_A = towers_EN_A_local;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        towers_EN_A_local = 1'b1;
    end else begin
        towers_EN_A_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        towers_EN_B = grp_cluster_sort_build_stream_fu_165_towers_EN_B;
    end else begin
        towers_EN_B = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((ap_enable_reg_pp0_iter1 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln160_1_fu_289_p2 = (indvar_flatten1_fu_106 + 11'd1);

assign add_ln160_fu_220_p2 = (eta2_fu_110 + 5'd1);

assign add_ln163_1_fu_272_p2 = (sub_ln163_fu_262_p2 + zext_ln163_2_fu_268_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_on_subcall_done = ((ap_sync_reg_grp_cluster_sort_build_stream_fu_165_ap_ready & ap_sync_reg_grp_cluster_sort_build_stream_fu_165_ap_done) == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_grp_cluster_sort_build_stream_fu_165_ap_ready = (grp_cluster_sort_build_stream_fu_165_ap_ready | ap_sync_reg_grp_cluster_sort_build_stream_fu_165_ap_ready);

assign eta_fu_234_p3 = ((ap_phi_mux_icmp_ln1616_phi_fu_158_p4[0:0] == 1'b1) ? add_ln160_fu_220_p2 : eta2_fu_110);

assign grp_cluster_sort_build_stream_fu_165_ap_start = grp_cluster_sort_build_stream_fu_165_ap_start_reg;

assign ht_2_fu_329_p2 = (conv4_i4_i4_fu_118 + zext_ln163_4_fu_325_p1);

assign icmp_ln160_fu_301_p2 = ((indvar_flatten1_fu_106 == 11'd1799) ? 1'b1 : 1'b0);

assign icmp_ln161_fu_295_p2 = ((phi_fu_283_p2 == 6'd60) ? 1'b1 : 1'b0);

assign p_shl_fu_242_p3 = {{eta_fu_234_p3}, {6'd0}};

assign phi_fu_283_p2 = (select_ln160_fu_226_p3 + 6'd1);

assign select_ln160_fu_226_p3 = ((ap_phi_mux_icmp_ln1616_phi_fu_158_p4[0:0] == 1'b1) ? 6'd0 : phi3_fu_114);

assign sub_ln163_fu_262_p2 = (p_shl_fu_242_p3 - zext_ln163_fu_258_p1);

assign tmp_fu_250_p3 = {{eta_fu_234_p3}, {2'd0}};

assign towers_Addr_A_local = towers_Addr_A_orig << 32'd1;

assign towers_Addr_A_orig = zext_ln163_3_fu_278_p1;

assign towers_Addr_B = grp_cluster_sort_build_stream_fu_165_towers_Addr_B;

assign towers_Clk_A = ap_clk;

assign towers_Clk_B = ap_clk;

assign towers_Din_A = 16'd0;

assign towers_Din_B = 16'd0;

assign towers_Rst_A = ap_rst_n_inv;

assign towers_Rst_B = ap_rst_n_inv;

assign towers_WEN_A = 2'd0;

assign towers_WEN_B = 2'd0;

assign trigger_objects_0 = grp_cluster_sort_build_stream_fu_165_trigger_objects_0;

assign trigger_objects_0_ap_vld = grp_cluster_sort_build_stream_fu_165_trigger_objects_0_ap_vld;

assign trigger_objects_1 = grp_cluster_sort_build_stream_fu_165_trigger_objects_1;

assign trigger_objects_1_ap_vld = grp_cluster_sort_build_stream_fu_165_trigger_objects_1_ap_vld;

assign trigger_objects_2 = grp_cluster_sort_build_stream_fu_165_trigger_objects_2;

assign trigger_objects_2_ap_vld = grp_cluster_sort_build_stream_fu_165_trigger_objects_2_ap_vld;

assign trigger_objects_3 = grp_cluster_sort_build_stream_fu_165_trigger_objects_3;

assign trigger_objects_3_ap_vld = grp_cluster_sort_build_stream_fu_165_trigger_objects_3_ap_vld;

assign trigger_objects_4 = grp_cluster_sort_build_stream_fu_165_trigger_objects_4;

assign trigger_objects_4_ap_vld = grp_cluster_sort_build_stream_fu_165_trigger_objects_4_ap_vld;

assign trigger_objects_5 = grp_cluster_sort_build_stream_fu_165_trigger_objects_5;

assign trigger_objects_5_ap_vld = grp_cluster_sort_build_stream_fu_165_trigger_objects_5_ap_vld;

assign trigger_objects_6 = grp_cluster_sort_build_stream_fu_165_trigger_objects_6;

assign trigger_objects_6_ap_vld = grp_cluster_sort_build_stream_fu_165_trigger_objects_6_ap_vld;

assign trigger_objects_7 = grp_cluster_sort_build_stream_fu_165_trigger_objects_7;

assign trigger_objects_7_ap_vld = grp_cluster_sort_build_stream_fu_165_trigger_objects_7_ap_vld;

assign zext_ln161_fu_335_p1 = ht_2_fu_329_p2;

assign zext_ln163_2_fu_268_p1 = select_ln160_fu_226_p3;

assign zext_ln163_3_fu_278_p1 = add_ln163_1_fu_272_p2;

assign zext_ln163_4_fu_325_p0 = towers_Dout_A;

assign zext_ln163_4_fu_325_p1 = zext_ln163_4_fu_325_p0;

assign zext_ln163_fu_258_p1 = tmp_fu_250_p3;

always @ (posedge ap_clk) begin
    zext_ln161_reg_396[23] <= 1'b0;
end

endmodule //calo_trigger_stream_ref
