// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module calo_trigger_ref_select_top_n_Pipeline_VITIS_LOOP_128_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        candidate_et,
        top_clusters_et_address0,
        top_clusters_et_ce0,
        top_clusters_et_q0,
        top_clusters_eta_address0,
        top_clusters_eta_ce0,
        top_clusters_eta_q0,
        top_clusters_phi_address0,
        top_clusters_phi_ce0,
        top_clusters_phi_q0,
        top_clusters_valid_address0,
        top_clusters_valid_ce0,
        top_clusters_valid_q0,
        candidate_eta,
        candidate_phi,
        j_out,
        j_out_ap_vld,
        zext_ln128_out,
        zext_ln128_out_ap_vld,
        ap_return
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_state3 = 11'd4;
parameter    ap_ST_fsm_state4 = 11'd8;
parameter    ap_ST_fsm_state5 = 11'd16;
parameter    ap_ST_fsm_state6 = 11'd32;
parameter    ap_ST_fsm_state7 = 11'd64;
parameter    ap_ST_fsm_state8 = 11'd128;
parameter    ap_ST_fsm_state9 = 11'd256;
parameter    ap_ST_fsm_state10 = 11'd512;
parameter    ap_ST_fsm_state11 = 11'd1024;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] candidate_et;
output  [2:0] top_clusters_et_address0;
output   top_clusters_et_ce0;
input  [15:0] top_clusters_et_q0;
output  [2:0] top_clusters_eta_address0;
output   top_clusters_eta_ce0;
input  [4:0] top_clusters_eta_q0;
output  [2:0] top_clusters_phi_address0;
output   top_clusters_phi_ce0;
input  [5:0] top_clusters_phi_q0;
output  [2:0] top_clusters_valid_address0;
output   top_clusters_valid_ce0;
input  [0:0] top_clusters_valid_q0;
input  [4:0] candidate_eta;
input  [5:0] candidate_phi;
output  [2:0] j_out;
output   j_out_ap_vld;
output  [2:0] zext_ln128_out;
output   zext_ln128_out_ap_vld;
output  [2:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg j_out_ap_vld;
reg zext_ln128_out_ap_vld;
reg[2:0] ap_return;

(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [2:0] trunc_ln128_fu_182_p1;
reg   [2:0] trunc_ln128_reg_256;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln128_fu_186_p2;
reg   [0:0] icmp_ln128_reg_262;
wire   [3:0] add_ln128_fu_192_p2;
reg   [3:0] add_ln128_reg_266;
wire   [63:0] zext_ln128_fu_198_p1;
reg   [63:0] zext_ln128_reg_271;
reg   [0:0] top_clusters_valid_load_reg_283;
wire    ap_CS_fsm_state3;
reg   [2:0] b_eta_reg_292;
reg   [2:0] b_phi_reg_297;
wire   [0:0] icmp_ln78_fu_203_p2;
reg   [0:0] icmp_ln78_reg_302;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln82_fu_208_p2;
reg   [0:0] icmp_ln82_reg_306;
wire   [0:0] icmp_ln86_fu_213_p2;
reg   [0:0] icmp_ln86_reg_310;
wire    ap_CS_fsm_state5;
wire   [0:0] icmp_ln90_fu_218_p2;
reg   [0:0] icmp_ln90_reg_314;
reg   [2:0] ap_phi_mux_UnifiedRetVal_phi_fu_157_p10;
reg   [2:0] UnifiedRetVal_reg_150;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state7;
reg   [3:0] b_valid_fu_64;
wire    ap_CS_fsm_state6;
wire   [0:0] icmp_ln94_fu_223_p2;
reg    top_clusters_valid_ce0_local;
reg    top_clusters_et_ce0_local;
reg    top_clusters_eta_ce0_local;
reg    top_clusters_phi_ce0_local;
reg   [2:0] ap_return_preg;
reg   [10:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 11'd1;
#0 b_valid_fu_64 = 4'd0;
#0 ap_return_preg = 3'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 3'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            ap_return_preg <= ap_phi_mux_UnifiedRetVal_phi_fu_157_p10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln78_reg_302 == 1'd0) & (top_clusters_valid_load_reg_283 == 1'd1) & (icmp_ln128_reg_262 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (icmp_ln86_reg_310 == 1'd0))) begin
        UnifiedRetVal_reg_150 <= 3'd4;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        UnifiedRetVal_reg_150 <= 3'd3;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        UnifiedRetVal_reg_150 <= 3'd2;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        UnifiedRetVal_reg_150 <= 3'd1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        UnifiedRetVal_reg_150 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        b_valid_fu_64 <= 4'd0;
    end else if (((1'b1 == ap_CS_fsm_state6) & ((((icmp_ln78_reg_302 == 1'd0) & (top_clusters_valid_load_reg_283 == 1'd1) & (icmp_ln128_reg_262 == 1'd0) & (icmp_ln90_reg_314 == 1'd1) & (icmp_ln86_reg_310 == 1'd0)) | ((icmp_ln78_reg_302 == 1'd0) & (top_clusters_valid_load_reg_283 == 1'd1) & (icmp_ln128_reg_262 == 1'd0) & (icmp_ln94_fu_223_p2 == 1'd0) & (icmp_ln86_reg_310 == 1'd0))) | ((icmp_ln78_reg_302 == 1'd0) & (top_clusters_valid_load_reg_283 == 1'd1) & (icmp_ln128_reg_262 == 1'd0) & (icmp_ln82_reg_306 == 1'd1))))) begin
        b_valid_fu_64 <= add_ln128_reg_266;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln128_reg_266 <= add_ln128_fu_192_p2;
        icmp_ln128_reg_262 <= icmp_ln128_fu_186_p2;
        trunc_ln128_reg_256 <= trunc_ln128_fu_182_p1;
        zext_ln128_reg_271[3 : 0] <= zext_ln128_fu_198_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        b_eta_reg_292 <= zext_ln128_reg_271;
        b_phi_reg_297 <= zext_ln128_reg_271;
        top_clusters_valid_load_reg_283 <= top_clusters_valid_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        icmp_ln78_reg_302 <= icmp_ln78_fu_203_p2;
        icmp_ln82_reg_306 <= icmp_ln82_fu_208_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        icmp_ln86_reg_310 <= icmp_ln86_fu_213_p2;
        icmp_ln90_reg_314 <= icmp_ln90_fu_218_p2;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln78_reg_302 == 1'd0) & (top_clusters_valid_load_reg_283 == 1'd1) & (icmp_ln128_reg_262 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (icmp_ln86_reg_310 == 1'd0))) begin
        ap_phi_mux_UnifiedRetVal_phi_fu_157_p10 = 3'd4;
    end else begin
        ap_phi_mux_UnifiedRetVal_phi_fu_157_p10 = UnifiedRetVal_reg_150;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ap_return = ap_phi_mux_UnifiedRetVal_phi_fu_157_p10;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state11) | ((icmp_ln78_reg_302 == 1'd0) & (top_clusters_valid_load_reg_283 == 1'd1) & (icmp_ln128_reg_262 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (icmp_ln86_reg_310 == 1'd0)))) begin
        j_out_ap_vld = 1'b1;
    end else begin
        j_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        top_clusters_et_ce0_local = 1'b1;
    end else begin
        top_clusters_et_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        top_clusters_eta_ce0_local = 1'b1;
    end else begin
        top_clusters_eta_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        top_clusters_phi_ce0_local = 1'b1;
    end else begin
        top_clusters_phi_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        top_clusters_valid_ce0_local = 1'b1;
    end else begin
        top_clusters_valid_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | ((icmp_ln78_reg_302 == 1'd0) & (top_clusters_valid_load_reg_283 == 1'd1) & (icmp_ln128_reg_262 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (icmp_ln86_reg_310 == 1'd0)))) begin
        zext_ln128_out_ap_vld = 1'b1;
    end else begin
        zext_ln128_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & ((((icmp_ln78_reg_302 == 1'd0) & (top_clusters_valid_load_reg_283 == 1'd1) & (icmp_ln128_reg_262 == 1'd0) & (icmp_ln90_reg_314 == 1'd1) & (icmp_ln86_reg_310 == 1'd0)) | ((icmp_ln78_reg_302 == 1'd0) & (top_clusters_valid_load_reg_283 == 1'd1) & (icmp_ln128_reg_262 == 1'd0) & (icmp_ln94_fu_223_p2 == 1'd0) & (icmp_ln86_reg_310 == 1'd0))) | ((icmp_ln78_reg_302 == 1'd0) & (top_clusters_valid_load_reg_283 == 1'd1) & (icmp_ln128_reg_262 == 1'd0) & (icmp_ln82_reg_306 == 1'd1))))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if (((icmp_ln128_reg_262 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else if (((top_clusters_valid_load_reg_283 == 1'd0) & (icmp_ln128_reg_262 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else if (((icmp_ln78_reg_302 == 1'd1) & (top_clusters_valid_load_reg_283 == 1'd1) & (icmp_ln128_reg_262 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else if (((icmp_ln78_reg_302 == 1'd0) & (top_clusters_valid_load_reg_283 == 1'd1) & (icmp_ln128_reg_262 == 1'd0) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln86_reg_310 == 1'd1) & (icmp_ln82_reg_306 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln128_fu_192_p2 = (b_valid_fu_64 + 4'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign icmp_ln128_fu_186_p2 = ((b_valid_fu_64 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln78_fu_203_p2 = ((candidate_et > top_clusters_et_q0) ? 1'b1 : 1'b0);

assign icmp_ln82_fu_208_p2 = ((candidate_et < top_clusters_et_q0) ? 1'b1 : 1'b0);

assign icmp_ln86_fu_213_p2 = ((candidate_eta < top_clusters_eta_q0) ? 1'b1 : 1'b0);

assign icmp_ln90_fu_218_p2 = ((candidate_eta > top_clusters_eta_q0) ? 1'b1 : 1'b0);

assign icmp_ln94_fu_223_p2 = ((candidate_phi < top_clusters_phi_q0) ? 1'b1 : 1'b0);

assign j_out = trunc_ln128_reg_256;

assign top_clusters_et_address0 = zext_ln128_reg_271;

assign top_clusters_et_ce0 = top_clusters_et_ce0_local;

assign top_clusters_eta_address0 = b_eta_reg_292;

assign top_clusters_eta_ce0 = top_clusters_eta_ce0_local;

assign top_clusters_phi_address0 = b_phi_reg_297;

assign top_clusters_phi_ce0 = top_clusters_phi_ce0_local;

assign top_clusters_valid_address0 = zext_ln128_fu_198_p1;

assign top_clusters_valid_ce0 = top_clusters_valid_ce0_local;

assign trunc_ln128_fu_182_p1 = b_valid_fu_64[2:0];

assign zext_ln128_fu_198_p1 = b_valid_fu_64;

assign zext_ln128_out = trunc_ln128_reg_256;

always @ (posedge ap_clk) begin
    zext_ln128_reg_271[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
end

endmodule //calo_trigger_ref_select_top_n_Pipeline_VITIS_LOOP_128_3
