-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity calo_trigger_ref_select_top_n_Pipeline_VITIS_LOOP_128_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    candidate_et : IN STD_LOGIC_VECTOR (15 downto 0);
    top_clusters_et_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    top_clusters_et_ce0 : OUT STD_LOGIC;
    top_clusters_et_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    top_clusters_eta_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    top_clusters_eta_ce0 : OUT STD_LOGIC;
    top_clusters_eta_q0 : IN STD_LOGIC_VECTOR (4 downto 0);
    top_clusters_phi_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    top_clusters_phi_ce0 : OUT STD_LOGIC;
    top_clusters_phi_q0 : IN STD_LOGIC_VECTOR (5 downto 0);
    top_clusters_valid_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    top_clusters_valid_ce0 : OUT STD_LOGIC;
    top_clusters_valid_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
    candidate_eta : IN STD_LOGIC_VECTOR (4 downto 0);
    candidate_phi : IN STD_LOGIC_VECTOR (5 downto 0);
    j_out : OUT STD_LOGIC_VECTOR (2 downto 0);
    j_out_ap_vld : OUT STD_LOGIC;
    zext_ln128_out : OUT STD_LOGIC_VECTOR (2 downto 0);
    zext_ln128_out_ap_vld : OUT STD_LOGIC;
    ap_return : OUT STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of calo_trigger_ref_select_top_n_Pipeline_VITIS_LOOP_128_3 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (10 downto 0) := "00000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (10 downto 0) := "00000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (10 downto 0) := "00000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (10 downto 0) := "00000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (10 downto 0) := "00000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (10 downto 0) := "00001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (10 downto 0) := "00010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (10 downto 0) := "00100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (10 downto 0) := "01000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal trunc_ln128_fu_182_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln128_reg_256 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln128_fu_186_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln128_reg_262 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln128_fu_192_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln128_reg_266 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln128_fu_198_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln128_reg_271 : STD_LOGIC_VECTOR (63 downto 0);
    signal top_clusters_valid_load_reg_283 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal b_eta_reg_292 : STD_LOGIC_VECTOR (2 downto 0);
    signal b_phi_reg_297 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln78_fu_203_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln78_reg_302 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal icmp_ln82_fu_208_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln82_reg_306 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln86_fu_213_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln86_reg_310 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal icmp_ln90_fu_218_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln90_reg_314 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_UnifiedRetVal_phi_fu_157_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal UnifiedRetVal_reg_150 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal b_valid_fu_64 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal icmp_ln94_fu_223_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal top_clusters_valid_ce0_local : STD_LOGIC;
    signal top_clusters_et_ce0_local : STD_LOGIC;
    signal top_clusters_eta_ce0_local : STD_LOGIC;
    signal top_clusters_phi_ce0_local : STD_LOGIC;
    signal ap_return_preg : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_return_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_preg <= ap_const_lv3_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                    ap_return_preg <= ap_phi_mux_UnifiedRetVal_phi_fu_157_p10;
                end if; 
            end if;
        end if;
    end process;


    UnifiedRetVal_reg_150_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln78_reg_302 = ap_const_lv1_0) and (top_clusters_valid_load_reg_283 = ap_const_lv1_1) and (icmp_ln128_reg_262 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln86_reg_310 = ap_const_lv1_0))) then 
                UnifiedRetVal_reg_150 <= ap_const_lv3_4;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                UnifiedRetVal_reg_150 <= ap_const_lv3_3;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
                UnifiedRetVal_reg_150 <= ap_const_lv3_2;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                UnifiedRetVal_reg_150 <= ap_const_lv3_1;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                UnifiedRetVal_reg_150 <= ap_const_lv3_0;
            end if; 
        end if;
    end process;

    b_valid_fu_64_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                b_valid_fu_64 <= ap_const_lv4_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state6) and ((((icmp_ln78_reg_302 = ap_const_lv1_0) and (top_clusters_valid_load_reg_283 = ap_const_lv1_1) and (icmp_ln128_reg_262 = ap_const_lv1_0) and (icmp_ln90_reg_314 = ap_const_lv1_1) and (icmp_ln86_reg_310 = ap_const_lv1_0)) or ((icmp_ln78_reg_302 = ap_const_lv1_0) and (top_clusters_valid_load_reg_283 = ap_const_lv1_1) and (icmp_ln128_reg_262 = ap_const_lv1_0) and (icmp_ln94_fu_223_p2 = ap_const_lv1_0) and (icmp_ln86_reg_310 = ap_const_lv1_0))) or ((icmp_ln78_reg_302 = ap_const_lv1_0) and (top_clusters_valid_load_reg_283 = ap_const_lv1_1) and (icmp_ln128_reg_262 = ap_const_lv1_0) and (icmp_ln82_reg_306 = ap_const_lv1_1))))) then 
                b_valid_fu_64 <= add_ln128_reg_266;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln128_reg_266 <= add_ln128_fu_192_p2;
                icmp_ln128_reg_262 <= icmp_ln128_fu_186_p2;
                trunc_ln128_reg_256 <= trunc_ln128_fu_182_p1;
                    zext_ln128_reg_271(3 downto 0) <= zext_ln128_fu_198_p1(3 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                b_eta_reg_292 <= zext_ln128_reg_271(3 - 1 downto 0);
                b_phi_reg_297 <= zext_ln128_reg_271(3 - 1 downto 0);
                top_clusters_valid_load_reg_283 <= top_clusters_valid_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                icmp_ln78_reg_302 <= icmp_ln78_fu_203_p2;
                icmp_ln82_reg_306 <= icmp_ln82_fu_208_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                icmp_ln86_reg_310 <= icmp_ln86_fu_213_p2;
                icmp_ln90_reg_314 <= icmp_ln90_fu_218_p2;
            end if;
        end if;
    end process;
    zext_ln128_reg_271(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, icmp_ln128_reg_262, top_clusters_valid_load_reg_283, icmp_ln78_reg_302, icmp_ln82_reg_306, icmp_ln86_reg_310, icmp_ln90_reg_314, ap_CS_fsm_state6, icmp_ln94_fu_223_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and ((((icmp_ln78_reg_302 = ap_const_lv1_0) and (top_clusters_valid_load_reg_283 = ap_const_lv1_1) and (icmp_ln128_reg_262 = ap_const_lv1_0) and (icmp_ln90_reg_314 = ap_const_lv1_1) and (icmp_ln86_reg_310 = ap_const_lv1_0)) or ((icmp_ln78_reg_302 = ap_const_lv1_0) and (top_clusters_valid_load_reg_283 = ap_const_lv1_1) and (icmp_ln128_reg_262 = ap_const_lv1_0) and (icmp_ln94_fu_223_p2 = ap_const_lv1_0) and (icmp_ln86_reg_310 = ap_const_lv1_0))) or ((icmp_ln78_reg_302 = ap_const_lv1_0) and (top_clusters_valid_load_reg_283 = ap_const_lv1_1) and (icmp_ln128_reg_262 = ap_const_lv1_0) and (icmp_ln82_reg_306 = ap_const_lv1_1))))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                elsif (((icmp_ln128_reg_262 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                elsif (((top_clusters_valid_load_reg_283 = ap_const_lv1_0) and (icmp_ln128_reg_262 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                elsif (((icmp_ln78_reg_302 = ap_const_lv1_1) and (top_clusters_valid_load_reg_283 = ap_const_lv1_1) and (icmp_ln128_reg_262 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                elsif (((icmp_ln78_reg_302 = ap_const_lv1_0) and (top_clusters_valid_load_reg_283 = ap_const_lv1_1) and (icmp_ln128_reg_262 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln86_reg_310 = ap_const_lv1_1) and (icmp_ln82_reg_306 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXX";
        end case;
    end process;
    add_ln128_fu_192_p2 <= std_logic_vector(unsigned(b_valid_fu_64) + unsigned(ap_const_lv4_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_UnifiedRetVal_phi_fu_157_p10_assign_proc : process(icmp_ln128_reg_262, top_clusters_valid_load_reg_283, icmp_ln78_reg_302, icmp_ln86_reg_310, UnifiedRetVal_reg_150, ap_CS_fsm_state7)
    begin
        if (((icmp_ln78_reg_302 = ap_const_lv1_0) and (top_clusters_valid_load_reg_283 = ap_const_lv1_1) and (icmp_ln128_reg_262 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln86_reg_310 = ap_const_lv1_0))) then 
            ap_phi_mux_UnifiedRetVal_phi_fu_157_p10 <= ap_const_lv3_4;
        else 
            ap_phi_mux_UnifiedRetVal_phi_fu_157_p10 <= UnifiedRetVal_reg_150;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_assign_proc : process(ap_phi_mux_UnifiedRetVal_phi_fu_157_p10, ap_CS_fsm_state7, ap_return_preg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            ap_return <= ap_phi_mux_UnifiedRetVal_phi_fu_157_p10;
        else 
            ap_return <= ap_return_preg;
        end if; 
    end process;

    icmp_ln128_fu_186_p2 <= "1" when (b_valid_fu_64 = ap_const_lv4_8) else "0";
    icmp_ln78_fu_203_p2 <= "1" when (unsigned(candidate_et) > unsigned(top_clusters_et_q0)) else "0";
    icmp_ln82_fu_208_p2 <= "1" when (unsigned(candidate_et) < unsigned(top_clusters_et_q0)) else "0";
    icmp_ln86_fu_213_p2 <= "1" when (unsigned(candidate_eta) < unsigned(top_clusters_eta_q0)) else "0";
    icmp_ln90_fu_218_p2 <= "1" when (unsigned(candidate_eta) > unsigned(top_clusters_eta_q0)) else "0";
    icmp_ln94_fu_223_p2 <= "1" when (unsigned(candidate_phi) < unsigned(top_clusters_phi_q0)) else "0";
    j_out <= trunc_ln128_reg_256;

    j_out_ap_vld_assign_proc : process(icmp_ln128_reg_262, top_clusters_valid_load_reg_283, icmp_ln78_reg_302, icmp_ln86_reg_310, ap_CS_fsm_state11, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state8, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state11) or ((icmp_ln78_reg_302 = ap_const_lv1_0) and (top_clusters_valid_load_reg_283 = ap_const_lv1_1) and (icmp_ln128_reg_262 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln86_reg_310 = ap_const_lv1_0)))) then 
            j_out_ap_vld <= ap_const_logic_1;
        else 
            j_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    top_clusters_et_address0 <= zext_ln128_reg_271(3 - 1 downto 0);
    top_clusters_et_ce0 <= top_clusters_et_ce0_local;

    top_clusters_et_ce0_local_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            top_clusters_et_ce0_local <= ap_const_logic_1;
        else 
            top_clusters_et_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    top_clusters_eta_address0 <= b_eta_reg_292;
    top_clusters_eta_ce0 <= top_clusters_eta_ce0_local;

    top_clusters_eta_ce0_local_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            top_clusters_eta_ce0_local <= ap_const_logic_1;
        else 
            top_clusters_eta_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    top_clusters_phi_address0 <= b_phi_reg_297;
    top_clusters_phi_ce0 <= top_clusters_phi_ce0_local;

    top_clusters_phi_ce0_local_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            top_clusters_phi_ce0_local <= ap_const_logic_1;
        else 
            top_clusters_phi_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    top_clusters_valid_address0 <= zext_ln128_fu_198_p1(3 - 1 downto 0);
    top_clusters_valid_ce0 <= top_clusters_valid_ce0_local;

    top_clusters_valid_ce0_local_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            top_clusters_valid_ce0_local <= ap_const_logic_1;
        else 
            top_clusters_valid_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln128_fu_182_p1 <= b_valid_fu_64(3 - 1 downto 0);
    zext_ln128_fu_198_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b_valid_fu_64),64));
    zext_ln128_out <= trunc_ln128_reg_256;

    zext_ln128_out_ap_vld_assign_proc : process(icmp_ln128_reg_262, top_clusters_valid_load_reg_283, icmp_ln78_reg_302, icmp_ln86_reg_310, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state8, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9) or ((icmp_ln78_reg_302 = ap_const_lv1_0) and (top_clusters_valid_load_reg_283 = ap_const_lv1_1) and (icmp_ln128_reg_262 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln86_reg_310 = ap_const_lv1_0)))) then 
            zext_ln128_out_ap_vld <= ap_const_logic_1;
        else 
            zext_ln128_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

end behav;
