// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module calo_trigger_ref_select_top_n (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        clusters_et_address0,
        clusters_et_ce0,
        clusters_et_q0,
        clusters_isolation_et_address0,
        clusters_isolation_et_ce0,
        clusters_isolation_et_q0,
        clusters_eta_address0,
        clusters_eta_ce0,
        clusters_eta_q0,
        clusters_phi_address0,
        clusters_phi_ce0,
        clusters_phi_q0,
        clusters_window_size_address0,
        clusters_window_size_ce0,
        clusters_window_size_q0,
        clusters_iso_outer_size_address0,
        clusters_iso_outer_size_ce0,
        clusters_iso_outer_size_q0,
        clusters_valid_address0,
        clusters_valid_ce0,
        clusters_valid_q0,
        num_clusters,
        top_clusters_et_address0,
        top_clusters_et_ce0,
        top_clusters_et_we0,
        top_clusters_et_d0,
        top_clusters_et_q0,
        top_clusters_et_address1,
        top_clusters_et_ce1,
        top_clusters_et_q1,
        top_clusters_isolation_et_address0,
        top_clusters_isolation_et_ce0,
        top_clusters_isolation_et_we0,
        top_clusters_isolation_et_d0,
        top_clusters_isolation_et_address1,
        top_clusters_isolation_et_ce1,
        top_clusters_isolation_et_q1,
        top_clusters_eta_address0,
        top_clusters_eta_ce0,
        top_clusters_eta_we0,
        top_clusters_eta_d0,
        top_clusters_eta_q0,
        top_clusters_eta_address1,
        top_clusters_eta_ce1,
        top_clusters_eta_q1,
        top_clusters_phi_address0,
        top_clusters_phi_ce0,
        top_clusters_phi_we0,
        top_clusters_phi_d0,
        top_clusters_phi_q0,
        top_clusters_phi_address1,
        top_clusters_phi_ce1,
        top_clusters_phi_q1,
        top_clusters_window_size_address0,
        top_clusters_window_size_ce0,
        top_clusters_window_size_we0,
        top_clusters_window_size_d0,
        top_clusters_window_size_address1,
        top_clusters_window_size_ce1,
        top_clusters_window_size_q1,
        top_clusters_iso_outer_size_address0,
        top_clusters_iso_outer_size_ce0,
        top_clusters_iso_outer_size_we0,
        top_clusters_iso_outer_size_d0,
        top_clusters_iso_outer_size_address1,
        top_clusters_iso_outer_size_ce1,
        top_clusters_iso_outer_size_q1,
        top_clusters_valid_address0,
        top_clusters_valid_ce0,
        top_clusters_valid_we0,
        top_clusters_valid_d0,
        top_clusters_valid_q0,
        top_clusters_valid_address1,
        top_clusters_valid_ce1,
        top_clusters_valid_q1
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_state8 = 9'd128;
parameter    ap_ST_fsm_state9 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [10:0] clusters_et_address0;
output   clusters_et_ce0;
input  [15:0] clusters_et_q0;
output  [10:0] clusters_isolation_et_address0;
output   clusters_isolation_et_ce0;
input  [17:0] clusters_isolation_et_q0;
output  [10:0] clusters_eta_address0;
output   clusters_eta_ce0;
input  [4:0] clusters_eta_q0;
output  [10:0] clusters_phi_address0;
output   clusters_phi_ce0;
input  [5:0] clusters_phi_q0;
output  [10:0] clusters_window_size_address0;
output   clusters_window_size_ce0;
input  [0:0] clusters_window_size_q0;
output  [10:0] clusters_iso_outer_size_address0;
output   clusters_iso_outer_size_ce0;
input  [2:0] clusters_iso_outer_size_q0;
output  [10:0] clusters_valid_address0;
output   clusters_valid_ce0;
input  [0:0] clusters_valid_q0;
input  [31:0] num_clusters;
output  [2:0] top_clusters_et_address0;
output   top_clusters_et_ce0;
output   top_clusters_et_we0;
output  [15:0] top_clusters_et_d0;
input  [15:0] top_clusters_et_q0;
output  [2:0] top_clusters_et_address1;
output   top_clusters_et_ce1;
input  [15:0] top_clusters_et_q1;
output  [2:0] top_clusters_isolation_et_address0;
output   top_clusters_isolation_et_ce0;
output   top_clusters_isolation_et_we0;
output  [17:0] top_clusters_isolation_et_d0;
output  [2:0] top_clusters_isolation_et_address1;
output   top_clusters_isolation_et_ce1;
input  [17:0] top_clusters_isolation_et_q1;
output  [2:0] top_clusters_eta_address0;
output   top_clusters_eta_ce0;
output   top_clusters_eta_we0;
output  [4:0] top_clusters_eta_d0;
input  [4:0] top_clusters_eta_q0;
output  [2:0] top_clusters_eta_address1;
output   top_clusters_eta_ce1;
input  [4:0] top_clusters_eta_q1;
output  [2:0] top_clusters_phi_address0;
output   top_clusters_phi_ce0;
output   top_clusters_phi_we0;
output  [5:0] top_clusters_phi_d0;
input  [5:0] top_clusters_phi_q0;
output  [2:0] top_clusters_phi_address1;
output   top_clusters_phi_ce1;
input  [5:0] top_clusters_phi_q1;
output  [2:0] top_clusters_window_size_address0;
output   top_clusters_window_size_ce0;
output   top_clusters_window_size_we0;
output  [1:0] top_clusters_window_size_d0;
output  [2:0] top_clusters_window_size_address1;
output   top_clusters_window_size_ce1;
input  [1:0] top_clusters_window_size_q1;
output  [2:0] top_clusters_iso_outer_size_address0;
output   top_clusters_iso_outer_size_ce0;
output   top_clusters_iso_outer_size_we0;
output  [2:0] top_clusters_iso_outer_size_d0;
output  [2:0] top_clusters_iso_outer_size_address1;
output   top_clusters_iso_outer_size_ce1;
input  [2:0] top_clusters_iso_outer_size_q1;
output  [2:0] top_clusters_valid_address0;
output   top_clusters_valid_ce0;
output   top_clusters_valid_we0;
output  [0:0] top_clusters_valid_d0;
input  [0:0] top_clusters_valid_q0;
output  [2:0] top_clusters_valid_address1;
output   top_clusters_valid_ce1;
input  [0:0] top_clusters_valid_q1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[2:0] top_clusters_et_address0;
reg top_clusters_et_ce0;
reg top_clusters_et_we0;
reg[15:0] top_clusters_et_d0;
reg top_clusters_et_ce1;
reg[2:0] top_clusters_isolation_et_address0;
reg top_clusters_isolation_et_ce0;
reg top_clusters_isolation_et_we0;
reg[17:0] top_clusters_isolation_et_d0;
reg top_clusters_isolation_et_ce1;
reg[2:0] top_clusters_eta_address0;
reg top_clusters_eta_ce0;
reg top_clusters_eta_we0;
reg[4:0] top_clusters_eta_d0;
reg top_clusters_eta_ce1;
reg[2:0] top_clusters_phi_address0;
reg top_clusters_phi_ce0;
reg top_clusters_phi_we0;
reg[5:0] top_clusters_phi_d0;
reg top_clusters_phi_ce1;
reg[2:0] top_clusters_window_size_address0;
reg top_clusters_window_size_ce0;
reg top_clusters_window_size_we0;
reg[1:0] top_clusters_window_size_d0;
reg top_clusters_window_size_ce1;
reg[2:0] top_clusters_iso_outer_size_address0;
reg top_clusters_iso_outer_size_ce0;
reg top_clusters_iso_outer_size_we0;
reg[2:0] top_clusters_iso_outer_size_d0;
reg top_clusters_iso_outer_size_ce1;
reg[2:0] top_clusters_valid_address0;
reg top_clusters_valid_ce0;
reg top_clusters_valid_we0;
reg[0:0] top_clusters_valid_d0;
reg top_clusters_valid_ce1;

(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    ap_CS_fsm_state2;
wire   [10:0] add_ln118_fu_338_p2;
reg   [10:0] add_ln118_reg_422;
wire    ap_CS_fsm_state3;
wire   [63:0] zext_ln118_fu_344_p1;
reg   [63:0] zext_ln118_reg_427;
wire   [0:0] icmp_ln119_fu_353_p2;
reg   [0:0] icmp_ln119_reg_437;
wire   [0:0] clusters_valid_q0_local;
reg   [0:0] clusters_valid_load_reg_446;
wire    ap_CS_fsm_state4;
reg   [15:0] candidate_et_reg_480;
wire    ap_CS_fsm_state5;
reg   [17:0] candidate_isolation_et_reg_486;
reg   [4:0] candidate_eta_reg_491;
reg   [5:0] candidate_phi_reg_497;
reg   [0:0] candidate_window_size_reg_503;
reg   [2:0] candidate_iso_outer_size_reg_508;
wire   [0:0] cond_fu_358_p2;
reg   [0:0] cond_reg_513;
wire    ap_CS_fsm_state6;
wire   [1:0] select_ln126_fu_364_p3;
reg   [1:0] select_ln126_reg_517;
wire    ap_CS_fsm_state7;
wire   [63:0] zext_ln128_reload_cast_fu_378_p1;
reg   [63:0] zext_ln128_reload_cast_reg_525;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_ap_start;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_ap_done;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_ap_idle;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_ap_ready;
wire   [2:0] grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_et_address0;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_et_ce0;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_et_we0;
wire   [15:0] grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_et_d0;
wire   [2:0] grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_isolation_et_address0;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_isolation_et_ce0;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_isolation_et_we0;
wire   [17:0] grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_isolation_et_d0;
wire   [2:0] grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_eta_address0;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_eta_ce0;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_eta_we0;
wire   [4:0] grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_eta_d0;
wire   [2:0] grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_phi_address0;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_phi_ce0;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_phi_we0;
wire   [5:0] grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_phi_d0;
wire   [2:0] grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_window_size_address0;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_window_size_ce0;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_window_size_we0;
wire   [1:0] grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_window_size_d0;
wire   [2:0] grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_iso_outer_size_address0;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_iso_outer_size_ce0;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_iso_outer_size_we0;
wire   [2:0] grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_iso_outer_size_d0;
wire   [2:0] grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_valid_address0;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_valid_ce0;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_valid_we0;
wire   [0:0] grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_valid_d0;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_ap_start;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_ap_done;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_ap_idle;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_ap_ready;
wire   [2:0] grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_top_clusters_et_address0;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_top_clusters_et_ce0;
wire   [2:0] grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_top_clusters_eta_address0;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_top_clusters_eta_ce0;
wire   [2:0] grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_top_clusters_phi_address0;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_top_clusters_phi_ce0;
wire   [2:0] grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_top_clusters_valid_address0;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_top_clusters_valid_ce0;
wire   [2:0] grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_j_out;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_j_out_ap_vld;
wire   [2:0] grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_zext_ln128_out;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_zext_ln128_out_ap_vld;
wire   [2:0] grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_ap_return;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_ap_start;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_ap_done;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_ap_idle;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_ap_ready;
wire   [2:0] grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_et_address0;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_et_ce0;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_et_we0;
wire   [15:0] grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_et_d0;
wire   [2:0] grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_et_address1;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_et_ce1;
wire   [2:0] grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_isolation_et_address0;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_isolation_et_ce0;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_isolation_et_we0;
wire   [17:0] grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_isolation_et_d0;
wire   [2:0] grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_isolation_et_address1;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_isolation_et_ce1;
wire   [2:0] grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_eta_address0;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_eta_ce0;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_eta_we0;
wire   [4:0] grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_eta_d0;
wire   [2:0] grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_eta_address1;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_eta_ce1;
wire   [2:0] grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_phi_address0;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_phi_ce0;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_phi_we0;
wire   [5:0] grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_phi_d0;
wire   [2:0] grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_phi_address1;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_phi_ce1;
wire   [2:0] grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_window_size_address0;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_window_size_ce0;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_window_size_we0;
wire   [1:0] grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_window_size_d0;
wire   [2:0] grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_window_size_address1;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_window_size_ce1;
wire   [2:0] grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_iso_outer_size_address0;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_iso_outer_size_ce0;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_iso_outer_size_we0;
wire   [2:0] grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_iso_outer_size_d0;
wire   [2:0] grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_iso_outer_size_address1;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_iso_outer_size_ce1;
wire   [2:0] grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_valid_address0;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_valid_ce0;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_valid_we0;
wire   [0:0] grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_valid_d0;
wire   [2:0] grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_valid_address1;
wire    grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_valid_ce1;
reg    grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_ap_start_reg;
reg    grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_ap_start_reg;
reg   [2:0] j_loc_fu_74;
reg   [2:0] zext_ln128_loc_fu_70;
reg    grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_ap_start_reg;
wire    ap_CS_fsm_state8;
wire   [0:0] icmp_ln118_fu_332_p2;
wire    ap_CS_fsm_state9;
wire   [63:0] zext_ln128_fu_382_p1;
reg   [10:0] i_1_fu_66;
reg    clusters_valid_ce0_local;
reg    clusters_et_ce0_local;
reg    clusters_isolation_et_ce0_local;
reg    clusters_eta_ce0_local;
reg    clusters_phi_ce0_local;
reg    clusters_window_size_ce0_local;
reg    clusters_iso_outer_size_ce0_local;
reg    top_clusters_et_we0_local;
reg    top_clusters_et_ce0_local;
reg    top_clusters_isolation_et_we0_local;
reg    top_clusters_isolation_et_ce0_local;
reg    top_clusters_eta_we0_local;
reg    top_clusters_eta_ce0_local;
reg    top_clusters_phi_we0_local;
reg    top_clusters_phi_ce0_local;
reg    top_clusters_window_size_we0_local;
reg    top_clusters_window_size_ce0_local;
reg    top_clusters_iso_outer_size_we0_local;
reg    top_clusters_iso_outer_size_ce0_local;
reg    top_clusters_valid_we0_local;
reg    top_clusters_valid_ce0_local;
wire   [31:0] zext_ln118_1_fu_349_p1;
reg   [8:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'd1;
#0 grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_ap_start_reg = 1'b0;
#0 grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_ap_start_reg = 1'b0;
#0 grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_ap_start_reg = 1'b0;
#0 i_1_fu_66 = 11'd0;
end

calo_trigger_ref_select_top_n_Pipeline_VITIS_LOOP_108_1 grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_ap_start),
    .ap_done(grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_ap_done),
    .ap_idle(grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_ap_idle),
    .ap_ready(grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_ap_ready),
    .top_clusters_et_address0(grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_et_address0),
    .top_clusters_et_ce0(grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_et_ce0),
    .top_clusters_et_we0(grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_et_we0),
    .top_clusters_et_d0(grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_et_d0),
    .top_clusters_isolation_et_address0(grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_isolation_et_address0),
    .top_clusters_isolation_et_ce0(grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_isolation_et_ce0),
    .top_clusters_isolation_et_we0(grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_isolation_et_we0),
    .top_clusters_isolation_et_d0(grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_isolation_et_d0),
    .top_clusters_eta_address0(grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_eta_address0),
    .top_clusters_eta_ce0(grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_eta_ce0),
    .top_clusters_eta_we0(grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_eta_we0),
    .top_clusters_eta_d0(grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_eta_d0),
    .top_clusters_phi_address0(grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_phi_address0),
    .top_clusters_phi_ce0(grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_phi_ce0),
    .top_clusters_phi_we0(grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_phi_we0),
    .top_clusters_phi_d0(grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_phi_d0),
    .top_clusters_window_size_address0(grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_window_size_address0),
    .top_clusters_window_size_ce0(grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_window_size_ce0),
    .top_clusters_window_size_we0(grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_window_size_we0),
    .top_clusters_window_size_d0(grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_window_size_d0),
    .top_clusters_iso_outer_size_address0(grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_iso_outer_size_address0),
    .top_clusters_iso_outer_size_ce0(grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_iso_outer_size_ce0),
    .top_clusters_iso_outer_size_we0(grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_iso_outer_size_we0),
    .top_clusters_iso_outer_size_d0(grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_iso_outer_size_d0),
    .top_clusters_valid_address0(grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_valid_address0),
    .top_clusters_valid_ce0(grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_valid_ce0),
    .top_clusters_valid_we0(grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_valid_we0),
    .top_clusters_valid_d0(grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_valid_d0)
);

calo_trigger_ref_select_top_n_Pipeline_VITIS_LOOP_128_3 grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_ap_start),
    .ap_done(grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_ap_done),
    .ap_idle(grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_ap_idle),
    .ap_ready(grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_ap_ready),
    .candidate_et(candidate_et_reg_480),
    .top_clusters_et_address0(grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_top_clusters_et_address0),
    .top_clusters_et_ce0(grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_top_clusters_et_ce0),
    .top_clusters_et_q0(top_clusters_et_q0),
    .top_clusters_eta_address0(grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_top_clusters_eta_address0),
    .top_clusters_eta_ce0(grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_top_clusters_eta_ce0),
    .top_clusters_eta_q0(top_clusters_eta_q0),
    .top_clusters_phi_address0(grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_top_clusters_phi_address0),
    .top_clusters_phi_ce0(grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_top_clusters_phi_ce0),
    .top_clusters_phi_q0(top_clusters_phi_q0),
    .top_clusters_valid_address0(grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_top_clusters_valid_address0),
    .top_clusters_valid_ce0(grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_top_clusters_valid_ce0),
    .top_clusters_valid_q0(top_clusters_valid_q0),
    .candidate_eta(candidate_eta_reg_491),
    .candidate_phi(candidate_phi_reg_497),
    .j_out(grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_j_out),
    .j_out_ap_vld(grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_j_out_ap_vld),
    .zext_ln128_out(grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_zext_ln128_out),
    .zext_ln128_out_ap_vld(grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_zext_ln128_out_ap_vld),
    .ap_return(grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_ap_return)
);

calo_trigger_ref_select_top_n_Pipeline_VITIS_LOOP_131_4 grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_ap_start),
    .ap_done(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_ap_done),
    .ap_idle(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_ap_idle),
    .ap_ready(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_ap_ready),
    .empty(j_loc_fu_74),
    .top_clusters_et_address0(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_et_address0),
    .top_clusters_et_ce0(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_et_ce0),
    .top_clusters_et_we0(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_et_we0),
    .top_clusters_et_d0(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_et_d0),
    .top_clusters_et_address1(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_et_address1),
    .top_clusters_et_ce1(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_et_ce1),
    .top_clusters_et_q1(top_clusters_et_q1),
    .top_clusters_isolation_et_address0(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_isolation_et_address0),
    .top_clusters_isolation_et_ce0(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_isolation_et_ce0),
    .top_clusters_isolation_et_we0(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_isolation_et_we0),
    .top_clusters_isolation_et_d0(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_isolation_et_d0),
    .top_clusters_isolation_et_address1(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_isolation_et_address1),
    .top_clusters_isolation_et_ce1(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_isolation_et_ce1),
    .top_clusters_isolation_et_q1(top_clusters_isolation_et_q1),
    .top_clusters_eta_address0(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_eta_address0),
    .top_clusters_eta_ce0(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_eta_ce0),
    .top_clusters_eta_we0(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_eta_we0),
    .top_clusters_eta_d0(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_eta_d0),
    .top_clusters_eta_address1(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_eta_address1),
    .top_clusters_eta_ce1(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_eta_ce1),
    .top_clusters_eta_q1(top_clusters_eta_q1),
    .top_clusters_phi_address0(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_phi_address0),
    .top_clusters_phi_ce0(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_phi_ce0),
    .top_clusters_phi_we0(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_phi_we0),
    .top_clusters_phi_d0(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_phi_d0),
    .top_clusters_phi_address1(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_phi_address1),
    .top_clusters_phi_ce1(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_phi_ce1),
    .top_clusters_phi_q1(top_clusters_phi_q1),
    .top_clusters_window_size_address0(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_window_size_address0),
    .top_clusters_window_size_ce0(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_window_size_ce0),
    .top_clusters_window_size_we0(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_window_size_we0),
    .top_clusters_window_size_d0(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_window_size_d0),
    .top_clusters_window_size_address1(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_window_size_address1),
    .top_clusters_window_size_ce1(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_window_size_ce1),
    .top_clusters_window_size_q1(top_clusters_window_size_q1),
    .top_clusters_iso_outer_size_address0(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_iso_outer_size_address0),
    .top_clusters_iso_outer_size_ce0(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_iso_outer_size_ce0),
    .top_clusters_iso_outer_size_we0(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_iso_outer_size_we0),
    .top_clusters_iso_outer_size_d0(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_iso_outer_size_d0),
    .top_clusters_iso_outer_size_address1(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_iso_outer_size_address1),
    .top_clusters_iso_outer_size_ce1(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_iso_outer_size_ce1),
    .top_clusters_iso_outer_size_q1(top_clusters_iso_outer_size_q1),
    .top_clusters_valid_address0(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_valid_address0),
    .top_clusters_valid_ce0(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_valid_ce0),
    .top_clusters_valid_we0(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_valid_we0),
    .top_clusters_valid_d0(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_valid_d0),
    .top_clusters_valid_address1(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_valid_address1),
    .top_clusters_valid_ce1(grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_valid_ce1),
    .top_clusters_valid_q1(top_clusters_valid_q1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_ap_start_reg <= 1'b1;
        end else if ((grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_ap_ready == 1'b1)) begin
            grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_ap_start_reg <= 1'b1;
        end else if ((grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_ap_ready == 1'b1)) begin
            grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_ap_start_reg <= 1'b0;
    end else begin
        if (((cond_reg_513 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
            grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_ap_start_reg <= 1'b1;
        end else if ((grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_ap_ready == 1'b1)) begin
            grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_1_fu_66 <= 11'd0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        i_1_fu_66 <= add_ln118_reg_422;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln118_reg_422 <= add_ln118_fu_338_p2;
        icmp_ln119_reg_437 <= icmp_ln119_fu_353_p2;
        zext_ln118_reg_427[10 : 0] <= zext_ln118_fu_344_p1[10 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        candidate_et_reg_480 <= clusters_et_q0;
        candidate_eta_reg_491 <= clusters_eta_q0;
        candidate_iso_outer_size_reg_508 <= clusters_iso_outer_size_q0;
        candidate_isolation_et_reg_486 <= clusters_isolation_et_q0;
        candidate_phi_reg_497 <= clusters_phi_q0;
        candidate_window_size_reg_503 <= clusters_window_size_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        clusters_valid_load_reg_446 <= clusters_valid_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        cond_reg_513 <= cond_fu_358_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_j_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        j_loc_fu_74 <= grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_j_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        select_ln126_reg_517 <= select_ln126_fu_364_p3;
        zext_ln128_reload_cast_reg_525[2 : 0] <= zext_ln128_reload_cast_fu_378_p1[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_zext_ln128_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        zext_ln128_loc_fu_70 <= grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_zext_ln128_out;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((icmp_ln118_fu_332_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln118_fu_332_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        clusters_et_ce0_local = 1'b1;
    end else begin
        clusters_et_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        clusters_eta_ce0_local = 1'b1;
    end else begin
        clusters_eta_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        clusters_iso_outer_size_ce0_local = 1'b1;
    end else begin
        clusters_iso_outer_size_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        clusters_isolation_et_ce0_local = 1'b1;
    end else begin
        clusters_isolation_et_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        clusters_phi_ce0_local = 1'b1;
    end else begin
        clusters_phi_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        clusters_valid_ce0_local = 1'b1;
    end else begin
        clusters_valid_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        clusters_window_size_ce0_local = 1'b1;
    end else begin
        clusters_window_size_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        top_clusters_et_address0 = grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_et_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        top_clusters_et_address0 = grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_top_clusters_et_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        top_clusters_et_address0 = grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_et_address0;
    end else begin
        top_clusters_et_address0 = zext_ln128_fu_382_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        top_clusters_et_ce0 = grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_et_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        top_clusters_et_ce0 = grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_top_clusters_et_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        top_clusters_et_ce0 = grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_et_ce0;
    end else begin
        top_clusters_et_ce0 = top_clusters_et_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        top_clusters_et_ce0_local = 1'b1;
    end else begin
        top_clusters_et_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        top_clusters_et_ce1 = grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_et_ce1;
    end else begin
        top_clusters_et_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        top_clusters_et_d0 = grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_et_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        top_clusters_et_d0 = grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_et_d0;
    end else begin
        top_clusters_et_d0 = candidate_et_reg_480;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        top_clusters_et_we0 = grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_et_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        top_clusters_et_we0 = grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_et_we0;
    end else begin
        top_clusters_et_we0 = top_clusters_et_we0_local;
    end
end

always @ (*) begin
    if (((cond_reg_513 == 1'd0) & (1'b1 == ap_CS_fsm_state9) & (clusters_valid_load_reg_446 == 1'd1) & (icmp_ln119_reg_437 == 1'd1))) begin
        top_clusters_et_we0_local = 1'b1;
    end else begin
        top_clusters_et_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        top_clusters_eta_address0 = grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_eta_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        top_clusters_eta_address0 = grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_top_clusters_eta_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        top_clusters_eta_address0 = grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_eta_address0;
    end else begin
        top_clusters_eta_address0 = zext_ln128_fu_382_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        top_clusters_eta_ce0 = grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_eta_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        top_clusters_eta_ce0 = grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_top_clusters_eta_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        top_clusters_eta_ce0 = grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_eta_ce0;
    end else begin
        top_clusters_eta_ce0 = top_clusters_eta_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        top_clusters_eta_ce0_local = 1'b1;
    end else begin
        top_clusters_eta_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        top_clusters_eta_ce1 = grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_eta_ce1;
    end else begin
        top_clusters_eta_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        top_clusters_eta_d0 = grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_eta_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        top_clusters_eta_d0 = grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_eta_d0;
    end else begin
        top_clusters_eta_d0 = candidate_eta_reg_491;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        top_clusters_eta_we0 = grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_eta_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        top_clusters_eta_we0 = grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_eta_we0;
    end else begin
        top_clusters_eta_we0 = top_clusters_eta_we0_local;
    end
end

always @ (*) begin
    if (((cond_reg_513 == 1'd0) & (1'b1 == ap_CS_fsm_state9) & (clusters_valid_load_reg_446 == 1'd1) & (icmp_ln119_reg_437 == 1'd1))) begin
        top_clusters_eta_we0_local = 1'b1;
    end else begin
        top_clusters_eta_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        top_clusters_iso_outer_size_address0 = grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_iso_outer_size_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        top_clusters_iso_outer_size_address0 = grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_iso_outer_size_address0;
    end else begin
        top_clusters_iso_outer_size_address0 = zext_ln128_fu_382_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        top_clusters_iso_outer_size_ce0 = grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_iso_outer_size_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        top_clusters_iso_outer_size_ce0 = grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_iso_outer_size_ce0;
    end else begin
        top_clusters_iso_outer_size_ce0 = top_clusters_iso_outer_size_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        top_clusters_iso_outer_size_ce0_local = 1'b1;
    end else begin
        top_clusters_iso_outer_size_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        top_clusters_iso_outer_size_ce1 = grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_iso_outer_size_ce1;
    end else begin
        top_clusters_iso_outer_size_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        top_clusters_iso_outer_size_d0 = grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_iso_outer_size_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        top_clusters_iso_outer_size_d0 = grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_iso_outer_size_d0;
    end else begin
        top_clusters_iso_outer_size_d0 = candidate_iso_outer_size_reg_508;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        top_clusters_iso_outer_size_we0 = grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_iso_outer_size_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        top_clusters_iso_outer_size_we0 = grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_iso_outer_size_we0;
    end else begin
        top_clusters_iso_outer_size_we0 = top_clusters_iso_outer_size_we0_local;
    end
end

always @ (*) begin
    if (((cond_reg_513 == 1'd0) & (1'b1 == ap_CS_fsm_state9) & (clusters_valid_load_reg_446 == 1'd1) & (icmp_ln119_reg_437 == 1'd1))) begin
        top_clusters_iso_outer_size_we0_local = 1'b1;
    end else begin
        top_clusters_iso_outer_size_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        top_clusters_isolation_et_address0 = grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_isolation_et_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        top_clusters_isolation_et_address0 = grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_isolation_et_address0;
    end else begin
        top_clusters_isolation_et_address0 = zext_ln128_fu_382_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        top_clusters_isolation_et_ce0 = grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_isolation_et_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        top_clusters_isolation_et_ce0 = grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_isolation_et_ce0;
    end else begin
        top_clusters_isolation_et_ce0 = top_clusters_isolation_et_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        top_clusters_isolation_et_ce0_local = 1'b1;
    end else begin
        top_clusters_isolation_et_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        top_clusters_isolation_et_ce1 = grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_isolation_et_ce1;
    end else begin
        top_clusters_isolation_et_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        top_clusters_isolation_et_d0 = grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_isolation_et_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        top_clusters_isolation_et_d0 = grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_isolation_et_d0;
    end else begin
        top_clusters_isolation_et_d0 = candidate_isolation_et_reg_486;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        top_clusters_isolation_et_we0 = grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_isolation_et_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        top_clusters_isolation_et_we0 = grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_isolation_et_we0;
    end else begin
        top_clusters_isolation_et_we0 = top_clusters_isolation_et_we0_local;
    end
end

always @ (*) begin
    if (((cond_reg_513 == 1'd0) & (1'b1 == ap_CS_fsm_state9) & (clusters_valid_load_reg_446 == 1'd1) & (icmp_ln119_reg_437 == 1'd1))) begin
        top_clusters_isolation_et_we0_local = 1'b1;
    end else begin
        top_clusters_isolation_et_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        top_clusters_phi_address0 = grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_phi_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        top_clusters_phi_address0 = grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_top_clusters_phi_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        top_clusters_phi_address0 = grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_phi_address0;
    end else begin
        top_clusters_phi_address0 = zext_ln128_fu_382_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        top_clusters_phi_ce0 = grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_phi_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        top_clusters_phi_ce0 = grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_top_clusters_phi_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        top_clusters_phi_ce0 = grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_phi_ce0;
    end else begin
        top_clusters_phi_ce0 = top_clusters_phi_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        top_clusters_phi_ce0_local = 1'b1;
    end else begin
        top_clusters_phi_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        top_clusters_phi_ce1 = grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_phi_ce1;
    end else begin
        top_clusters_phi_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        top_clusters_phi_d0 = grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_phi_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        top_clusters_phi_d0 = grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_phi_d0;
    end else begin
        top_clusters_phi_d0 = candidate_phi_reg_497;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        top_clusters_phi_we0 = grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_phi_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        top_clusters_phi_we0 = grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_phi_we0;
    end else begin
        top_clusters_phi_we0 = top_clusters_phi_we0_local;
    end
end

always @ (*) begin
    if (((cond_reg_513 == 1'd0) & (1'b1 == ap_CS_fsm_state9) & (clusters_valid_load_reg_446 == 1'd1) & (icmp_ln119_reg_437 == 1'd1))) begin
        top_clusters_phi_we0_local = 1'b1;
    end else begin
        top_clusters_phi_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        top_clusters_valid_address0 = grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_valid_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        top_clusters_valid_address0 = grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_top_clusters_valid_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        top_clusters_valid_address0 = grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_valid_address0;
    end else begin
        top_clusters_valid_address0 = zext_ln128_reload_cast_reg_525;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        top_clusters_valid_ce0 = grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_valid_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        top_clusters_valid_ce0 = grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_top_clusters_valid_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        top_clusters_valid_ce0 = grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_valid_ce0;
    end else begin
        top_clusters_valid_ce0 = top_clusters_valid_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        top_clusters_valid_ce0_local = 1'b1;
    end else begin
        top_clusters_valid_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        top_clusters_valid_ce1 = grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_valid_ce1;
    end else begin
        top_clusters_valid_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        top_clusters_valid_d0 = grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_valid_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        top_clusters_valid_d0 = grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_valid_d0;
    end else begin
        top_clusters_valid_d0 = 1'd1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        top_clusters_valid_we0 = grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_valid_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        top_clusters_valid_we0 = grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_valid_we0;
    end else begin
        top_clusters_valid_we0 = top_clusters_valid_we0_local;
    end
end

always @ (*) begin
    if (((cond_reg_513 == 1'd0) & (1'b1 == ap_CS_fsm_state9) & (clusters_valid_load_reg_446 == 1'd1) & (icmp_ln119_reg_437 == 1'd1))) begin
        top_clusters_valid_we0_local = 1'b1;
    end else begin
        top_clusters_valid_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        top_clusters_window_size_address0 = grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_window_size_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        top_clusters_window_size_address0 = grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_window_size_address0;
    end else begin
        top_clusters_window_size_address0 = zext_ln128_fu_382_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        top_clusters_window_size_ce0 = grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_window_size_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        top_clusters_window_size_ce0 = grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_window_size_ce0;
    end else begin
        top_clusters_window_size_ce0 = top_clusters_window_size_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        top_clusters_window_size_ce0_local = 1'b1;
    end else begin
        top_clusters_window_size_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        top_clusters_window_size_ce1 = grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_window_size_ce1;
    end else begin
        top_clusters_window_size_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        top_clusters_window_size_d0 = grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_window_size_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        top_clusters_window_size_d0 = grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_window_size_d0;
    end else begin
        top_clusters_window_size_d0 = select_ln126_reg_517;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        top_clusters_window_size_we0 = grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_window_size_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        top_clusters_window_size_we0 = grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_top_clusters_window_size_we0;
    end else begin
        top_clusters_window_size_we0 = top_clusters_window_size_we0_local;
    end
end

always @ (*) begin
    if (((cond_reg_513 == 1'd0) & (1'b1 == ap_CS_fsm_state9) & (clusters_valid_load_reg_446 == 1'd1) & (icmp_ln119_reg_437 == 1'd1))) begin
        top_clusters_window_size_we0_local = 1'b1;
    end else begin
        top_clusters_window_size_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln118_fu_332_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((icmp_ln118_fu_332_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln119_fu_353_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (clusters_valid_q0_local == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((cond_reg_513 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln118_fu_338_p2 = (i_1_fu_66 + 11'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign clusters_et_address0 = zext_ln118_reg_427;

assign clusters_et_ce0 = clusters_et_ce0_local;

assign clusters_eta_address0 = zext_ln118_reg_427;

assign clusters_eta_ce0 = clusters_eta_ce0_local;

assign clusters_iso_outer_size_address0 = zext_ln118_reg_427;

assign clusters_iso_outer_size_ce0 = clusters_iso_outer_size_ce0_local;

assign clusters_isolation_et_address0 = zext_ln118_reg_427;

assign clusters_isolation_et_ce0 = clusters_isolation_et_ce0_local;

assign clusters_phi_address0 = zext_ln118_reg_427;

assign clusters_phi_ce0 = clusters_phi_ce0_local;

assign clusters_valid_address0 = zext_ln118_fu_344_p1;

assign clusters_valid_ce0 = clusters_valid_ce0_local;

assign clusters_valid_q0_local = clusters_valid_q0;

assign clusters_window_size_address0 = zext_ln118_reg_427;

assign clusters_window_size_ce0 = clusters_window_size_ce0_local;

assign cond_fu_358_p2 = ((grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_ap_return == 3'd0) ? 1'b1 : 1'b0);

assign grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_ap_start = grp_select_top_n_Pipeline_VITIS_LOOP_108_1_fu_267_ap_start_reg;

assign grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_ap_start = grp_select_top_n_Pipeline_VITIS_LOOP_128_3_fu_285_ap_start_reg;

assign grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_ap_start = grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_ap_start_reg;

assign icmp_ln118_fu_332_p2 = ((i_1_fu_66 == 11'd1800) ? 1'b1 : 1'b0);

assign icmp_ln119_fu_353_p2 = (($signed(zext_ln118_1_fu_349_p1) < $signed(num_clusters)) ? 1'b1 : 1'b0);

assign select_ln126_fu_364_p3 = ((candidate_window_size_reg_503[0:0] == 1'b1) ? 2'd3 : 2'd0);

assign top_clusters_et_address1 = grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_et_address1;

assign top_clusters_eta_address1 = grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_eta_address1;

assign top_clusters_iso_outer_size_address1 = grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_iso_outer_size_address1;

assign top_clusters_isolation_et_address1 = grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_isolation_et_address1;

assign top_clusters_phi_address1 = grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_phi_address1;

assign top_clusters_valid_address1 = grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_valid_address1;

assign top_clusters_window_size_address1 = grp_select_top_n_Pipeline_VITIS_LOOP_131_4_fu_305_top_clusters_window_size_address1;

assign zext_ln118_1_fu_349_p1 = i_1_fu_66;

assign zext_ln118_fu_344_p1 = i_1_fu_66;

assign zext_ln128_fu_382_p1 = j_loc_fu_74;

assign zext_ln128_reload_cast_fu_378_p1 = zext_ln128_loc_fu_70;

always @ (posedge ap_clk) begin
    zext_ln118_reg_427[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
    zext_ln128_reload_cast_reg_525[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
end

endmodule //calo_trigger_ref_select_top_n
